### ISSUE TITLE
[Feature Request] Cloaking Feature

### ISSUE THREAD

**Issue by ykamei** [Equals182/eqFTP#101]
Thank you for your nice extension.

May I request the feature?
To ignore some files/folders which have specific extension (or names) for upload, I want eqFTP to have cloaking feature.
Please consider to support this.

**Comment by Equals182** [comment]
This is already a feature in v0.7.0. Check it, `sync` automatization type, `Ignore list` option. It should work like `.gitignore`.

**Comment by ykamei** [comment]
Thank you for your replying.

I installed eqFTP v0.7.0 which released today.
And I clicked the icon, but eqFTP doesn't appear on Brackets(Release 1.2 build 1.2.0-15697).

**Comment by Equals182** [comment]
Have you tried to restart Brackets manually?
If yes and nothing happened, please [follow this steps here](http://equals182.github.io/eqFTP/#creating-issue). You can skip first step and post everything here.

**Comment by knorrre** [comment]
Same problem here. Brackets does not show an update for eqFTP. Still on 0.6.3.

**Comment by Equals182** [comment]
there's no update to v0.7.0 in registry due the problem: https://twitter.com/Equals182/status/572626121721843712
you can still update directly using this link: https://github.com/Equals182/eqFTP

**Comment by ykamei** [comment]
Yes, I restarted Brackets manually.

Is this OK? I clicked eqFTP icon on toolbar, then it maybe caused some error.
[eqFTP] Loaded (v0.7.0) main.js:1549
Uncaught SyntaxError: Unexpected token [  index.html:11
Uncaught SyntaxError: Unexpected token [  index.html:11
Uncaught SyntaxError: Unexpected token [  index.html:11

**Comment by Equals182** [comment]
Have you seen this line in your log?
```
[node-log 8:42:23 AM] [eqFTP-ftpDomain] Loaded
```

**Comment by ykamei** [comment]
Sorry for forgetting the line.
I found it.

> [node-log 11:30:35 AM] [eqFTP-ftpDomain] Loaded  NodeDebugUtils.js:117

**Comment by Equals182** [comment]
hmm.. That's weird.
I'll make some changes for you to debug this stuff, but I'm pretty sure it's just a weird random bug that I can't really control. Me and Wikunia have those fairly often when he updating eqFTP. Like #104. I just gave him same version with just 2 new lines of `console.log` and, hey presto, It's working for him somehow!

So for now I would sugget to (it should take about 2-3 minutes for you):
1. Uninstall eqFTP complitely
2. Restart Brackets
3. Debug->Restart Node
4. Wait a second and press F5
5. Install eqFTP and try again

If it still doesn't work for you - I'll add console.log lines to check where it's stucking.

**Comment by ykamei** [comment]
Thank you for your replying.
I delete Brackets and any extensions including eqFTP and any configuration file. 
Then I installed Brackets and eqFTP again.
But this issue is still caused.

Following function at line 1525 to 1528 is not called when I clicked the icon on toolbar.

>                eqFTP.sf.settings.read(function(result) {
                    console.log("test for showing eqFTP"); // This log is not appeared on the console.
                    if (result)
                        eqFTP.sf.fileTree.show(e);
>                });

**Comment by Equals182** [comment]
Oh.. That's really weird. Maybe something wrong with your settings file.
Since you're debugging it yourself, you can use DevTools (press F12 in Brackets) and debug with Breakpoints, not console logs (except when you debug node - then it's console log only).
I can add console lines for you, but it's faster to use breakpoints now. Try debugging `eqFTP.sf.settings.read` and find where it's stuck.

To use breakpoints you should open DevTools, open Sources tab, find your Breackets extensions folder in filetree on left side of window, open main.js in eqFTP's folder.

And I'm really sorry for putting this task on you.

**Comment by ykamei** [comment]
I found the reason.
I tried to use Breakpoints, and I noticed the variable "result" was including the ftp connection settings!

I'm very sorry for forgetting to delete the eqFTP Projects/.remotesettings .
After deleting the setting file, I can found the window at last. 

And I could find the cloaking future!
Thank you for your nice extension and kindly replying.

**Comment by ykamei** [comment]
sorry for my replying again.
I want to use the cloaking future when I upload the site manually (right click and upload).
Can I use this future except `sync` option?

**Comment by Equals182** [comment]
Actually, deleting settings should not be necessary. There was something wrong with settings, though. Glad you solved this but sorry for loosing your connections settings.

No.. there's no way using cloaking without sync, sorry. Is this a problem?
Also please be carefull still. I found out that cloaking work weird and I'm gonna fix it as soon as possible.

**Comment by ykamei** [comment]
> No.. there's no way using cloaking without sync, sorry. Is this a problem?

Manual uploading is necessary for me because I want to upload to the real server after test on the local. 
Sorry for my putting you to trouble. I'm glad if you consider this.

**Comment by Equals182** [comment]
Oh, I'm dumb. It should actually work with any kind of uploads, downloads, renames and deletes.
But I'm gonna double check it today later. In like 7-8 hours or so. Gotta work for now :)

**Comment by ykamei** [comment]
Ah, sorry. 
It's working for right click uploading except under the folder which is the pattern of matching for ignore.
(But only the folder for ignoring was created on the server.)

**Comment by Equals182** [comment]
So.. It's like.. ignoring files in folder but still creates folder itself?

**Comment by ykamei** [comment]
Yes, it is probably.

I put to Ignore List
`ignore/`

But still created the "ignore" folder itself.

**Comment by Equals182** [comment]
I'll check this feature as soon as possible.
