### ISSUE TITLE
Progress (bar/loading icon)

### ISSUE THREAD

**Issue by Tomgroot** [Equals182/eqFTP#102]
A progress bar would really bring a very handy feature. Especially with uploading big files, you do not know when its finished.
When the upload is finished the icon of eqFTP changes to a check-icon. Can the icon be a loading-icon when its bussy uploading(/downloading)?

(or even make somewhere room for a progress bar, but a loading-icon seems much simpler)

**Comment by Equals182** [comment]
This is already  a feature in version you're using. You just need to open queue (originally bottom right corner of screen) or you could download new version from github directly and there will be an animated icon when file is in process and also a progress bar in queue.
