### ISSUE TITLE
no symlinks displayed

### ISSUE THREAD

**Issue by knorrre** [Equals182/eqFTP#106]
Hi,

is there any option to display symlinks? Currently I can not see them.

Best regards!

**Comment by Equals182** [comment]
No, there's no option to display them and more over - I set to ignore them, displaying just files and folders. If there's a telling argument why they should be here - please tell me, I'll think about supporting them.

**Comment by knorrre** [comment]
At my hoster uberspace all users can manage stuff in their /home. But public files are located at /var/www/virtual/unsername/html. In home directory this html-directory is linked with a symlink. In deed users are able to change in this directory, but with symlink it is much easier. ;)
Maybe eqFTP can have an option for displaying symlinks (checkbox in general settings or connection setting)?

**Comment by Equals182** [comment]
I'm not sure how to make this real yet, but if it is possible - I'll try to do this

**Comment by shivanandsharma** [comment]
Instead of traversing 5 directories, I'd just like to create a symlink to the folder form root and be able to use it.

**Comment by knorrre** [comment]
According to #147 creation or at least displaying of symlinks will not be integrated?

**Comment by Equals182** [comment]
Not yet. I *probably* can manage to implement symlinks, but only those that point to file/directory **inside** **remote_path**, because traveling up, above root folder may cause *really* unexpected results.

**Comment by Equals182** [comment]
### Hello there!

I know this issue been there for a pretty long time, but I have some good news here!
We just released eqFTP v**1.0.0-beta.0** (v1-b for short I guess) and we're completely discontinuing support of all previous versions of this plugin.
New version works great on Brackets 1.8 and it should be good on lower versions too.

So yeah, we're closing and locking this issue forever and looking forward for you to try out our new version of eqFTP.
I'm sorry if I somehow disturbed you, or you lost your interest in eqFTP or Brackets in general, we're not going to make any noise here again.

If you have any questions, please contact me via email (you can find it in [my profile](https://github.com/Equals182)) or [Telegram app](http://t.me/equals182)

Thank you for understanding 😊
