### ISSUE TITLE
[Feature Request] Order of connections

### ISSUE THREAD

**Issue by knorrre** [Equals182/eqFTP#107]
Hi,

is there any possibility to change the order of the conncection entries?
E. g. A-Z/asc, Z-A/desc, creation date or drag'n'drop?

Regards

**Comment by Equals182** [comment]
For now there's no way to change order of Conections but I already thought about that and I'll definitely add this feature.

**Comment by knorrre** [comment]
Cool, thanks!!

**Comment by Equals182** [comment]
Added in fee92cf694dd435eb4f5862c81784b0539c04fef
