### ISSUE TITLE
FTP file list instead of project list 

### ISSUE THREAD

**Issue by Kershrew** [Equals182/eqFTP#110]
I never work with files locally on my computer after setting up a websites framework, it's all done off the server.

Is there any way to replace the file list pane on the left of brackets with the list of files from the server?

This is probably a feature request but I'd love it :+1:

**Comment by pozd** [comment]
I also would like this feature. It is not comfortable to allways open ftp to find files. I would like to see them all the time on left. Should make switch local/remote to change view :)

**Comment by mjbrancato** [comment]
I agree, I would love this feature as well. Might be kind of hard because I think Brackets expects the left sidebar to be the way it is (so constraining).

**Comment by Equals182** [comment]
### Hello there!

I know this issue been there for a pretty long time, but I have some good news here!
We just released eqFTP v**1.0.0-beta.0** (v1-b for short I guess) and we're completely discontinuing support of all previous versions of this plugin.
New version works great on Brackets 1.8 and it should be good on lower versions too.

So yeah, we're closing and locking this issue forever and looking forward for you to try out our new version of eqFTP.
I'm sorry if I somehow disturbed you, or you lost your interest in eqFTP or Brackets in general, we're not going to make any noise here again.

If you have any questions, please contact me via email (you can find it in [my profile](https://github.com/Equals182)) or [Telegram app](http://t.me/equals182)

Thank you for understanding 😊
