### ISSUE TITLE
These features will make eqFTP the best FTP plugin for Brackets

### ISSUE THREAD

**Issue by Savesx** [Equals182/eqFTP#111]
---
## New Features
1. Linking Documents
   Have the ability to link a document so that when you save, it uploads both documents. This would be extremely useful for pre-processors like SASS. Working with SASS files and when you save, eqFTP uploads the CSS document that it's linked to.
2. Remember Password
   Ability to remember the password so that you don't have to type it in every time you re-launch program.

---
## Issues
1. Uploading files in new directories
   When I create a new folder on my local host and upload it, it won't work. I have to open a 3rd party FTP in order to upload the new folder for eqFTP to be able to work.
2. Randomly breaks and won't upload
   I don't know what it is, randomly eqFTP decides it doesn't want to upload anymore. Then I have to open a 3rd party program to handle my FTP. It's really annoying.

**Comment by Equals182** [comment]
1. This is a thing in v0.7.0
2. This is against the idea of master password 

1. This should be fixed in v0.7.0
2. This could still exist in new version unfortunately

**Comment by Savesx** [comment]
1. Really? How do I go about setting that up? I can't find out how to do it anywhere.

2. You should give us the option, I'm personally okay with it remembering the password.

3. Sweet! I absolutely can't wait for v0.7.0!

4. What is causing it??

**Comment by Equals182** [comment]
1. It's in v0.7.0. To install it right now, follow instructions [here](http://equals182.github.io/eqFTP/#installing) (Installing beta version). Set up [**Sync**](http://equals182.github.io/eqFTP/#sync) (file update is for you)
2. Dude, if it will remebmer master password then there's no point to encrypt your data with it. For people who bothered with entering password again and again - just turn off Master Password. It's simple: programm saves your master password -> hacker can take it and easily decrypt settings with it.
3. Follow №1 to install v0.7.0
4. Lots of stuff can cause this problem. Can be just poor error (or forced disconnection) handling in jsftp or something. I've tried to improve it and I will improve it more in new versions.

**Comment by sasagit** [comment]
I installed beta version from link and have problems with master password, whatever I enter it says: Can't read settings file. You probably mistyped your master password.

**Comment by Equals182** [comment]
Weird. 
1. Backup your `.remotesettings` file (should be in folder that set in **Folder for Settings**)
2. Downgrade (delete eqFTP and install it from extension manager)
3. Load eqFTP and uncheck **Master Password** option and save
4. Upgrade again and try to load eqFTP with master password off

If it's working - temporary backup your decrypted settings file and then try to use **Master Password** again

**Comment by Equals182** [comment]
Also, are you Savesx? Or you just too lazy to create an issue?

**Comment by Equals182** [comment]
### Hello there!

I know this issue been there for a pretty long time, but I have some good news here!
We just released eqFTP v**1.0.0-beta.0** (v1-b for short I guess) and we're completely discontinuing support of all previous versions of this plugin.
New version works great on Brackets 1.8 and it should be good on lower versions too.

So yeah, we're closing and locking this issue forever and looking forward for you to try out our new version of eqFTP.
I'm sorry if I somehow disturbed you, or you lost your interest in eqFTP or Brackets in general, we're not going to make any noise here again.

If you have any questions, please contact me via email (you can find it in [my profile](https://github.com/Equals182)) or [Telegram app](http://t.me/equals182)

Thank you for understanding 😊
