### ISSUE TITLE
SFTP with password encrypted RSA key

### ISSUE THREAD

**Issue by maciej-kolodziejczak** [Equals182/eqFTP#112]
There is a problem with connecting to a server via SFTP with encrypted SSH key. When I make new connection and choose a valid key: `uncaught exception at top level, exiting. Error: Encrypted private key detected, but no passphrase given`. I've not seen any field to enter that passphrase.

Another error I'm encountering is `[eqFTP-ftpDomain]: [c.d] There's no connection with this ID: 0. true` when I change something in a single connection and/or error above shows up.

Brackets v.1.2 build 1.2.0-15697, eqFTP v.0.7.0

**Comment by Equals182** [comment]
Sorry, I forgot to add passphrase support, will do
As for second error - I'll take a look as well. I'm currently redesigning ID system of Connections so I'll try fix this issue.

**Comment by Equals182** [comment]
May I ask you some stuff about passphrase? What format does it have? Is it string and is it ok to use password field for it?

**Comment by maciej-kolodziejczak** [comment]
Just a plain string with special chars and numbers. Password field is perfect for if



—

**Comment by Equals182** [comment]
I'm gonna add this soon but I'm not able to test passphrase for rsa. So I hope everything is working fine by default

**Comment by Equals182** [comment]
Can you please test passphrase feature for me? I uploaded new version here: https://github.com/Equals182/Buggy-eqFTP

**Comment by maciej-kolodziejczak** [comment]
Hi there,

I don't see any new field for password so I've just typed password into a "Password" field, and it keeps disconnecting all the time.

The first screenshot is when using private key and the second when using public key.

![screenshot 2015-03-22 22 43 55](https://cloud.githubusercontent.com/assets/6781344/6771664/30f464ca-d0e5-11e4-872a-4d2c7eca5203.png)
![screenshot 2015-03-22 22 44 00](https://cloud.githubusercontent.com/assets/6781344/6771665/312282d8-d0e5-11e4-8428-966ed5055a1a.png)

**Comment by Equals182** [comment]
That will be hard to debug remotely. I'll try to setup sftp and encoded private keys on virtual machinve and then fix error. 
Sorry for inconvenience.

**Comment by Equals182** [comment]
Hi again
Please, update from `https://github.com/Equals182/eqFTP` and try to connect. Use passphrase in password field and path to private key in RSA key field.
It should work, I just tested it on virtual Ubuntu with open-ssh (I guess) keys that it generated for me.
