### ISSUE TITLE
Options menu not working

### ISSUE THREAD

**Issue by Freshchris01** [Equals182/eqFTP#113]
Hy, when I click the gearwheel for the options menu I get asked for the password. If I type a wrong password I get asked to type it in again, which is as you want it . But when I type in the correct password in, I don't get any feedback. No alert opens and no other window opens. Am I missing something?
Greetings Christian

**Comment by Equals182** [comment]
Hi
Can you please attach your logs here? [Here's manual on how to do this](http://equals182.github.io/eqFTP/#creating-issue)

**Comment by Freshchris01** [comment]
Ok, I updated to 0.7.0 and now everything seems to work fine! Thanks for this great plugin.
