### ISSUE TITLE
SFTP & FTPS are greyed out

### ISSUE THREAD

**Issue by napa-web-designer** [Equals182/eqFTP#115]
I am newly using this extension.  I read your instructions.  When creating a New Connection, SFTP and FTPS are not selectable for the Protocol Type.  I would like to connect using SFTP but cannot.  Not sure if this is a bug or what I am missing.

Thanks,

**Comment by Equals182** [comment]
Hello,
You most likely installing eqFTP from extension manager that have v0.6.2 of eqFTP. SFTP is supported since v0.7.0 which is still under development. You can donwload latest version from here: https://github.com/Equals182/Buggy-eqFTP

**Comment by napa-web-designer** [comment]
Thanks for the quick response.  Do you have a rough idea of when version 7 will leave the realm of buggy?

**Comment by Equals182** [comment]
I don't experience any problems right now. I need to test SFTP more, I guess, but it should work now. The thing is that usually I don't work with SFTP at all, and I've tested it as much as possible on a virtual machine.

**Comment by napa-web-designer** [comment]
ok.  Thanks.  I will give it a spin and let you know if I run into any issues.  

FYI - I did not test it out and experience any issues with it being buggy, I just went with the topic name of the page where the download link took me :)

**Comment by Equals182** [comment]
I've got it, no problems :) 
Yeah, please, [create an issue](http://equals182.github.io/eqFTP/#creating-issue) if you find something.

**Comment by napa-web-designer** [comment]
I'm back.  I realize I do have one question perhaps obvious to some but not me.  If I download from GitHub from that link, how do I update the install I already have running, with the settings I already have?

Thanks

**Comment by Equals182** [comment]
You can use **Install from URL** in **Extension Manager** that's where you need link I gave you.

**Comment by napa-web-designer** [comment]
thanks

**Comment by napa-web-designer** [comment]
do I delete the original one first, or just expect it to be replaced auto?

**Comment by Equals182** [comment]
It should be replaced automatically

**Comment by napa-web-designer** [comment]
it did thanks.
