### ISSUE TITLE
Do I need to update manually?

### ISSUE THREAD

**Issue by Madebym** [Equals182/eqFTP#117]
eqFTP started behaving weirdly lately, sometimes it saves, sometimes it don't. The weirdest was that it only saves once after connecting and after that nothing. That happened a lot lately.

That is why I visited GitHub page and saw that the current version is 0.7, while mine was 0.6. I deleted and installed from URL the new version and it works fine now.

Why there were no notifications in my Brackets, should I check myself for newer versions from now on, or it is just some sort of bug? 
Also my laptop still has 0.6 version, also no notifications there.

**Comment by Equals182** [comment]
That's because v070 is still on beta test. And another reason - extension registry denied new version for some reason so now I'm fixing bugs, testing it and then I'll try to upload it in registry again

**Comment by Madebym** [comment]
Ok, that explains it!! Sorry for the hassle. BTW, the new version works fine for me, I've had issues with the past version.
