### ISSUE TITLE
Remote Tree Error

### ISSUE THREAD

**Issue by rzvngbrl** [Equals182/eqFTP#118]
Hi,
I'm trying for a few hours now, to make it work but no luck for me.

Every server I try to connect, it connects successfully but instead of listing the dir, files it shows something like this:

_view_pdf.phpmodify=20150319171743;perm=flcdmpe;type=dir;unique=FD00U2689ED;UNIX.group=2522;UNIX.mode=0755;UNIX.owner=10001;

I'm on MAC, running latest Brackets version, and with the latest version of eqFtp
Server Side: ProFTPD Version 1.3.4d 

No other files are listed except the one I've pasted here.

Looking forward for your hint.

![screen shot 2015-03-24 at 21 36 14](https://cloud.githubusercontent.com/assets/8759592/6811055/d8e1b636-d26d-11e4-8c67-812d1330c602.png)

Thanks,
R

**Comment by Equals182** [comment]
Hi
Can you please add some logs? [This is how you can do it](http://equals182.github.io/eqFTP/#creating-issue). You can skip first step, obviously, I just need a console output.

**Comment by rzvngbrl** [comment]
NodeDebugUtils.js:117 [node-log 9:46:22 PM] DEBUG:  user_command
NodeDebugUtils.js:117 [node-log 9:46:22 PM] "NOOP"
NodeDebugUtils.js:117 [node-log 9:46:22 PM] DEBUG:  server_response
NodeDebugUtils.js:117 [node-log 9:46:22 PM] {
  "code": 200,
  "text": "200 NOOP command successful",
  "isMark": false,
  "isError": false
}
NodeDebugUtils.js:117 [node-log 9:46:23 PM] [eqFTP-ftpDomain]: Connecting to this ID: 1
NodeDebugUtils.js:117 [node-log 9:46:23 PM] [eqFTP-ftpDomain]: Connecting...
main.js:2537 [eqFTP] Connected to server
NodeDebugUtils.js:117 [node-log 9:46:23 PM] [eqFTP-ftpDomain]: Connected...
NodeDebugUtils.js:117 [node-log 9:46:23 PM] DEBUG:  server_response
NodeDebugUtils.js:117 [node-log 9:46:23 PM] {
  "code": 220,
  "text": "220 FTP Server ready.",
  "isMark": false,
  "isError": false
}
NodeDebugUtils.js:117 [node-log 9:46:23 PM] DEBUG:  user_command
NodeDebugUtils.js:117 [node-log 9:46:23 PM] "user frilame"
NodeDebugUtils.js:117 [node-log 9:46:23 PM] DEBUG:  server_response
NodeDebugUtils.js:117 [node-log 9:46:23 PM] {
  "code": 331,
  "text": "331 Password required for frilame",
  "isMark": false,
  "isError": false
}
NodeDebugUtils.js:117 [node-log 9:46:23 PM] DEBUG:  user_command
NodeDebugUtils.js:117 [node-log 9:46:23 PM] "pass *********"
NodeDebugUtils.js:117 [node-log 9:46:23 PM] DEBUG:  server_response
NodeDebugUtils.js:117 [node-log 9:46:23 PM] {
  "code": 230,
  "text": "230 User frilame logged in",
  "isMark": false,
  "isError": false
}
NodeDebugUtils.js:117 [node-log 9:46:23 PM] DEBUG:  user_command
NodeDebugUtils.js:117 [node-log 9:46:23 PM] "feat"
NodeDebugUtils.js:117 [node-log 9:46:24 PM] DEBUG:  server_response
NodeDebugUtils.js:117 [node-log 9:46:24 PM] {
  "code": 211,
  "text": "211-Features:\n MDTM\n MFMT\n TVFS\n UTF8\n LANG zh-TW;ko-KR;it-IT;es-ES;fr-FR;ru-RU;bg-BG;en-US;zh-CN;ja-JP\n MFF modify;UNIX.group;UNIX.mode;\n MLST modify*;perm*;size*;type*;unique*;UNIX.group*;UNIX.mode*;UNIX.owner*;\n REST STREAM\n SIZE\n211 End",
  "isMark": false,
  "isError": false
}
NodeDebugUtils.js:117 [node-log 9:46:24 PM] [eqFTP-ftpDomain]: Getting remote root for this ID: 1
NodeDebugUtils.js:117 [node-log 9:46:32 PM] DEBUG:  user_command
NodeDebugUtils.js:117 [node-log 9:46:32 PM] "NOOP"
NodeDebugUtils.js:117 [node-log 9:46:32 PM] DEBUG:  server_response
NodeDebugUtils.js:117 [node-log 9:46:32 PM] {
  "code": 200,
  "text": "200 NOOP command successful",
  "isMark": false,
  "isError": false
}
NodeDebugUtils.js:117 [node-log 9:46:34 PM] DEBUG:  user_command
NodeDebugUtils.js:117 [node-log 9:46:34 PM] "NOOP"
NodeDebugUtils.js:117 [node-log 9:46:34 PM] DEBUG:  server_response
NodeDebugUtils.js:117 [node-log 9:46:34 PM] {
  "code": 200,
  "text": "200 NOOP command successful",
  "isMark": false,
  "isError": false
}

**Comment by rzvngbrl** [comment]
and then, is the keepalive:

[node-log 9:47:24 PM] DEBUG:  user_command
NodeDebugUtils.js:117 [node-log 9:47:24 PM] "NOOP"
NodeDebugUtils.js:117 [node-log 9:47:24 PM] DEBUG:  server_response
NodeDebugUtils.js:117 [node-log 9:47:24 PM] {
  "code": 200,
  "text": "200 NOOP command successful",
  "isMark": false,
  "isError": false
}

**Comment by rzvngbrl** [comment]
On refresh I get this:

[node-log 9:50:56 PM] [eqFTP-ftpDomain]: Queue updated: [{"type":"folder","connectionID":1,"path":""},{"type":"folder","connectionID":1,"path":""}]
NodeDebugUtils.js:117 [node-log 9:50:56 PM] [eqFTP-ftpDomain]: Connecting to this ID: 1
NodeDebugUtils.js:117 [node-log 9:50:56 PM] [eqFTP-ftpDomain]: Connection already exists for this ID: 1
NodeDebugUtils.js:117 [node-log 9:50:56 PM] [eqFTP-ftpDomain]: Connecting to this ID: 1
NodeDebugUtils.js:117 [node-log 9:50:56 PM] [eqFTP-ftpDomain]: Connection already exists for this ID: 1
NodeDebugUtils.js:117 [node-log 9:50:56 PM] DEBUG:  user_command
NodeDebugUtils.js:117 [node-log 9:50:56 PM] "TYPE I"
NodeDebugUtils.js:117 [node-log 9:50:56 PM] DEBUG:  server_response
NodeDebugUtils.js:117 [node-log 9:50:56 PM] {
  "code": 200,
  "text": "200 Type set to I",
  "isMark": false,
  "isError": false
}
NodeDebugUtils.js:117 [node-log 9:50:56 PM] DEBUG:  user_command
NodeDebugUtils.js:117 [node-log 9:50:56 PM] "PASV"
NodeDebugUtils.js:117 [node-log 9:50:56 PM] DEBUG:  server_response
NodeDebugUtils.js:117 [node-log 9:50:56 PM] {
  "code": 227,
  "text": "227 Entering Passive Mode (86,122,175,189,128,232).",
  "isMark": false,
  "isError": false
}
NodeDebugUtils.js:117 [node-log 9:50:56 PM] DEBUG:  user_command
NodeDebugUtils.js:117 [node-log 9:50:56 PM] "MLSD /"
NodeDebugUtils.js:117 [node-log 9:50:56 PM] DEBUG:  server_response
NodeDebugUtils.js:117 [node-log 9:50:56 PM] {
  "code": 150,
  "text": "150 Opening BINARY mode data connection for MLSD",
  "isMark": true,
  "isError": false
}
NodeDebugUtils.js:117 [node-log 9:50:56 PM] [eqFTP-ftpDomain]: 745: Got Directory: /
NodeDebugUtils.js:117 [node-log 9:50:56 PM] [eqFTP-ftpDomain]: Got folder: /
NodeDebugUtils.js:117 [node-log 9:50:56 PM] DEBUG:  server_response
NodeDebugUtils.js:117 [node-log 9:50:56 PM] {
  "code": 226,
  "text": "226 Transfer complete",
  "isMark": false,
  "isError": false
}

**Comment by Equals182** [comment]
Alright, lets try something different. Update from this url `https://github.com/Equals182/Buggy-eqFTP` (use Install from URL in Extension Manager), restart Brackets manually and try to connect. If nothing changes, I'll add some new log lines for you to see what server return to you.

**Comment by rzvngbrl** [comment]
[node-log 10:03:47 PM] [eqFTP-queueisbusy][s.sKA 2] Setting busy to false
NodeDebugUtils.js:117 [node-log 10:03:49 PM] [eqFTP-ftpDomain]: 1837: [q.a] Queue updated: {"a":[{"type":"folder","connectionID":1,"path":"/","id":"f_1427227429417968","state":"opened","queue":"a"}],"p":[],"f":[],"s":[]}
main.js:1624 Object {event: "queue_update", connectionID: 1, element: Object}
main.js:1624 Object {event: "working", work: true}
main.js:1624 Object {event: "queue_update", connectionID: 1, element: Object}
NodeDebugUtils.js:117 [node-log 10:03:49 PM] [eqFTP-queueisbusy][q.p just started] Setting busy to true
2NodeDebugUtils.js:117 [node-log 10:03:49 PM] [eqFTP-ftpDomain]: [c.c] Connection already exists for this ID: 1
NodeDebugUtils.js:117 [node-log 10:03:49 PM] DEBUG:  user_command
NodeDebugUtils.js:117 [node-log 10:03:49 PM] "TYPE I"
NodeDebugUtils.js:117 [node-log 10:03:49 PM] DEBUG:  server_response
NodeDebugUtils.js:117 [node-log 10:03:49 PM] {
  "code": 200,
  "text": "200 Type set to I",
  "isMark": false,
  "isError": false
}
NodeDebugUtils.js:117 [node-log 10:03:49 PM] DEBUG:  user_command
NodeDebugUtils.js:117 [node-log 10:03:49 PM] "PASV"
NodeDebugUtils.js:117 [node-log 10:03:49 PM] DEBUG:  server_response
NodeDebugUtils.js:117 [node-log 10:03:49 PM] {
  "code": 227,
  "text": "227 Entering Passive Mode (86,122,175,189,228,118).",
  "isMark": false,
  "isError": false
}
NodeDebugUtils.js:117 [node-log 10:03:49 PM] DEBUG:  user_command
NodeDebugUtils.js:117 [node-log 10:03:49 PM] "MLSD /"
NodeDebugUtils.js:117 [node-log 10:03:50 PM] DEBUG:  server_response
NodeDebugUtils.js:117 [node-log 10:03:50 PM] {
  "code": 150,
  "text": "150 Opening BINARY mode data connection for MLSD",
  "isMark": true,
  "isError": false
}
NodeDebugUtils.js:117 [node-log 10:03:50 PM] [eqFTP-ftpDomain]: 1125: [s.gP] Got Directory: /
NodeDebugUtils.js:117 [node-log 10:03:50 PM] [eqFTP-queueisbusy][q.p folder] Setting busy to false
NodeDebugUtils.js:117 [node-log 10:03:50 PM] [eqFTP-ftpDomain]: [q.p] Got folder: /
main.js:1624 Object {event: "directory_got", err: false, files: Array[1], path: "/", connectionID: 1…}
main.js:1624 Object {event: "working", work: false}
NodeDebugUtils.js:117 [node-log 10:03:50 PM] [eqFTP-ftpDomain]: [q.p] Queue is empty
NodeDebugUtils.js:117 [node-log 10:03:50 PM] DEBUG:  server_response
NodeDebugUtils.js:117 [node-log 10:03:50 PM] {
  "code": 226,
  "text": "226 Transfer complete",
  "isMark": false,
  "isError": false
}
NodeDebugUtils.js:117 [node-log 10:03:57 PM] [eqFTP-queueisbusy][s.sKA 1] Setting busy to true
NodeDebugUtils.js:117 [node-log 10:03:57 PM] [eqFTP-ftpDomain]: [c.c] Connection already exists for this ID: 1
NodeDebugUtils.js:117 [node-log 10:03:57 PM] DEBUG:  user_command
NodeDebugUtils.js:117 [node-log 10:03:57 PM] "NOOP"
NodeDebugUtils.js:117 [node-log 10:03:57 PM] DEBUG:  server_response
NodeDebugUtils.js:117 [node-log 10:03:57 PM] {
  "code": 200,
  "text": "200 NOOP command successful",
  "isMark": false,
  "isError": false
}
NodeDebugUtils.js:117 [node-log 10:03:57 PM] [eqFTP-queueisbusy][s.sKA 2] Setting busy to false

**Comment by rzvngbrl** [comment]
[node-log 10:03:50 PM] [eqFTP-ftpDomain]: [q.p] Got folder: /
main.js:1624 Object {event: "directory_got", err: false, files: Array[1], path: "/", connectionID: 1…}connectionID: 1err: falseevent: "directory_got"files: Array[1]0: Objectname: "comanda_externa.php↵modify=20140123122211;perm=adfrw;size=1541;type=file;unique=803U7FF18;UNIX.group=502;UNIX.mode=0766;UNIX.owner=502; androidpost.php↵modify=20150123133934;perm=adfrw;size=5431;type=file;unique=803U7FEC2;UNIX.group=502;UNIX.mode=0777;UNIX.owner=502; comanda_produse.php↵modify=20140520155044;perm=adfrw;size=5556;type=file;unique=803U7FEFF;UNIX.group=502;UNIX.mode=0777;UNIX.owner=502; lista_comenzi.php↵modify=20130723170249;perm=adfrw;size=2076;type=file;unique=803U7FC6C;UNIX.group=502;UNIX.mode=0777;UNIX.owner=502; login.php↵modify=20130307015049;perm=adfrw;size=488;type=file;unique=803U7FEC7;UNIX.group=502;UNIX.mode=0777;UNIX.owner=502; fisa_produs.php↵modify=20130314162650;perm=adfrw;size=221;type=file;unique=803U7FEC5;UNIX.group=502;UNIX.mode=0777;UNIX.owner=502; fisa_partener_contact.php↵modify=20130402200615;perm=adfrw;size=0;type=file;unique=803U80008;UNIX.group=502;UNIX.mode=0777;UNIX.owner=502; qr.php↵modify=20130412190934;perm=adfrw;size=488;type=file;unique=803U7FEC8;UNIX.group=502;UNIX.mode=0777;UNIX.owner=502; fisa_produs.phps↵modify=20140520150125;perm=adfrw;size=2128;type=file;unique=803U7FF16;UNIX.group=502;UNIX.mode=0777;UNIX.owner=502; update.php↵modify=20150123130811;perm=adfrw;size=6896;type=file;unique=803U7FEFD;UNIX.group=502;UNIX.mode=0777;UNIX.owner=502; index.php↵modify=20130729001722;perm=adfrw;size=2642;type=file;unique=803U802F2;UNIX.group=502;UNIX.mode=0766;UNIX.owner=502; lista_facturi.php↵modify=20140109113949;perm=adfrw;size=3580;type=file;unique=803U7FEC3;UNIX.group=502;UNIX.mode=0777;UNIX.owner=502; detalii_receptie.php↵modify=20130315121334;perm=adfrw;size=0;type=file;unique=803U7FF45;UNIX.group=502;UNIX.mode=0777;UNIX.owner=502; img.php↵modify=20130729012812;perm=adfrw;size=95;type=file;unique=803U80307;UNIX.group=502;UNIX.mode=0766;UNIX.owner=502; utilizatori.php↵modify=20131210171956;perm=adfrw;size=4315;type=file;unique=803U804B7;UNIX.group=502;UNIX.mode=0777;UNIX.owner=502; comanda_externa_document.php↵modify=20130729001648;perm=adfrw;size=2642;type=file;unique=803U80304;UNIX.group=502;UNIX.mode=0766;UNIX.owner=502; lista_bonuri.php↵modify=20130713153615;perm=adfrw;size=52568;type=file;unique=803U7FEB8;UNIX.group=502;UNIX.mode=0777;UNIX.owner=502; photorec.ses↵modify=20130930005137;perm=adfrw;size=8990;type=file;unique=803U7FECC;UNIX.group=502;UNIX.mode=0777;UNIX.owner=502; genComanda.php↵modify=20150123131640;perm=adfrw;size=4893;type=file;unique=803U7FF01;UNIX.group=502;UNIX.mode=0777;UNIX.owner=502; lista_produse.php↵modify=20130731183524;perm=adfrw;size=3263;type=file;unique=803U7FC45;UNIX.group=502;UNIX.mode=0766;UNIX.owner=502; factura_produse.php↵modify=20131029125808;perm=adfrw;size=4297;type=file;unique=803U7FEC9;UNIX.group=502;UNIX.mode=0777;UNIX.owner=502; fisa_produs_retetar.php↵modify=20130729001940;perm=adfrw;size=2643;type=file;unique=803U80303;UNIX.group=502;UNIX.mode=0766;UNIX.owner=502; lista_avize.php↵modify=20130731195259;perm=adfrw;size=2436;type=file;unique=803U7FF05;UNIX.group=502;UNIX.mode=0777;UNIX.owner=502; lista_stocuri.php↵modify=20140915121425;perm=adfrw;size=7350;type=file;unique=803U7FEFC;UNIX.group=502;UNIX.mode=0777;UNIX.owner=502; genNir.php↵modify=20130722092014;perm=flcdmpe;type=dir;unique=803U7FF1B;UNIX.group=502;UNIX.mode=0777;UNIX.owner=502; upload↵modify=20141217105825;perm=flcdmpe;type=cdir;unique=803U7FC9A;UNIX.group=502;UNIX.mode=0777;UNIX.owner=502; .↵modify=20141217100809;perm=flcdmpe;type=dir;unique=803U9FFA0;UNIX.group=502;UNIX.mode=0777;UNIX.owner=502; calendar↵modify=20130314162519;perm=adfrw;size=198;type=file;unique=803U7FEC4;UNIX.group=502;UNIX.mode=0777;UNIX.owner=502; fisa_partener.php↵modify=20140123115929;perm=adfrw;size=6274;type=file;unique=803U7FC6F;UNIX.group=502;UNIX.mode=0777;UNIX.owner=502; genQR.php↵modify=20130402194428;perm=adfrw;size=118565;type=file;unique=803U80001;UNIX.group=502;UNIX.mode=0777;UNIX.owner=502; phpqrcode.php↵modify=20130714045215;perm=adfrw;size=4757;type=file;unique=803U7FF07;UNIX.group=502;UNIX.mode=0777;UNIX.owner=502; receptie_document.php↵modify=20141218181059;perm=adfrw;size=973;type=file;unique=803U81C85;UNIX.group=502;UNIX.mode=0666;UNIX.owner=502; programatorCalendar.php↵modify=20141217124550;perm=adfrw;size=227;type=file;unique=803U81C83;UNIX.group=502;UNIX.mode=0666;UNIX.owner=502; programator.php↵modify=20141028085318;perm=flcdmpe;type=dir;unique=803U7FEB9;UNIX.group=502;UNIX.mode=0777;UNIX.owner=502; web-source↵modify=20130612211636;perm=adfrw;size=1619;type=file;unique=803U7FEBB;UNIX.group=502;UNIX.mode=0777;UNIX.owner=502; receptie.php↵modify=20130718195714;perm=adfrw;size=5659;type=file;unique=803U7FEA8;UNIX.group=502;UNIX.mode=0777;UNIX.owner=502; detalii_produse_qr.php↵modify=20130723172748;perm=adfrw;size=8876;type=file;unique=803U7FEAE;UNIX.group=502;UNIX.mode=0777;UNIX.owner=502; fisa_partener_plati.php↵modify=20130801111044;perm=adfrw;size=20043;type=file;unique=803U7FEAF;UNIX.group=502;UNIX.mode=0777;UNIX.owner=502; genFactura.php↵modify=20150204111007;perm=adfrw;size=3300;type=file;unique=803U7FC79;UNIX.group=502;UNIX.mode=0777;UNIX.owner=502; detalii_comanda.php↵modify=20140109102733;perm=adfrw;size=3596;type=file;unique=803U7FEBF;UNIX.group=502;UNIX.mode=0777;UNIX.owner=502; receptie_produse.php↵modify=20141217105825;perm=flcdmpe;type=pdir;unique=803U7FC9A;UNIX.group=502;UNIX.mode=0777;UNIX.owner=502; ..↵modify=20150107105655;perm=adfrw;size=2344;type=file;unique=803U81C84;UNIX.group=502;UNIX.mode=0666;UNIX.owner=502; calendarFeed.php↵modify=20131014100954;perm=adfrw;size=4431;type=file;unique=803U7FEB7;UNIX.group=502;UNIX.mode=0777;UNIX.owner=502; lista_receptii.php↵modify=20140417040423;perm=flcdmpe;type=dir;unique=803UBFDAB;UNIX.group=502;UNIX.mode=0777;UNIX.owner=502; backup↵modify=20130621084444;perm=adfrw;size=3567;type=file;unique=803U7FEA7;UNIX.group=502;UNIX.mode=0777;UNIX.owner=502; detalii_produse.php↵modify=20130722032417;perm=adfrw;size=36;type=file;unique=803U7FEC0;UNIX.group=502;UNIX.mode=0777;UNIX.owner=502; settings.php↵modify=20131210172629;perm=adfrw;size=3375;type=file;unique=803U7FEB2;UNIX.group=502;UNIX.mode=0777;UNIX.owner=502; lista_parteneri.php↵modify=20150213092626;perm=adfrw;size=9405;type=file;unique=803U7FEFE;UNIX.group=502;UNIX.mode=0766;UNIX.owner=502; genQRComanda.php↵modify=20131016114123;perm=adfrw;size=1640;type=file;unique=803U7FC77;UNIX.group=502;UNIX.mode=0777;UNIX.owner=502; comanda.php↵modify=20140123114356;perm=adfrw;size=5489;type=file;unique=803U7FCFE;UNIX.group=502;UNIX.mode=0777;UNIX.owner=502; detalii_monitorizare.php↵modify=20131210174848;perm=adfrw;size=4133;type=file;unique=803U80BA0;UNIX.group=502;UNIX.mode=0777;UNIX.owner=502; comanda_externa_produse.php↵modify=20140331202043;perm=adfrw;size=456098;type=file;unique=803UE0E34;UNIX.group=502;UNIX.mode=0666;UNIX.owner=502; erp.sql↵modify=20130801122332;perm=adfrw;size=4273;type=file;unique=803U7FC78;UNIX.group=502;UNIX.mode=0777;UNIX.owner=502; comanda_document.php↵modify=20140103102025;perm=adfrw;size=369;type=file;unique=803U8037A;UNIX.group=502;UNIX.mode=0666;UNIX.owner=502; fix.php↵modify=20130524033002;perm=adfrw;size=2302;type=file;unique=803U7FEAC;UNIX.group=502;UNIX.mode=0777;UNIX.owner=502; fisa_partener_contacte.php↵modify=20130825210357;perm=adfrw;size=4944;type=file;unique=803U7FC4C;UNIX.group=502;UNIX.mode=0666;UNIX.owner=502; out.log↵modify=20130516040450;perm=adfrw;size=1226;type=file;unique=803U7FEA2;UNIX.group=502;UNIX.mode=0777;UNIX.owner=502; detalii_partener.php↵modify=20130729002219;perm=adfrw;size=2810;type=file;unique=803U7FEA9;UNIX.group=502;UNIX.mode=0777;UNIX.owner=502; factura.php↵modify=20141017083526;perm=adfrw;size=5530;type=file;unique=803U802F1;UNIX.group=502;UNIX.mode=0766;UNIX.owner=502; genConsum.php↵modify=20140123122105;perm=adfrw;size=15876;type=file;unique=803U7FC74;UNIX.group=502;UNIX.mode=0777;UNIX.owner=502; android.php↵modify=20130515171719;perm=adfrw;size=0;type=file;unique=803U7FC76;UNIX.group=502;UNIX.mode=0777;UNIX.owner=502; blank.php↵modify=20140123114129;perm=adfrw;size=11940;type=file;unique=803U7FEB0;UNIX.group=502;UNIX.mode=0777;UNIX.owner=502; genMonitorizare.php↵modify=20140416154759;perm=adfrw;size=30088;type=file;unique=803U8034A;UNIX.group=502;UNIX.mode=0666;UNIX.owner=502; iesiridepozit↵modify=20140416154757;perm=adfrw;size=731;type=file;unique=803U7FC53;UNIX.group=502;UNIX.mode=0666;UNIX.owner=502; test.php↵modify=20130724050015;perm=adfrw;size=5608;type=file;unique=803U7FEAA;UNIX.group=502;UNIX.mode=0777;UNIX.owner=502; factura_document.php↵"size: "1685"time: 1386689610000type: 0__proto__: Objectlength: 1__proto__: Array[0]path: "/"queuer: Object__proto__: Object

**Comment by rzvngbrl** [comment]
![screen shot 2015-03-24 at 22 04 48](https://cloud.githubusercontent.com/assets/8759592/6811629/d13a5f2e-d271-11e4-9db8-c46607d66780.png)

**Comment by rzvngbrl** [comment]
apparently here I can see more files - I guess there's a parse error ...

I'm running CENTOS 6.5 ( if this makes the difference )

**Comment by Equals182** [comment]
Yep, it is defenitely a parse error. I'm gonna make some changes in couple of minutes, please stay tuned

**Comment by rzvngbrl** [comment]
I'm here :) 




	
Tudor Razvan Gabriel 
C.E.O. 
Mobile: +40722.88.99.85 
Fax: +40372.00.25.15 
Office: +40371.33.22.21 

Str. Ardealului nr. 70, Alfa Center, 
Office: 07, Timisoara, Timis, Romania 

E-Mail: razvan.tudor@fxmedia.ro 
WEB: www.fxmedia.ro 






















----- Original Message -----

**Comment by rzvngbrl** [comment]
I'm here :)

**Comment by Equals182** [comment]
Not sure if it helps. I see new line symbols in log but for some reason splitting `\r\n` don't wanna work for you. Let's try `\n` and see if it helps. Update from `https://github.com/Equals182/Buggy-eqFTP` again, please

**Comment by rzvngbrl** [comment]
Magic :)

![screen shot 2015-03-24 at 22 28 28](https://cloud.githubusercontent.com/assets/8759592/6812078/273a81da-d275-11e4-8817-070af7cadac3.png)

**Comment by rzvngbrl** [comment]
directories works also ! thanks for your quick fix and support ( I will get soon a donation ! :)

Thanks,
R.

**Comment by rzvngbrl** [comment]
I dont understand however why OSX doesn't like \r\n :)

**Comment by Equals182** [comment]
Hope everything else will work fine. Also, you're using beta version now. It have tons of new features and it's still not released so keep an eye on extension manager for v0.7.0 version with even more improvements (you won't see a notification about new version because version number you're using now is 0.7.0)
And thank you In advance for donation!

**Comment by rzvngbrl** [comment]
i'll get back to you if anything else happens, PS: i'm going to set a Romanian language pack, and fix the Italian language also, I just dont know how to send them to you, but I will manage somehow :) ( i'm new with github ) :)

**Comment by Equals182** [comment]
Oh, you need to fork this repository first and then make pull request so I could merge it :)
Not sure how to make pull request, though :D I'm pretty sure Google knows how!

**Comment by rzvngbrl** [comment]
Ok, will be done :)
