### ISSUE TITLE
Won't save login

### ISSUE THREAD

**Issue by braydondavis** [Equals182/eqFTP#125]
Hello,
Anytime I create a new server to connect to, when I restart the Brackets program, the plugin doesn't seem to save any of the servers that I add.

**Comment by Equals182** [comment]
Hi
Please follow [these steps](http://equals182.github.io/eqFTP/#creating-issue) to add log

**Comment by Cedwik** [comment]
Hi, i have the same issue. 
Running on 0.6.2, bracket version is 1.3.0. 

I looked at the console and there's no error displaying, there's a line to say it's done when i save my config. And when i look at the file it's the same that shows the console. 

I think it's more a problem of loading than saving, but i don't find any error concerning eqFTP in the console log. 

Hope it helps !

**Comment by Equals182** [comment]
Hellooooo
First question: do you have **Store passwords safely** option on and if you do, how do you use it?
Second question: how does your path to settings file looks like (check **Folder for Settings** in main eqFTP settings)
Also, please, check if you have `.remotesettings` file in directory that you saw in **Folder for Settings** and if it updates after you click **Save**/**Apply** button in Connection Manager

**Comment by Cedwik** [comment]
Ok the problem is when i have "Store Password Safely" enabled.

I just unchecked it and saved my settings and everything went back the same when i restarted brackets. 

My folder for settings is the default : documents/eqFTP Projects and i have .remotesettings inside wich is updated everytime i save my settings. 
So the problem is with crypto i guess

**Comment by Equals182** [comment]
How do you work with Password option?
To clarify subject, I suggest reading [this](http://equals182.github.io/eqFTP/#main-settings) (Master Password paragraph)
If you think you doing it the way it suppose to be, than it could be a bug.

**Comment by Cedwik** [comment]
I was using an empty password until now, i didn't knew it was used to encrypt so i left it empty. 

Now that is isn't empty anymore it works fine. 
You should prevent users from leaving the password empty then 

Thanks for the help !

**Comment by Equals182** [comment]
Alright, will work on it.
Hope you'll enjoy working with eqFTP.
