### ISSUE TITLE
since last updates no upload possible

### ISSUE THREAD

**Issue by HyperKat** [Equals182/eqFTP#128]
Hello since the last updates eqftp don't upload the files  aftzer saving, also the uplod button dosen't work...

on startup eqftp password question opening more than one time sometimes

**Comment by Equals182** [comment]
Hi!
What last update you talking about? What version do you use?

**Comment by HyperKat** [comment]
ok all done, after the third try deinstall/install it works fine 
my version 0.7.0
thank you

**Comment by Equals182** [comment]
Well, no problem then! Have fun!
