### ISSUE TITLE
v.70 can't open eqFTP

### ISSUE THREAD

**Issue by nickfmc** [Equals182/eqFTP#129]
After installing the latest version on .70 I click on the eqFTP icon and it just throws an error. I have tried installing multiple times.
index.html:1 Uncaught SyntaxError: Unexpected token u

**Comment by Equals182** [comment]
Can you please post full log?

**Comment by nickfmc** [comment]
This is all that is triggered 1 for every time I hit the button, do you want me to do a print and save as a PDF for you?
![capture](https://cloud.githubusercontent.com/assets/8106386/7481345/1dc0cb44-f324-11e4-99b7-7b212715fc30.PNG)

**Comment by Equals182** [comment]
Save as BMP and then convert it to DJVU please. Also host it on facebook.
Try clean re-install or removing other extensions. There's nothing in my extension that executes in index.html on line 1.

**Comment by nickfmc** [comment]
well I'm not sure how or why I would host this on FB, here is a .djvu file does that work? http://www.anyfile.net/An7mKHtx3my/
I'm sure that it may be a conflict with another extension however, everything seams to work until I try to launch eqFTP and your current version works without an issue.

**Comment by Equals182** [comment]
lol, man, I was just kidding. I'm really sorry about that.

Serious one: try to delete eqFTP entirely, restart node (Debug->Restart Node), restart Brackets and install again from this repo and restart everything again afterwards.
I'm reeeeeeally not sure what's going on, and you're the first luck guy with this problem.

There was a plenty of weird issues that resolve themselves somehow, like only one line of code was executed (no matter what line was after or before) so it may be one of those.

If there'll be no luck, I will add some `console.log` lines for you so we could debug this stuff. But I'm 99% sure it's just another case of super-weird-ghost-bugs-of-ridiculousness

**Comment by nickfmc** [comment]
I was wondering but I'm dying to have a good brackets FTP I'll try anything! thought maybe .djvu was a Russian thing ;)  I tried what you suggested without luck. I also removed all of my plugins from Brackets so it had nothing at all. Here is the log with nothing but eq installed if that helps . 
![capture](https://cloud.githubusercontent.com/assets/8106386/7483246/2a90b61e-f332-11e4-8f51-5e8bca4dbb67.PNG)

**Comment by Equals182** [comment]
I'm sorry, man
I see one deprecated thing but it shouldn't affect that hard on work. 
I'll fix it in about 8 hours, when I'll be on PC (it's kinda late here already)
I'll also add logs and we'll see what's going on. 

We'll fix it someday, no doubt. And you will have this thing working! 
For now.. If it's urgent - please use 062. 

I'll comment here in 8-9 hours.

**Comment by Equals182** [comment]
Also, what version of brackets do you use? 1.3?

**Comment by nickfmc** [comment]
Solved this by closing brackets and removing the C:\Users\Nick\Documents\eqFTP Projects\.remotesettings and relaunching brackets!

**Comment by Equals182** [comment]
Awesome! 
I hope it'll work like fine for you
Feel free to report bugs,  I won't be a jerk, I promise :D
Have fun!
