### ISSUE TITLE
SFTP transferring very slow

### ISSUE THREAD

**Issue by onetrev** [Equals182/eqFTP#130]
I'm using v0.7.0 with latest Brackets (1.3) and finding SFTP file transferring is slow, very slow. Like, go grab a coffee slow.

From my testing I'd say it probably averages 8-12 seconds each time I upload a file. Major bummer as with regular FTP it's nearly instant. And on the same server with a FileZilla SFTP, the handshake takes < 1 second, and then the file same 10kb file transfers nearly instantly too. Anything that can be done would be awesome. Thanks!

**Comment by Equals182** [comment]
Hi!

Not sure if I can do anything here, I'm not a creator of node-scp2 or ssh2, I'm just using it in project, giving those functions local and remote pathes and thats it. 
The process itself on eqFTP side (my own code) isn't very different from FTP version, it just uses different lib. Sadly, it IS slower than FTP. In my case it's about 2-3 seconds per upload. 

Can you please look at console ([with debug mode on](http://equals182.github.io/eqFTP/#creating-issue)) and tell me if it connects every time you upload file or it uses "noop"-ish command?

**Comment by onetrev** [comment]
Not 100% sure what I'm looking for in the noop-ish commands, sorry. I looked with debug mode activated.

But yes it definitely connects and disconnects every time it syncs / uploads a file. This shows in the console log, as well with the pop up box in Brackets.

**Comment by Equals182** [comment]
What value do you have in Connection's settings, Advanced tab, Keep alive interval setting?

**Comment by onetrev** [comment]
Default value, 10.

**Comment by Equals182** [comment]
Hmm.. and there's no any "cd ." commands or anything like this? Can you screenshot it for me?

**Comment by onetrev** [comment]
Can do. The entire transfer doesn't fit on one screen with debug mode on. It would probably be more like 3 1080p screens. Here is the end of it. Let me know if you need more.

![eqftp-ss1](https://cloud.githubusercontent.com/assets/597601/7501302/e663bf98-f3e7-11e4-9dec-2325a7107efe.png)

**Comment by Equals182** [comment]
Can you please update from `https://github.com/Equals182/Buggy-eqFTP` and do same exact thing? You should be able to see log line `IS THIS GOING THROUGH`, I need a screenshot/copypaste of this part for now.

**Comment by onetrev** [comment]
Updated eqFTP (it just tells you that you are overwriting installing right? Which I then did)... 

And negative. I do not have that line in my log files. Sorry.

**Comment by Equals182** [comment]
It is possible if you didn't restart node
and yeah, you should overwrite it
To restart node click Debug->Restart node. Also, it's better to restart Brackets after update.
Please, try again. In console window press Ctrl+F and search for `IS THIS GOING THROUGH`, it should be there after any action (even just connection)

**Comment by onetrev** [comment]
Got it. See attached, hope that helps...

![eqftp-ss2](https://cloud.githubusercontent.com/assets/597601/7502605/fe863dee-f3f1-11e4-96da-4d9b8b98a940.png)

**Comment by Equals182** [comment]
I saw your screenshot but I still can't say the reason why keep alive not working for you. I will add some new log lines tomorrow and we will test it a couple (or 10 couples) more times, okay?

Just for your information, keep alive setting will send empty or simple commands to your server making it think you're wokring and keeping connection opened, so there'll be no handshakes, authorizations and other just-opened-connection-stuff. This should help you, I guess.

**Comment by nickfmc** [comment]
I see the same log as @onetrev , where as my keep alive doesn't seam to work.

**Comment by onetrev** [comment]
Some interesting news on this. Good and bad. First the good. I discovered a way to keep the connection open. If I directly select the server for my project in the eqFTP menu, then it stays connected while it syncs. What I was doing before was just loading up and allowing sync option to automatically connect and upload. Hope that makes sense.

The bad news... It's still slow. VERY slow. Did some testing and timing and got as high as 20 seconds, even after it was already connected.

One thing I should note, I don't think it would matter, but I don't have an RSA key setup for the server I'm testing with.

**Comment by Equals182** [comment]
Damn! I forgot that this is how it supposed to work. I'm talking about keep alive. It should only work when you establish connection by choosing it in drop-down list. Sorry about that.
As for speed, it doesn't sound good :( not sure what I can do about it. I'll try to figure it out.

**Comment by Equals182** [comment]
Have you tried **brackets-sftp-upload**? What your feelings about it's speed compared to eqFTP? Maybe I did something wrong if it works faster.

**Comment by nickfmc** [comment]
I used it with an sftp site and don't remember having any issues with speed, I think I would have noticed if it was as slow as eq

**Comment by Equals182** [comment]
So, you have speed issues as well? :(

**Comment by onetrev** [comment]
I just tried that extension as well. Not sure if it's good or bad news, but upload was basically instant.

**Comment by nickfmc** [comment]
When using SFTP ya takes 5 to 20 seconds for my files to transfer usually closer to the high end

**Comment by Equals182** [comment]
That's bad
![Imsad](https://pbs.twimg.com/media/B4_7d8xCUAAKAZJ.jpg)

**Comment by Equals182** [comment]
Guys, I need some speed tests. I just tried to upload files via SFTP (not an extension, but protocol) and it worked in like 2.3sec. Can you please update from `https://github.com/Equals182/eqFTP`, turn off debug mode, restart Brackets and upload just one file and screenshot me your console output?

**Comment by onetrev** [comment]
Updated. Restarted node and Brackets a couple of times. Spun around my chair 3 times. Here is what happened... about an 18 second upload according to the console output I think.

![untitled-1](https://cloud.githubusercontent.com/assets/597601/7519341/43393772-f495-11e4-87e5-6feeecfe4c93.png)

**Comment by Equals182** [comment]
Damn, I can't even test it by myself! Look at this!
![](https://pp.vk.me/c624118/v624118643/3405a/tOoRSBLRAhk.jpg)

**Comment by onetrev** [comment]
Weird. You are testing with SFTP setting though right, not just regular FTP connection? Just makin' sure!

**Comment by Equals182** [comment]
yep, SFTP
![](https://pp.vk.me/c624724/v624724643/3277f/9mOW1P8AYK8.jpg)

**Comment by Equals182** [comment]
I will look through sftp-upload's code and try to figure out where's the difference.
Maybe I will even make time tests in it just to make sure where exactly my ext. is slower.

**Comment by onetrev** [comment]
Sounds great! Thanks for working through this will me. Looking forward to the fix. For now I will just take coffee breaks on every upload, no worries! ;)

**Comment by Equals182** [comment]
Hey man! Sorry for not answering you soo long. Can you provide me a test account for your server?
I know, that can sound suspicious. I only need ~1 mb space on it, just to debug uploading.
My tests shows pretty good performance :(

**Comment by onetrev** [comment]
No worries! I can set this up for, but not sure we need to worry about it if no one else is reporting it, as I've switched editors.... I'm using Atom now! Bracket is just too, how should I say, "Adobe-ish" for me. Haha!

**Comment by Equals182** [comment]
Oh.. Well, I can try to debug it anyway, if it's not a problem for you to set up an account for me :) Send me info on equals182@gmail.com if you do it, please :)

**Comment by Equals182** [comment]
### Hello there!

I know this issue been there for a pretty long time, but I have some good news here!
We just released eqFTP v**1.0.0-beta.0** (v1-b for short I guess) and we're completely discontinuing support of all previous versions of this plugin.
New version works great on Brackets 1.8 and it should be good on lower versions too.

So yeah, we're closing and locking this issue forever and looking forward for you to try out our new version of eqFTP.
I'm sorry if I somehow disturbed you, or you lost your interest in eqFTP or Brackets in general, we're not going to make any noise here again.

If you have any questions, please contact me via email (you can find it in [my profile](https://github.com/Equals182)) or [Telegram app](http://t.me/equals182)

Thank you for understanding 😊
