### ISSUE TITLE
95% CPU Usage

### ISSUE THREAD

**Issue by Neilq5** [Equals182/eqFTP#132]
Since adding this plug, the CPU Usage for Brackets has gone crazy.  It's definitely caused by this extension has removing it has taken away the problem.
I've had this rMBP for over a year and today is the first time I've heard it having to use it's fan.

I've looked at the Activity Monitor and it's saying "Brackets Helper" is using 95% of the CPU.

**Comment by Equals182** [comment]
Hi
Can't test it on Mac and have absolutely no idea why this is happening. There was memory leaks loooong time ago, but I'm using it on win and ubuntu now and it's working fine - 0% CPU and ~300mb of memory for Brackets.

Can you try installing clean version of Brackets and latest version of eqFTP (using https://github.com/Equals182/eqFTP as URL for installation)?

**Comment by Neilq5** [comment]
Thanks for the reply, I've reinstalled Brackets, eqFTP and removed all other extensions for now, I'll let you know how it goes.

**Comment by Neilq5** [comment]
Hey Equals, I was still getting the problem, so I removed all other extensions and the problem has seemingly disappeared, which is strange as they work fine without eqFTP installed.  I don't know if it's possible for extensions to 'clash' in some way and cause the problem.  I'll reinstall them at a later time and see if the problem reoccurs.  But for now all is good

**Comment by Equals182** [comment]
Feel free to reopen this issue if you find out anything. Hope everything fill work fine for you! Have fun :)

**Comment by Neilq5** [comment]
Hey Equals.  Just posting a small update I think you might want to look in to.
I've been very careful about what I've been doing in Brackets over the past couple of days so I could be sure, if the issue did happen again, I'd know exactly what caused it.
The issue did happen again about an hour ago, it seems to occur right after receiving the following error

node-error 10:55:40 PM] [eqFTP-ftpDomain]: Can't get in directory: /home/public_html/. Trying to get in /NodeDebugUtils.js:114 handleLogEvent/utils/EventDispatcher.js:222 trigger/utils/EventDispatcher.js:260 triggerWithArray/utils/NodeConnection.js:479 NodeConnection._receive

I was entering my setup info wrong with one of my sites and this memory leak seems to occur right after this is triggered.  I'm not sure if this is just on my machine but as soon as the information is fixed, or Brackets is restarted without attempting to connect to the wrong site, CPU Usage returns to normal.

**Comment by Equals182** [comment]
Hi!
Can you please provide full log? I'll try to find out what's going on, but unfortunately I don't have much time now. If it's working fine

**Comment by Neilq5** [comment]
Hey Equals, I'll post the full log as soon as I get home.  It's not urgent it, I didn't intend to reopen the issue, just clicked the wrong button

**Comment by Equals182** [comment]
Reopening is okay, it's a bug anyway and it's need to be fixed :)

**Comment by Equals182** [comment]
I tried setting wrong `remote path` but there's no memory leak for me - just spinner doesn't disappear. There's no endless loops and stuff, so I'm not sure where the leak can possibly be.

**Comment by Neilq5** [comment]
My bad I never got back to this, the problem seems to be exclusive so GoDaddy, the workaround I've found is to just add the files to the paused queue and upload less frequently so it doesn't take a hissy fit.  Seems the problem is more with how they handle the FTP connection rather than this extension.  Thanks for the help!
