### ISSUE TITLE
Problem with "-" char when creating files

### ISSUE THREAD

**Issue by dennyschwender** [Equals182/eqFTP#133]
Creating a new file with the "-" char, the system create it without the "-" char.
I've done some step to let you see what is appening, on the first image you see the name I want, on the second image you see the file created.

![step1](https://cloud.githubusercontent.com/assets/5999774/7567417/333d8542-f7fd-11e4-886a-81ca9346bbcb.png)
![step2](https://cloud.githubusercontent.com/assets/5999774/7567416/333d2cfa-f7fd-11e4-9f39-93dc845078b1.png)

**Comment by Equals182** [comment]
Yes, unfortunately it is a bug, will work on it.
