### ISSUE TITLE
Can't change a connection

### ISSUE THREAD

**Issue by Wikunia** [Equals182/eqFTP#134]
Hi Alex,

I've reinstalled your extension cause I had some problems.
Now I've recognized, that I can't change a connection.

This appears in the log:
`Uncaught TypeError: Cannot call method 'addConnections' of undefined` in main.js lines: 1374 and 1346

**Comment by Equals182** [comment]
Hey man!
I'm sorry for late answer
Can you please update from `https://github.com/Equals182/eqFTP` again check if it works? I'm pretty sure I didn't change this part of code too much since 0.6.2, it could be tmp bug.
If nothing will change, I will add log line for you to debug, k?

**Comment by Wikunia** [comment]
Still there :/

```
Uncaught TypeError: Cannot call method 'updateSettings' of undefined main.js:2525
Uncaught TypeError: Cannot call method 'addConnections' of undefined main.js:1083
```

**Comment by Equals182** [comment]
Probably compatibility issues with https://github.com/dschaffe/brackets-xunit
No errors for now. Reopen if you'll notice some
