### ISSUE TITLE
Can't connect to server "uncaught exception at top level, exiting. undefined"

### ISSUE THREAD

**Issue by Wikunia** [Equals182/eqFTP#135]
I am not able to connect to my server :/

![2015-05-13-194149_1897x296_scrot](https://cloud.githubusercontent.com/assets/4931746/7616887/1dca379e-f9a8-11e4-84d9-bc3e367b184d.png)

version: latest (from url)

**Comment by Equals182** [comment]
Compatibility issues with https://github.com/dschaffe/brackets-xunit
