### ISSUE TITLE
Can't connect to FTP account 

### ISSUE THREAD

**Issue by SheepDomination** [Equals182/eqFTP#136]
I've setup a connection via eqFTP, ip address (example: ftp.111.111.111.111) etc regardless if the connection icon is in disconnected or connection mode, I can't connect to an ftp account ?

**Comment by Equals182** [comment]
Hi! 
Please provide some logs. [Here's](http://equals182.github.io/eqFTP/#creating-issue) how you can do it

**Comment by SheepDomination** [comment]
eqFTP - 0.6.2
Brackets - Release 1.3 build 1.3.0-16022

Attempting to connect to an FTP server was all I wanted to do.

 [node-error 2:02:42 AM] [eqFTP-ftpDomain]: {"code":"ENOTFOUND","errno":"ENOTFOUND","syscall":"getaddrinfo"}ErrorNotification.js:125 window.console.errorNodeDebugUtils.js:114 handleLogEvent/utils/EventDispatcher.js:222 trigger/utils/EventDispatcher.js:260 triggerWithArray/utils/NodeConnection.js:479 NodeConnection._receive
NodeDebugUtils.js:117 [node-log 2:02:42 AM] [eqFTP-ftpDomain]: Disconnecting...

**Comment by Equals182** [comment]
Does it happens only with IP addresses or with any host you tried?

**Comment by SheepDomination** [comment]
I only use IP address with ports !

**Comment by Equals182** [comment]
I'm sorry for late response, I had no time at all. Can you please provide exact IP address you're using in `Server` field? Is it `111.111.111.111` or something different? I just noticed you wrote `ftp.111.111.111.111` which is wrong format.

**Comment by SheepDomination** [comment]
It works, except it doesn't save my connections ?

**Comment by Equals182** [comment]
What do you mean? You click save, restart brackets and your connections lost? Right?

**Comment by SheepDomination** [comment]
Did you upgrade eqFTP recently, when I click the icon, nothing loads ?

**Comment by Equals182** [comment]
If you didn't update it yourself, then nothing should be changed for you. Also, no, nothing special. On the bottom of screen do you see `eqFTP Queue`? Is it red?

**Comment by SheepDomination** [comment]
I had to restart again, now things are working good.  How do I save the file I'm working on using eqFTP to the ftp directory ?

**Comment by Equals182** [comment]
Wait a second. There's already 3 different problems you already stated.
Let's discuss first one:
> It works, except it doesn't save my connections ?

Are you able to save your connections now?

**Comment by SheepDomination** [comment]
Yes, Im able to save my connections !

**Comment by Equals182** [comment]
Ok, good. Moving to last one
>  How do I save the file I'm working on using eqFTP to the ftp directory ?

How eqFTP works. You creating FTP Connection. You just double click file in remote file tree, edit it, save and upload. To upload file you can right click it in project file tree, and click upload.
If you set up connection, but there's nothing yet to download - open local project, that related to your connection, create file here and upload it. File structure will be saved.

It's not easy to describe whole concept of eqFTP in couple of sentences, so I would like to recommend you reading some kind of manual [here](http://equals182.github.io/eqFTP/)

**Comment by Equals182** [comment]
Also, this is how eqFTP links to local projects
**Local project** is just a folder on you PC, that keeps all your project's files. It's a *project* because Brackets can open folders as projects.
So eqFTP using this system. You can link your project to Connection by setting **local path** in Connection's settings. You can leave this setting blank and let eqFTP create local project in default folder. It will use Connection's name and project name. You can see what is your default folder in **Folder for Projects** main setting.
eqFTP will save files in project's folder and only files within this project can be uploaded to remote server keeping folder structure same on both sides.
