### ISSUE TITLE
Can't set protocol to SFTP - dropdown does not work?

### ISSUE THREAD

**Issue by KarstenPaech** [Equals182/eqFTP#137]
Cannot choose anything but "FTP" in Connection Managers Protocol-Dropdown. Here is my Brackets Status:
{
    "uuid": "eabcc886-5996-415f-b397-83e04b2d47a3",
    "snapshotTime": 1432132447137,
    "os": "win",
    "userAgent": "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Brackets/1.3.0.0 Chrome/39.0.2171.36 Safari/537.36",
    "osLanguage": "de-DE",
    "bracketsLanguage": "de-DE",
    "bracketsVersion": "1.3.0-16022",
    "installedExtensions": [
        {
            "name": "delkos",
            "version": "0.0.3"
        },
        {
            "name": "stripper-theme",
            "version": "0.1.0"
        },
        {
            "name": "beldar.auto-brackets",
            "version": "0.0.9"
        },
        {
            "name": "camden.wordcount",
            "version": "1.0.0"
        },
        {
            "name": "crabcode.outline",
            "version": "0.1.9"
        },
        {
            "name": "gbratsos.zurb-foundation",
            "version": "1.0.2"
        },
        {
            "name": "ivogabe.icons",
            "version": "1.4.0"
        },
        {
            "name": "jdiehl.less-autocompile",
            "version": "1.1.8"
        },
        {
            "name": "lesshints",
            "version": "1.1.0"
        },
        {
            "name": "mirorauhala.bootstrap-skeleton",
            "version": "0.1.0"
        },
        {
            "name": "pflynn.brackets.commands.guide",
            "version": "1.0.5"
        },
        {
            "name": "themesforbrackets",
            "version": "2.0.12"
        },
        {
            "name": "toendering.advanced_new_file",
            "version": "0.2.0"
        },
        {
            "name": "twig",
            "version": "1.0.0"
        },
        {
            "name": "brackets-backup",
            "version": "1.0.4"
        },
        {
            "name": "brackets-minifier",
            "version": "1.1.1"
        },
        {
            "name": "insya.newdocument",
            "version": "0.0.4"
        },
        {
            "name": "brackets-php-syntax-hint",
            "version": "1.1.3"
        },
        {
            "name": "chrisgriffith.jqmbrackets",
            "version": "0.1.0"
        },
        {
            "name": "brackets-ckeditor",
            "version": "1.0.3"
        },
        {
            "name": "brackets-integrated-development",
            "version": "0.5.59"
        },
        {
            "name": "camden.jshint",
            "version": "2.2.11"
        },
        {
            "name": "websiteduck.wdminimap",
            "version": "2.2.3"
        },
        {
            "name": "brackets-simple-js-code-hints",
            "version": "1.0.1"
        },
        {
            "name": "brackets-various-improvements",
            "version": "2.2.1"
        },
        {
            "name": "timburgess.pagesuck",
            "version": "1.0.2"
        },
        {
            "name": "mikailcolak.brackets-color-picker",
            "version": "0.1.3"
        },
        {
            "name": "dnbard.extensions-rating",
            "version": "0.7.0"
        },
        {
            "name": "dnbard.lorem-pixel",
            "version": "0.1.5"
        },
        {
            "name": "dnbard.documents-toolbar",
            "version": "0.5.14"
        },
        {
            "name": "dnbard.projects",
            "version": "0.1.7"
        },
        {
            "name": "brackets-beautify",
            "version": "1.1.6"
        },
        {
            "name": "jeffbooher.new-project",
            "version": "0.4.97"
        },
        {
            "name": "equals182.eqftp",
            "version": "0.6.2"
        },
        {
            "name": "le717.html-skeleton",
            "version": "1.4.2"
        },
        {
            "name": "response-for-brackets",
            "version": "0.1.0"
        },
        {
            "name": "mikaeljorhult.brackets-todo",
            "version": "0.8.1"
        },
        {
            "name": "jrowny.brackets.snippets",
            "version": "1.1.0"
        },
        {
            "name": "wthreec_schools",
            "version": "0.2.6"
        },
        {
            "name": "brackets-emmet",
            "version": "1.2.2"
        },
        {
            "name": "adobe.brackets.extract",
            "version": "0.7.2-1724-release"
        }
    ]
}
Hope this helps.

Karsten

**Comment by Equals182** [comment]
Hi Karsten!
You're using version 0.6.2 which doesn't have SFTP support yet, but there is version 0.7.0 in beta testing right now which have SFTP support. You can [install it](http://equals182.github.io/eqFTP/#installing) (use beta version guide), but please keep in mind that if you update this way, you will not be able to see new version as **new** in extension manager when it comes out so you'll need to keep an eye on eqFTP in ext manager and check it from time to time, if you want newest version.
I can't tell you when it'll be released (it's in development for half of year already) but it may happen some day and you probably don't want to miss latest update with bugfixes and ~~hookers~~

So yeah! Try beta :3

**Comment by KarstenPaech** [comment]
Sorry,
that I did not see this - now I can connect via SFTP. Thanks.
Maybe you could disable dropdown for versions, that do not offer other protocols than FTP?

Thank you for your great work.

Karsten

**Comment by Equals182** [comment]
I should have done this but now I don't really want to update version just for removing unabled protocols
