### ISSUE TITLE
Can't install or use proper 

### ISSUE THREAD

**Issue by tatof** [Equals182/eqFTP#138]
Hello,

First of all, great plugin! when it works it perfectly fits my needs.

Only think is that eqFTP doesn't always work.
Use your plugin on 3 computer systems and they all have a few problems.

1. Sometimes Brackets just starts without the plugin icon and I have to F5 to reload and hope it will appear.
2. Settings menu text disapears sometimes (have to reinstall to get it back)
3. Brackets keeps crashing with eqFTP installed.
4. Right now i'm trying to reinstall eqFTP but it just keeps loading. (force bracket to quit) and eqFTP will be installed with error.
5. sometimes I can't upload files to the server. need to restart brackets to upload. (think password popup box is brokan at that point)

Got the error log file for the 4th problem with installing. but its more than 9000 row's high.
Maybe this is enough?

In require.js:166
Uncaught Error: Mismatched anonymous define() module: function (require, exports, module) {

Really want to use Brackets cause its awesome but also need an good ftp solution and you guys are that solution! (don't want to go back to notepad++ :/)

Thanks!

**Comment by Equals182** [comment]
Hi!
Please, delete eqFTP entirely, like double check extenstion folder for it and restart Brackets manually. After that *just in case* restart Node (Debug->Restart Node) and F5 Brackets.
This should clean it.
Then please try to install from this url `https://github.com/Equals182/eqFTP`.
This is beta version. Use extension manager and Install from URL on bottom of window.
Right after install, close Brackets and open it again.

It *may* happen, that eqFTP won't load sometimes (eqFTP Queue is red and folder icon isn't clickable), but it's quite rare thing. Restart fixes it.

Please let me know how was the installation process and we'll move to another errors

**Comment by tatof** [comment]
At work it installed just fine, going to try it out! thanks.

At home with the biggest problems, I wil try that out tonight.

**Comment by tatof** [comment]
Oke doesn't work here (at home).
Deleted brackets with youruninstaller and reinstalled brackets.

Removed eqFTP and checked the extentions folder \AppData\Roaming\Brackets.
Trying to install the link but it keeps "loading".. its going for 15 minutes now.

EDIT:
Oke Deleted the brackets folder in "\AppData\Roaming\" and restarted. 
now it works. will test on stability! 

thanks you.

**Comment by tatof** [comment]
sorry for tripple post but.... this new beta version rocks! good job :D

**Comment by Equals182** [comment]
Thank you! Hope everything will work fine for you :+1:
