### ISSUE TITLE
Not able to have two connections with same source

### ISSUE THREAD

**Issue by visnik** [Equals182/eqFTP#141]
I can't seem to have two connections to the same source, for example on my machine I have a project, lets lets say located at /myProject,  I have a ftp server with two separate folders, a Dev and a QA.  I am attempting to set up two connections , both with the source being /myProject and and a destination on my server of  /myProject-Dev and /MyProject-QA.  I am able to set up the Dev connection and it works fine, however when I set up the second connection to the remote QA location, i can connect, See my files on the server,  but I can't upload.  I get the following errors, In the dev tools debug window : "[eqFTP] You're not allowing me to upload files on this server when you're not connected to it."  In the Queue windows it says Can't upload file. 'event if Disconnected' option is off. 

Thanks

**Comment by Equals182** [comment]
Well, yes. 
When you do stuff in your local project, eqFTP searches trough Connections for *local path* or *connection name* that match path of local project and works with the first found Connection. 
So when you set up 2 connections with same *local path* it will only works with one of them. 

For now it's not possible do to such thing. 
I guess you want eqFTP to upload to currently connected server, right?

**Comment by jsmeltzer** [comment]
I've recently started using eqFTP and would love to see this feature as well. It's the only issue I've run into with it so far. Keep up the good work!

**Comment by bestsj** [comment]
I also would love to see this feature! We're working with multiple servers at the same time, and it would be great to be able to upload the locally edited file to all of these servers at the same time just by saving it! :)

**Comment by Equals182** [comment]
It's different. @bestsj want to upload one file to all servers, while @jsmeltzer and @visnik (at least as I understood) want to upload file on currently connected server. I think I can manage both solutions but I'm not sure if it's right approach. I mean everyone want a different feature and mot sure if there's enough people to second those features. Of course I can do some settings stuff that would be set off by default, but it may result in overcomplicated settings window which is not good.

**Comment by visnik** [comment]
HI Equals182, 

I am not sure if I understand, but it seems as though @bestsj is asking for the same feature.  A project in Brackets can have multiple connections, connection A, B, or C.  Does this matter if it is the same remote server pointing to different directories or multiple servers as each connection asked for ip, and destination directory? A connection if abstracted out, the app should just treat it as one more connection.  I think this wold be a great feature as a lot of people work with multiple servers/distribution locations.  I have never built out a brackets plugin, or worked with FTP connections on that level, but I'm willing to help with this feature were I can?

**Comment by Equals182** [comment]
Correct me if I'm wrong.
You would like to see a dialog box popping out when you trying to upload file while current project's path is bounded with more than one Connection, right? And this dialog box should ask you where you want to upload your file (one of Connections or all of them)?

This is cool, it should work, **but**, there is a feature that automatically connect to server and compare local and remote files for differences and I don't know how exactly make it work with proposed system. I see three ways:
1. Make one Connection default. It will compare local file with remote file on default Connection's server.
2. Make a dialog box (this will be annoying af) asking you where it should take remote file
3. Automatically disable this comparing feature if there are more than 1 bounded local project.

I hope you got my point. And this is probably not the only one pitfall that we can face making this feature.

As for helping. You can fork it and try to do yourself, but I'm sure it will be not that easy to understand someone else's code. So you may help me figure out the best way to add this feature without crashing everything that eqFTP have at this point.

**Comment by visnik** [comment]
HI Equals, 

Yes, I think option 1 would probably be the best option, though I think 3 should also be considered an option, as others upload to the remote,  I as a user may not want to automatically sync to there files yet. 

In Aptana, when you have multiple connections and the dialog pops up to choose remote location, there is a check-box to set as default. this causes the checkbox to stop popping up each time you upload a file(s). You can of course reset it in the settings, I think this would be a great feature to emulate.  If it is helpful I'll see if I can grab a series of screenshot and put them up here later today. 

I'll also pull, or fork your code this weekend and and start looking at it to see where and how I can help. 

Thanks,

**Comment by M4TH76** [comment]
Hi Equals,

I would to, love this feature...
For me the best option is something like Dreamweaver, Local / remote folder, with an option to have more than one remote server and selecting their sync options independently. 

Again, for me, projects based settings work better than folder based, I have some folder that overlap each other.

Thanks for your good work!

**Comment by Equals182** [comment]
### Hello there!

I know this issue been there for a pretty long time, but I have some good news here!
We just released eqFTP v**1.0.0-beta.0** (v1-b for short I guess) and we're completely discontinuing support of all previous versions of this plugin.
New version works great on Brackets 1.8 and it should be good on lower versions too.

So yeah, we're closing and locking this issue forever and looking forward for you to try out our new version of eqFTP.
I'm sorry if I somehow disturbed you, or you lost your interest in eqFTP or Brackets in general, we're not going to make any noise here again.

If you have any questions, please contact me via email (you can find it in [my profile](https://github.com/Equals182)) or [Telegram app](http://t.me/equals182)

Thank you for understanding 😊
