### ISSUE TITLE
Feature Request - Copy FTP Connection

### ISSUE THREAD

**Issue by amaust82** [Equals182/eqFTP#143]
I LOVE using Brackets, but it isn't quite practical yet. eqFTP is almost there, but I do a lot of smaller date-driven projects on one server. I touch 10 - 15 a day, opening 2 or 3 new ones each day. As such, re-entering the FTP connection info for EVERY project is a huge time-waster. Any way to copy an existing so I can just update the remote directory? 

Ideally, I would love an FTP template without a remote directory, then when I make a new connection I can select that and I just have to drop in a name and remote directory.

**Comment by Equals182** [comment]
Please update from `https://github.com/Equals182/eqFTP`
You'll should be able to see new `copy` icon next to delete icon in connections list. It should be simple to figure out how it works.
Thank you for feature request, take it :)
