### ISSUE TITLE
Detachable Window

### ISSUE THREAD

**Issue by f34rl3ss** [Equals182/eqFTP#145]
Hi,

first of all, i love your plugin.
Tested all the other bracket ftp plugins and this one is the best of them.

There is only one feature i am missing so far: Would it be possible to make the eqFTP window detachable from the main brackets window?
I have 3 monitors and i like to make these ftp windows seperate and move them left of the main window on the left monitor.
That way they can stay open all the time and do not preserve space in the main window.

Regardless if this is possible or not, thanks for this great plugin! :)

Regards

**Comment by Equals182** [comment]
Hi!

Thank you for kind words :)
I'm afraid, this feature you asking for is not possible to realize. I'm currently asking Brackets' devs about it. I'll post final conclusion here when they answer.

Hope you have good time using eqFTP :)

**Comment by f34rl3ss** [comment]
You are welcome :)

I thought so, but thank you for asking the Brackets' devs about it :)

It's not that big of a deal as in other code editors because brackets has that local folder view and eqFTP uploads automatically on saving, but it would be a nice to have thing to let eqFTP stay open
freed from the main program window in case i need another file from the server.

Onother idea would be, if it cannot be detached from the main window, to integrate it in the folder view if connected to a ftp. maybe with a button or tab to switch between local folders and eqFTP folders.

**Comment by Equals182** [comment]
That request was in #110 :)

**Comment by f34rl3ss** [comment]
Haha, didn't see that request.
Thumbs up for the same idea :)

**Comment by Equals182** [comment]
Also, devs didn't answered me. I think they just like to ignore me on slack and github.

**Comment by f34rl3ss** [comment]
Bad devs ;(
It came to my attention that the dev-console window is detached from the main window, and can also be moved outside of the main window.
So it might not be completly impossible to do someting like that ^^

**Comment by Equals182** [comment]
### Hello there!

I know this issue been there for a pretty long time, but I have some good news here!
We just released eqFTP v**1.0.0-beta.0** (v1-b for short I guess) and we're completely discontinuing support of all previous versions of this plugin.
New version works great on Brackets 1.8 and it should be good on lower versions too.

So yeah, we're closing and locking this issue forever and looking forward for you to try out our new version of eqFTP.
I'm sorry if I somehow disturbed you, or you lost your interest in eqFTP or Brackets in general, we're not going to make any noise here again.

If you have any questions, please contact me via email (you can find it in [my profile](https://github.com/Equals182)) or [Telegram app](http://t.me/equals182)

Thank you for understanding 😊
