### ISSUE TITLE
Password field freezing Brackets on saving without connection to ftp (v0.7.0)

### ISSUE THREAD

**Issue by f34rl3ss** [Equals182/eqFTP#148]
I had the issue in 0.6.2 that when opening brackets, when not connected to a ftp,
on saving a file he asked for the eqFTP password, but did not connect to the server and upload automatically.
Just wanted to check if the problem is gone in 0.7.0.
Now it is even worse. The eqFTP password box comes up and then freezes brackets completly. No cancel/ok possible. The Dev-Console cannot be openend.
Brackets can only be closed by the task manager then.

Edit:
Opened the Dev-Console before doing it again:
```
 [node-log 1:34:37 PM] [eqFTP-ftpDomain] Loaded
/C:/Users/xxx/AppData/Roaming/Brackets/extensions/user/equals182.eqftp/main.js:1633 [eqFTP] Loaded (v0.7.0)
main.js:3295 13:34:47.300 [eqFTP-uploadonsave] documentSaved triggered
main.js:3297 [eqFTP-uploadonsave] Checking if file is within project F:/Files/jic/wp-content/themes/jic/footer.php
main.js:3299 [eqFTP-uploadonsave] Yes it is
main.js:3301 [eqFTP-uploadonsave] Getting connection ID by path
NodeDebugUtils.js:117 [node-log 1:34:54 PM] [eqFTP-test] Updating settings. Expecting debug on { debug: true,
  defaultLocal: 'F:/Important Files/Web-Project-Files/eqFTP Projects' }
NodeDebugUtils.js:117 [node-log 1:34:54 PM] [eqFTP-ftpDomain]: Adding connections.
NodeDebugUtils.js:117 [node-log 1:34:54 PM] [eqFTP-ftpDomain]: 136: Checking connection ID: 0
NodeDebugUtils.js:117 [node-log 1:34:54 PM] [eqFTP-ftpDomain]: 147: Getting existent connection by ID, result: undefined
NodeDebugUtils.js:117 [node-log 1:34:54 PM] [eqFTP-ftpDomain]: 173: Adding new connection: "Webserver"
```
Looks normal. But the password box is still open and cannot be closed.

**Comment by Equals182** [comment]
Something new here. Not sure what causes freezzing, since it's just regular dialog box . Does it freeze when you enter password or on first appearance? 
Try opening dev-console before doing stuff with eqFTP and then check what's going on

**Comment by f34rl3ss** [comment]
Added dev-console output in my first post.
Not sure if freezing is the right word. The dialog box is reacting (you can see the animation on button pressing), but the dialog box does not close after anymore (no difference if entering a password or not entering a password).
Because the main window of backets is "grayed-out" when the password box is active, brackets cannot be closed by pressing X.
This only happens if the password box is triggered with a save file event.
When i open eqFTP by pressing the plugin symbol, the password box behaves as it should.

**Comment by Equals182** [comment]
Saw your logs. Weird. May be I fucked up and missed this bug. I'm gonna debug it myself today/tomorrow. You can trun off master password for now, until it fixed.

**Comment by jkalousek** [comment]
I have same problem, after saving file without previously open eqFTP, it ask me for master password and after confirm, it just sits there. Program still running in background fine but there is no way to close pop-up window.

**Comment by Equals182** [comment]
This may happen since I've made some changes in this window's behaviour. I'll fix it asap, sorry :(

**Comment by Equals182** [comment]
Okay, fixed. Uploading now, update from `https://github.com/Equals182/eqFTP` in 5-10 minutes
