### ISSUE TITLE
Downloads incomplete files from server

### ISSUE THREAD

**Issue by shivanandsharma** [Equals182/eqFTP#151]
Brackets is my default code-editor. I'm connected to my FTP server and this has happened twice: When opening files from the ftp connection, sometimes if the file is large (mine was 77 kb-ish) but it once happened on a 48kb file also. The file contents were only partial and the file was truncated at the end. I lost work but luckily I make backups of every version of the files on the server.

Is there a way I can see what's happening in the background? Debug super powers mode?

**Comment by Equals182** [comment]
77kb is really small file. You can turn on debug mode in settings, just put checkmark and restart brackets

**Comment by Equals182** [comment]
More information about turning debug mode [here](http://equals182.github.io/eqFTP/#creating-issue)

**Comment by Equals182** [comment]
### Hello there!

I know this issue been there for a pretty long time, but I have some good news here!
We just released eqFTP v**1.0.0-beta.0** (v1-b for short I guess) and we're completely discontinuing support of all previous versions of this plugin.
New version works great on Brackets 1.8 and it should be good on lower versions too.

So yeah, we're closing and locking this issue forever and looking forward for you to try out our new version of eqFTP.
I'm sorry if I somehow disturbed you, or you lost your interest in eqFTP or Brackets in general, we're not going to make any noise here again.

If you have any questions, please contact me via email (you can find it in [my profile](https://github.com/Equals182)) or [Telegram app](http://t.me/equals182)

Thank you for understanding 😊
