### ISSUE TITLE
[RU]Проблема с паролем

### ISSUE THREAD

**Issue by MutableR** [Equals182/eqFTP#155]
Случилось так что я потеряла пароль и не могу пользоваться eqFTP. Существуют ли какие нибудь способы решить мою проблему. Тут несомненно моя вина, но я хотела бы и дальше пользоваться им.

**Comment by Equals182** [comment]
К сожалению, нет. Восстановить мастер-пароль никак нельзя - он нигде не хранится. Вы можете пользоваться eqFTP дальше, но потеряете все настройки FTP соединений. Просто отмените диалоговое окно пароля, когда eqFTP попросит вас, зайдите в настройки, создайте соединение и сохраните - изменения перезапишут файл настроек

**Comment by MutableR** [comment]
тогда я могу подключиться к тому же FTP серверу снова?

**Comment by Equals182** [comment]
да, конечно. просто придется перенастроить подключение

**Comment by MutableR** [comment]
спасибо за ваш ответ

**Comment by Equals182** [comment]
Не за что, обращайтесь. Надеюсь у вас не возникнет проблем с использованием eqFTP в будущем)
