### ISSUE TITLE
Adding in Drag and Drop Support

### ISSUE THREAD

**Issue by mjbrancato** [Equals182/eqFTP#156]
This plugin is awesome!!

I was wondering if you could add in drag and drop support to catch the files and upload them? I came across this API to do that: http://brackets.io/docs/current/modules/utils/DragAndDrop.html

Also, I don't know if it's possible because the way Brackets is written, but it would be cool to have the eqFTP box stay open when loosing focus or the ability to snap it in a sidebar.

**Comment by Equals182** [comment]
This feature request will be really hard to implement

**Comment by Equals182** [comment]
### Hello there!

I know this issue been there for a pretty long time, but I have some good news here!
We just released eqFTP v**1.0.0-beta.0** (v1-b for short I guess) and we're completely discontinuing support of all previous versions of this plugin.
New version works great on Brackets 1.8 and it should be good on lower versions too.

So yeah, we're closing and locking this issue forever and looking forward for you to try out our new version of eqFTP.
I'm sorry if I somehow disturbed you, or you lost your interest in eqFTP or Brackets in general, we're not going to make any noise here again.

If you have any questions, please contact me via email (you can find it in [my profile](https://github.com/Equals182)) or [Telegram app](http://t.me/equals182)

Thank you for understanding 😊
