### ISSUE TITLE
Saved FTP connections not saved

### ISSUE THREAD

**Issue by Rann1** [Equals182/eqFTP#161]
When I add websites to the saved FTP Connections, it doesn't seem to safe always.

I Create a new connection, fill in the info, click apply, click close.

When I click on the ' Select remote server to connect"  dropdown, it will not appear in the list.

Sometimes when I add it three times, it does appear, also on restart of Brackets the list is empty. If I still have a working file downloaded from a server in my working files list, and save and upload it, the list suddenly fills up again..

**Comment by Equals182** [comment]
Can you please provide some logs?
It should work with just 1 click of Save button.
So to test it:
1. Open Brackets
2. Press F12 and click Console tab
2.1. Clear console
3. Click eqFTP icon
4. Copy Console output here and clear Console
5. Open eqFTP settings
6. Fill credentials for test connection and click Save
7. Copy Console output here

That should be enough. Thanks for patience.

**Comment by Rann1** [comment]
Can't reproduce at the moment, had it on my home, work, and my colleague had it aswell during the first day of usage. Not sure what the problem is/was.

**Comment by Equals182** [comment]
### Hello there!

I know this issue been there for a pretty long time, but I have some good news here!
We just released eqFTP v**1.0.0-beta.0** (v1-b for short I guess) and we're completely discontinuing support of all previous versions of this plugin.
New version works great on Brackets 1.8 and it should be good on lower versions too.

So yeah, we're closing and locking this issue forever and looking forward for you to try out our new version of eqFTP.
I'm sorry if I somehow disturbed you, or you lost your interest in eqFTP or Brackets in general, we're not going to make any noise here again.

If you have any questions, please contact me via email (you can find it in [my profile](https://github.com/Equals182)) or [Telegram app](http://t.me/equals182)

Thank you for understanding 😊
