### ISSUE TITLE
Visual Cue for project / file state

### ISSUE THREAD

**Issue by satur9** [Equals182/eqFTP#162]
UX feature request to have a visual cue in the taskbar area similar to a RAG status indicator. This can be placed next to the eqFTP Queue taskbar item text, and would be useful to indicate:

Green - All files have been synced / uploaded
Amber - Upload in progress
Red - Unsaved files / project (i.e. not yet uploaded changes)

This would provide a simple way to check for unsaved changes and monitor the queue without the need for the queue tray to be open.

**Comment by newelement** [comment]
+1 or just and option to add files to queue when saved/created

**Comment by Equals182** [comment]
### Hello there!

I know this issue been there for a pretty long time, but I have some good news here!
We just released eqFTP v**1.0.0-beta.0** (v1-b for short I guess) and we're completely discontinuing support of all previous versions of this plugin.
New version works great on Brackets 1.8 and it should be good on lower versions too.

So yeah, we're closing and locking this issue forever and looking forward for you to try out our new version of eqFTP.
I'm sorry if I somehow disturbed you, or you lost your interest in eqFTP or Brackets in general, we're not going to make any noise here again.

If you have any questions, please contact me via email (you can find it in [my profile](https://github.com/Equals182)) or [Telegram app](http://t.me/equals182)

Thank you for understanding 😊
