### ISSUE TITLE
[Q] Add to queue specific file and auto uploading after save file?

### ISSUE THREAD

**Issue by Amstramgram** [Equals182/eqFTP#164]
Hi,
i work with eqFTP and it's works fine, but i discovered not long ago SASS for Brackets , he is really cool.
He generate file (main.css) from multi-file scss or sass.

My question is: It's possible to upload main.css when i save from another a file (specific or not) or a folder (specific) ?

Thank you and sorry it's really hard for me to speak in English.

**Comment by Equals182** [comment]
Hi
Yeah, you can do this. All you need is to set up Automatization to Sync, check **File Update** is **Select what to sync** and after that eqFTP will upload any changed file automatically. If it doesn't - help it - upload .css file once and eqFTP will watch for changes until Brackets restart. So basically you saving SCSS and when SASS for Brackets changes CSS file - it will be uploaded automatically.

**Comment by Amstramgram** [comment]
Sorry but i don't see Automatization to Sync or check File Update in Select what to sync. 
Have you a screenshort of this mysterious tab ?

thank you

**Comment by Equals182** [comment]
You probably have an older version of eqFTP. Please install beta from `https://github.com/Equals182/eqFTP`:
1. Open Extension Manager
2. Click Install from URL on bottom of window
3. Paste `https://github.com/Equals182/eqFTP` and click install

Then in Connection's settings you'll see a new Automatization tab

**Comment by Amstramgram** [comment]
Yeah, it's works

btw i have 0.6.2 - 18/12/2014

 Thank you again !

**Comment by Equals182** [comment]
Now you have 0.7.0 :) Have fun!
