### ISSUE TITLE
Extension failure after connection idles for long periods of time

### ISSUE THREAD

**Issue by marcandrews** [Equals182/eqFTP#167]
After a connection to a server idles for an extended period of time and a file upload is attempted, the extension fails with a red alert popup "epipe" error and the eqFTP icon on the right-side panel spinner spins endlessly, requiring a Brackets refresh or even a force-close.

```
[node-error 10:08:44 AM] [eqFTP-ftpDomain]: {"code":"EPIPE"}NodeDebugUtils.js:114 handleLogEvent/utils/EventDispatcher.js:222 trigger/utils/EventDispatcher.js:260 triggerWithArray/utils/NodeConnection.js:479 NodeConnection._receive
NodeDebugUtils.js:114 [node-error 10:08:44 AM] [eqFTP-ftpDomain]: [q.p] Can't connect to server on connectionID: 0. Queue cleared now.NodeDebugUtils.js:114 handleLogEvent/utils/EventDispatcher.js:222 trigger/utils/EventDispatcher.js:260 triggerWithArray/utils/NodeConnection.js:479 NodeConnection._receive
```

v0.7.0

**Comment by Equals182** [comment]
### Hello there!

I know this issue been there for a pretty long time, but I have some good news here!
We just released eqFTP v**1.0.0-beta.0** (v1-b for short I guess) and we're completely discontinuing support of all previous versions of this plugin.
New version works great on Brackets 1.8 and it should be good on lower versions too.

So yeah, we're closing and locking this issue forever and looking forward for you to try out our new version of eqFTP.
I'm sorry if I somehow disturbed you, or you lost your interest in eqFTP or Brackets in general, we're not going to make any noise here again.

If you have any questions, please contact me via email (you can find it in [my profile](https://github.com/Equals182)) or [Telegram app](http://t.me/equals182)

Thank you for understanding 😊
