### ISSUE TITLE
Bug: Connection 'stuck'

### ISSUE THREAD

**Issue by Rann1** [Equals182/eqFTP#169]
Problem: After trying to open an empty folder, eqFTP browse ftp functionality stops. You can not open new folders, nor will it download any files.
Currently rebooted Brackets numerous times, issue seems persistent.

I've clicked a few folders numerous times, also download/ add to queue didnt work.
![eqftp-browsw-bug](https://cloud.githubusercontent.com/assets/13347420/9514311/397f322a-4c99-11e5-9c77-3a79a2c469fb.jpg)

**Comment by Equals182** [comment]
Hi! Sorry for late response! Please, try restarting Node before restarting Brackets (Debug->Restart Node), also try reinstalling eqFTP. This is kinda weird problem. I'm sorry you experience this thing :(

**Comment by Equals182** [comment]
### Hello there!

I know this issue been there for a pretty long time, but I have some good news here!
We just released eqFTP v**1.0.0-beta.0** (v1-b for short I guess) and we're completely discontinuing support of all previous versions of this plugin.
New version works great on Brackets 1.8 and it should be good on lower versions too.

So yeah, we're closing and locking this issue forever and looking forward for you to try out our new version of eqFTP.
I'm sorry if I somehow disturbed you, or you lost your interest in eqFTP or Brackets in general, we're not going to make any noise here again.

If you have any questions, please contact me via email (you can find it in [my profile](https://github.com/Equals182)) or [Telegram app](http://t.me/equals182)

Thank you for understanding 😊
