### ISSUE TITLE
When saving .CSS files it uploads twice

### ISSUE THREAD

**Issue by rjmaturi** [Equals182/eqFTP#170]
I have "upload when saving" and "even if disconnected" activated (I get this bug even if I don't activate the second option).

It always uploads twice .CSS files. I have no problems with other files.

Sometimes it tries to upload .CSS files twice and it gets stuck in "Waiting" status. I then have to cancel those two upload attemps and try again. Usually doing this gives me a "Completed" status. But it always uploads twice per save.

Is it really a bug or am I doing something wrong?

![css-upload-twice](https://cloud.githubusercontent.com/assets/8105352/9607947/87d1eef8-5091-11e5-91c9-87ebad685299.jpg)

**Comment by Equals182** [comment]
### Hello there!

I know this issue been there for a pretty long time, but I have some good news here!
We just released eqFTP v**1.0.0-beta.0** (v1-b for short I guess) and we're completely discontinuing support of all previous versions of this plugin.
New version works great on Brackets 1.8 and it should be good on lower versions too.

So yeah, we're closing and locking this issue forever and looking forward for you to try out our new version of eqFTP.
I'm sorry if I somehow disturbed you, or you lost your interest in eqFTP or Brackets in general, we're not going to make any noise here again.

If you have any questions, please contact me via email (you can find it in [my profile](https://github.com/Equals182)) or [Telegram app](http://t.me/equals182)

Thank you for understanding 😊
