### ISSUE TITLE
I cannot select SFTP nor FTPS protocols.

### ISSUE THREAD

**Issue by wyattbiker** [Equals182/eqFTP#173]
Any ideas? I tried mouse and arrow keys

**Comment by Equals182** [comment]
You're using v0.6.0 but SFTP is only in 0.7.0. You can download it via link. Follow these steps (http://equals182.github.io/eqFTP/#installing) to instal beta version

**Comment by wyattbiker** [comment]
For now I changed manually in configuration file.  Is there logging for error messages to see why the connection never happens? There are no messages and no directories show up. Thanks.

**Comment by Equals182** [comment]
Is there still a FTPS option in list?

**Comment by wyattbiker** [comment]
Yes there is. But I have manually set it in remoteSettings to SFTP. Does not connect nor give messages. I use WinSCP to that server with Putty and connects fine.  Any ideas?

**Comment by Equals182** [comment]
Because there's no SFTP functionality in this version you're using right now. You need to update as I said above to be able to use SFTP.

**Comment by wyattbiker** [comment]
Just did. Looks very nice. But do I need an RSA key or is it optional?

**Comment by Equals182** [comment]
it's optional

**Comment by wyattbiker** [comment]
Any suggestions on how to debug? Any error messages or log files I can look at?

**Comment by Equals182** [comment]
http://equals182.github.io/eqFTP/#creating-issue
