### ISSUE TITLE
What does this error mean?

### ISSUE THREAD

**Issue by wyattbiker** [Equals182/eqFTP#175]
latest beta version: Error: {"level":"authentication","partial":false}

Brackets is on Windows 7 box , my project is on Linux box which I currently connect using WinSCP/Putty using password.

Some debug code:
NodeDebugUtils.js:117 [node-log 11:07:57 AM] [eqFTP-ftpDomain]: Connecting to this ID: 0
main.js:1644 Object {event: "server_connecting", connectionID: 0}
NodeDebugUtils.js:117 [node-log 11:07:57 AM] [eqFTP-ftpDomain]: Connecting...
NodeDebugUtils.js:114 [node-error 11:07:57 AM] [eqFTP-ftpDomain]: 322: [c.cC] Can't create sftp Client for ID: 0. Error: {"level":"authentication","partial":false}
NodeDebugUtils.js:114 [node-error 11:07:57 AM] [eqFTP-ftpDomain]: [q.p] Can't connect to server on connectionID: 0. Queue cleared now.
NodeDebugUtils.js:117 [node-log 11:07:57 AM] [eqFTP-ftpDomain]: Disconnecting...
main.js:1644 Object {event: "server_disconnecting", connectionID: 0, clearQueue: true}

**Comment by Equals182** [comment]
It may be an authentication error. Since I'm using node libraries to connect to FTP and SFTP servers, it can also be a bug in there. Currently I'm using SFTP without any issues (using just password and nothing else). Check your host filed, user and password. Maybe there's a whitespace somewhere.

**Comment by Equals182** [comment]
### Hello there!

I know this issue been there for a pretty long time, but I have some good news here!
We just released eqFTP v**1.0.0-beta.0** (v1-b for short I guess) and we're completely discontinuing support of all previous versions of this plugin.
New version works great on Brackets 1.8 and it should be good on lower versions too.

So yeah, we're closing and locking this issue forever and looking forward for you to try out our new version of eqFTP.
I'm sorry if I somehow disturbed you, or you lost your interest in eqFTP or Brackets in general, we're not going to make any noise here again.

If you have any questions, please contact me via email (you can find it in [my profile](https://github.com/Equals182)) or [Telegram app](http://t.me/equals182)

Thank you for understanding 😊
