### ISSUE TITLE
Watch files for change

### ISSUE THREAD

**Issue by jkalousek** [Equals182/eqFTP#179]
Could you implement "Watchdog" for selected files/folder which would upload file if it changes - not just when file is saved within brackets?
I'm using SASS more and more, but I must upload generated file each time manually so there would be really good feature, if plugin can check file for change and then if it does change upload it.

It is at least possible?

**Comment by Equals182** [comment]
It's a thing since v0.7.0. The only thing you need to do is to switch to "sync" mode in automatization tab and select "File update" event after that. It will watch everthing in project folder for any changes and upload it. To make rules what to upload and what to ignore, use "Ignore" option in Sync settings. 
You can read about this feature here: http://equals182.github.io/eqFTP/#sync

**Comment by jkalousek** [comment]
Sorry but that is not working for me, I have Sync mode active in Automatization tab and I have checked all checkboxes below, but when css file is generated from scss (via. jasonsanjose/brackets-sass) it is not uploaded to FTP. When I hit upload manually it is uploaded instantly…

**Comment by Equals182** [comment]
Sometimes it needs one manual upload before brackets will start watching
it. Eqftp uses default brackets methods for watching changes in files so
it's probably not an issue in brackets. I'm using this feature rn and it's
working fine.
Try that: upload final css file once and then change and compile scss file.
Check what files were uploaded after compilation. You may want to use debug
mode to see what's going on inside.
Also please be really careful about those ☑ in sync settings. I highly
recommend to use only "update" feature.

**Comment by jkalousek** [comment]
It not consistent problem, sometimes it’s working fine, but another time I got it working after maybe 4th scss file generation. I will watch debug output and let you know if I find something.

**Comment by Equals182** [comment]
I know sometimes it's not working fine, but I believe it's because brackets
doesn't watch all files perfectly - sometimes it fires change event and
sometimes it doesn't. It's weird. Quick solution is to upload output file
once and then forget about it until next start of brackets.
