### ISSUE TITLE
Impossible to select SFTP

### ISSUE THREAD

**Issue by philmarty** [Equals182/eqFTP#180]
Hello,

When I'm creating a new connection, I can't select SFTP, even if I can see it in the dropdown list. I even select port 22 in case there was a filter, but no way.
Where is the problem?

I'm using eqFTP 0.6.2 with Brackets 1.5.0-16538

**Comment by Equals182** [comment]
You need to update to 0.7.0 via github to use sftp. Check
http://equals182.github.io/eqFTP/ for more information.
