### ISSUE TITLE
Недоступен выбор соединения по SFTP и FTPS

### ISSUE THREAD

**Issue by zamkevich** [Equals182/eqFTP#182]
Не могу выбрать соединение  SFTP и FTPS
Скрин:
http://take.ms/1YXP0

У меня:
eqFTP: 1.1
system: OS X El Capitan
Brackets: 1.5

**Comment by Equals182** [comment]
Вам нужно обновиться до последней версии eqFTP напрямую с гитахаба. Я чет слажал и сделал их disabled тип будет такой функционал, а теперь все спрашивают.
Зайдите в менеджер дополнений, нажмите установка по URL и введите https://github.com/Equals182/eqFTP
Потом вручную перезапустите Brackets и SFTP будет работать. Ну, скорее всего))
Гудлак.

**Comment by zamkevich** [comment]
Ух ты, ты так быстро ответил). Спасибо, попробую.
