### ISSUE TITLE
После установки требует ввести пароль

### ISSUE THREAD

**Issue by Lehakos** [Equals182/eqFTP#184]
После установки расширения, требует ввести пароль. Когда жму отмена, появляется табличка: "Не могу прочитать настройки, возможно вы неправильно ввели мастер-пароль".

**Comment by Equals182** [comment]
У вас включена функция мастер пароля? Нажмите отмену, откройте настройки,
уберите галочку мастер пароля и сохраните настройки. Должно сработать.

**Comment by Lehakos** [comment]
После нажатия отмены ничего не открывается, кроме того сообщения, что я написал

**Comment by Equals182** [comment]
И если закрыть это сообщение и нажать на кнопке справа, на панели
дополнений, то он опять спросит пароль?

**Comment by Lehakos** [comment]
Да

**Comment by Equals182** [comment]
Хм. Странно. Впервые слышу о такой ошибке. Попробуйте открыть файл настроек
brackets.json: отладка -> открыть файл настроек. Там будет параметр
eqFTP.useEncryption поставьте его в false. После сохраните файл и
перезагрузите brackets.

**Comment by Lehakos** [comment]
Пароль больше не требует, но и расширение не открывается :( Сначала я установил расширение через менеджер, оно открывалось, но там была устаревшая версия без sftp. Я установил через урл новую версию и вот такая ерунда.

**Comment by Equals182** [comment]
Попробуйте удалить расширение полностью (из папки в
appdata/roaming/brackets/extensions/user ), перезагрузить brackets и
установить его заново. Если не поможет, попробуем посмотреть в консоли в
чем дело.

**Comment by Lehakos** [comment]
Это не помогло :(

**Comment by Equals182** [comment]
Откройте Brackets, нажмите F12 и перейдите во вкладку Console. После нажмите на иконку eqFTP и посмотрите консоль. Скиньте мне, пожалуйста, ее содержимое. Если там есть какие-либо персональные данные - пожалуйста, спрячьте их.

**Comment by Lehakos** [comment]
http://joxi.ru/V2VBL4WF0EEkg2

**Comment by Equals182** [comment]
Пока никаких ошибок со стороны eqftp не видно. 
Обновитесь, пожалуйста, с другого (https://github.com/Equals182/Buggy-eqFTP) репозитория и повторите действия. Там должны будут появиться несколько новых строк, которые помогут понять, где конкретно находится ошибка.

**Comment by mamezito** [comment]
после обновления не позволяет работать с пустым паролем - у меня было без пароля, нажимал OK и работал, щас поле подсвечивает красным и не дает работать (

**Comment by Equals182** [comment]
@mamezito о каком пароле речь? Мастер пароль для приложения? или пароль к северу?

**Comment by mamezito** [comment]
пароль eqftp https://www.dropbox.com/s/horimm9arypc9ea/Screenshot%202015-12-17%2012.53.33.png?dl=0

**Comment by Equals182** [comment]
Хм. Никогда не думал, что кто-то будет использовать пустой пароль.
Чтобы спасти ваши сохраненные подключения, советую скопировать файл `.remotesettings` куда-либо еще, опуститься до 0.6.2 версии, открыть настройки и убрать пароль с настроек. После этого вновь обновиться до последней версии (если вам это действительно нужно, конечно). Старую версию можно найти тут: https://github.com/Equals182/eqFTP/releases/tag/v0.6.2

**Comment by mamezito** [comment]
попробуем, спасибо

**Comment by Simon1111** [comment]
Та же самая ошибка. Честно сказать эта опция вообще лишняя, и только раздражает.

**Comment by Equals182** [comment]
Эээм.. выключите ее? лол

**Comment by mamezito** [comment]
в старой версии сетингсы не работают, а в новую соотвественно зайти нельзя с нулевым паролем

**Comment by Equals182** [comment]
В каком смысле не работают? Формат настроек не менялся, так что все должно быть ок.
Давайте попробуем еще раз:
1. Скопируйте файл настроек в безопасное место
2. Удалите версию 0.7
3. Установите версию 0.6.2
4. Установите пароль в настройках
5. Закройте Brackets
6. Замените файл `.remotesettings`, который расположен в папке, указанной в настройке `Folder For Settings` (`Папка для настроек`) на файл, который вы скопировали на первом шаге
7. Запустите Brackets и введите пустой пароль
8. Зайдите настройки, снимите галочку `Безопасное хранение` или как там она называлась, и сохраните настройки
9. Откройте файл настроек любым тестовым редактором и убедитесь, что внутри обычный json
10. Скопируйте его на время в безопасное место
11. Установите 0.7.0
12. Настройте папки для проектов и настроек
13. Уберите галочку с `Мастер пароля`
14. Закройте Brackets
15. Положите `.remotesettings` в папку с настройками
16. Откройте Brackets и проверьте все ли работает.

**Comment by Simon1111** [comment]
Хорошо, спасибо. Завтра попробую.

**Comment by Equals182** [comment]
### Hello there!

I know this issue been there for a pretty long time, but I have some good news here!
We just released eqFTP v**1.0.0-beta.0** (v1-b for short I guess) and we're completely discontinuing support of all previous versions of this plugin.
New version works great on Brackets 1.8 and it should be good on lower versions too.

So yeah, we're closing and locking this issue forever and looking forward for you to try out our new version of eqFTP.
I'm sorry if I somehow disturbed you, or you lost your interest in eqFTP or Brackets in general, we're not going to make any noise here again.

If you have any questions, please contact me via email (you can find it in [my profile](https://github.com/Equals182)) or [Telegram app](http://t.me/equals182)

Thank you for understanding 😊
