### ISSUE TITLE
Automatic save to server option

### ISSUE THREAD

**Issue by SheepDomination** [Equals182/eqFTP#185]
I like eqFTP except two issues, why does it seems to time out whereas, when I try to upload my file via, right click and upload, instead, I have to open eqFTP on the server, open a directory on the server, then, and sometimes it doesn't work but usually, then, and only then can I upload the file once again ?

If I'm loading a file from a server, does it make sense that when I save the file it is automatically uploaded and saved to the server or overwrote the existing file, instead of having to right click the file in Brackets and choose upload, this is something I wish was atleast an option in eqFTP.

**Comment by Equals182** [comment]
You should be able to upload any file from local project if your automatization option is set to `Classic` and `Even if disconnected` is on, or your automatization option is set to `Sync` and `File update` is on (v0.7.0). If it's not happening then there's probably a bug somewhere - we can debug it via console.

I don't really understand second issue. It should syncronize changes automatically from local project to remote. You can just save file and it will be automatically uploaded at same directory on remote server if you chose one of automatization options.

**Comment by SheepDomination** [comment]
Automatization option; I don't see any Automatization option within eqFTP ?

With regards to my second question, when I save the file, I also have to right click the file and choose upload, even though I'm loading the file from the server.  Strictly saving the file does not automatically save it on the server or overwrite the existing file, which is what I was hoping for; that is not occurring.

**Comment by Equals182** [comment]
Uploading file after saving is what eqFTP made for :) Please update from this url: https://github.com/Equals182/eqFTP
Open extension manager, click `Install from URL` on the bottom of window and paste link.
After that restart Brackets and you'll be able to see Automatization tab in Connection settings. Check instructions for more information: http://equals182.github.io/eqFTP/#creating-connection

**Comment by SheepDomination** [comment]
Ah, I was using an older version.  This is better, I hope all works well :)

**Comment by Equals182** [comment]
Let me know if you solved it or not

**Comment by SheepDomination** [comment]
Hi, things are working better, I'd say it is solved :)

**Comment by Equals182** [comment]
Glad to hear it. Hope you won't have any more problems with this extension.. but yeah, it's still kinda buggy anyway.
Have fun!
