### ISSUE TITLE
Can eqFTP creates new file on server via FTP connection?

### ISSUE THREAD

**Issue by javasworks** [Equals182/eqFTP#187]
Hi,
i can't figure how to create new file & new folder on opened connection. Doing right click on folder, there are only:

- Download
- Add to Queue
- Rename
- Delete

**Comment by Equals182** [comment]
Yes, try version 0.7. Look here http://equals182.github.io/eqFTP/#installing
for details (beta version section)

On Mon, Nov 30, 2015, 07:12 Javas Works <notifications@github.com> wrote:

Hi,
i can't figure how to create new file & new folder on opened connection.
Doing right click on folder, there are only:

DownloadAdd to QueueRenameDelete

—
Reply to this email directly or view it on GitHub
<https://github.com/Equals182/eqFTP/issues/187>.<img src="
https://ci5.googleusercontent.com/proxy/5JhEAUhmG5dE-DHIYVhfrmJm18Eo3OQfT1oxws_wWlGSvBn6fXUY9RadTiQVPzgvjK3jJXfpiqOL3sbfDCUoreBzI14UHXqCkKbUh7fTXi9gFDs7VXKC_VeeBY8wjEcBqho6jzyMZHWKqhwIWVV-nhYeYoISjw=s0-d-e1-ft#https://github.com/notifications/beacon/AEDsU4BB9xLfj-cDlzkGB_wEevDbziOqks5pK8QkgaJpZM4GrK_K.gif
">

**Comment by javasworks** [comment]
Wow thanks @Equals182 :D , that version is very good. Much better than the old version

**Comment by Equals182** [comment]
I hope someday I'll release even better version.
Have fun.
