### ISSUE TITLE
eqFTP is not loading

### ISSUE THREAD

**Issue by mzeledon** [Equals182/eqFTP#188]
I keep getting this code when I try to connect to my server:

 [node-error 9:58:53 PM] [eqFTP-ftpDomain]: [s.l][FTP-error] {"code":"ETIMEDOUT","errno":"ETIMEDOUT","syscall":"connect"}
main.js:1644 Object {event: "server_connection_error", err: Object, connectionID: 1}
main.js:1644 Object {event: "server_disconnect", err: Object, connectionID: 1}
main.js:1859 [eqFTP] Disconnected from server
NodeDebugUtils.js:114 [node-error 9:58:53 PM] [eqFTP-ftpDomain]: [q.p] Can't connect to server on connectionID: 1. Queue cleared now.
NodeDebugUtils.js:117 [node-log 9:58:53 PM] [eqFTP-ftpDomain]: Disconnecting...
main.js:1644 Object {event: "server_disconnecting", connectionID: 1, clearQueue: true}
NodeDebugUtils.js:117 [node-log 9:58:53 PM] [eqFTP-queueisbusy][c.d no connection] Setting busy to false
NodeDebugUtils.js:117 [node-log 9:58:53 PM] [eqFTP-ftpDomain]: Disonnected. Actually there was no client so nothing to disconnect.

What does this mean and how can I fix it?

**Comment by Equals182** [comment]
It looks like timeout error and there can be lots of reasons for it. Is this a full log you got?

**Comment by Equals182** [comment]
### Hello there!

I know this issue been there for a pretty long time, but I have some good news here!
We just released eqFTP v**1.0.0-beta.0** (v1-b for short I guess) and we're completely discontinuing support of all previous versions of this plugin.
New version works great on Brackets 1.8 and it should be good on lower versions too.

So yeah, we're closing and locking this issue forever and looking forward for you to try out our new version of eqFTP.
I'm sorry if I somehow disturbed you, or you lost your interest in eqFTP or Brackets in general, we're not going to make any noise here again.

If you have any questions, please contact me via email (you can find it in [my profile](https://github.com/Equals182)) or [Telegram app](http://t.me/equals182)

Thank you for understanding 😊
