### ISSUE TITLE
File upload upon Save

### ISSUE THREAD

**Issue by Rann1** [Equals182/eqFTP#191]
My followed steps:

Opened an website I'm working on. Edited some files. Suddenly stops uploading when saving. The following appears in error log:
![image](https://cloud.githubusercontent.com/assets/13347420/11869273/bf2c8b7a-a4be-11e5-8a2e-7677f3c4436b.png)

Update rocks visually though!

**Comment by Equals182** [comment]
This is probably one of knows issues. It worked first and then suddenly stopped, right?
Does it work after Brackets restart? Do you have `Keep Alive` option on (greater than 0)?

**Comment by Rann1** [comment]
Correct,
In the old version it immediatly worked after restart. With the new update I had to re-open it twice, not sure if it was a bug on my side or not.

Keep alive is set on default (10)

**Comment by Equals182** [comment]
### Hello there!

I know this issue been there for a pretty long time, but I have some good news here!
We just released eqFTP v**1.0.0-beta.0** (v1-b for short I guess) and we're completely discontinuing support of all previous versions of this plugin.
New version works great on Brackets 1.8 and it should be good on lower versions too.

So yeah, we're closing and locking this issue forever and looking forward for you to try out our new version of eqFTP.
I'm sorry if I somehow disturbed you, or you lost your interest in eqFTP or Brackets in general, we're not going to make any noise here again.

If you have any questions, please contact me via email (you can find it in [my profile](https://github.com/Equals182)) or [Telegram app](http://t.me/equals182)

Thank you for understanding 😊
