### ISSUE TITLE
Remote Path bug

### ISSUE THREAD

**Issue by sasagit** [Equals182/eqFTP#193]
I have local folder named html_new and on upload folder "_new" is added to Remote Path.

So if I have C:/html_new for Local Path and mysite for Remote Path files are uploaded to mysite/_new/.

**Comment by Equals182** [comment]
Hi!
I need some debug info, 'cause I don't have any troubles uploading files with `_` symbol. Please follow steps 2-5 here: http://equals182.github.io/eqFTP/#creating-issue

**Comment by sasagit** [comment]
It seams that if I have one saved FTP connection with Local Path C:/project/html and if I add another connection C:/project/html_new it ads "_new" or if Local Path is C:/project/htmlasd "asd" is added  to Remote Path or whatever is after html so it is not the problem with _ symbol

**Comment by Equals182** [comment]
Yeah, looks like it's problem with detecting related connection. 
Can you please update from `https://github.com/Equals182/Buggy-eqFTP`, turn off debug mode and check console on upload event? I need to see if it really is detecting problem.

**Comment by sasagit** [comment]
this is what I get from console on upload
main.js:1109 /^C:\/project\/html\//gi "C:/project/html_new/" "result: "
main.js:1109 /^C:\/project\/html_new\//gi "C:/project/html_new/" "result: "
main.js:1111 found
main.js:1109 /^C:\/project\/html\//gi "C:/project/html_new/" "result: "
main.js:1109 /^C:\/project\/html_new\//gi "C:/project/html_new/" "result: "
main.js:1111 found

**Comment by Equals182** [comment]
*May be* I fixed it here: https://github.com/Equals182/Buggy-eqFTP
Please update and tell me if it works.

**Comment by sasagit** [comment]
Thank you for this, everything works now with similar names
