### ISSUE TITLE
Connection will only work when remote path is empty

### ISSUE THREAD

**Issue by src053** [Equals182/eqFTP#195]
It looks like the connection is putting me in the root of the remote server.  However when starting the remote path with /home it always presents an error that remote path is not present.  When I leave the remote path blank it connects in and I can browse in the /home directory.

**Comment by Equals182** [comment]
Have you tried `home` instead of `/home`? Also, can you please post debug info? Check steps 2-4 here: http://equals182.github.io/eqFTP/#creating-issue

**Comment by src053** [comment]
Ya I have tried home and /home

**Comment by alekks** [comment]
I've got the same issue.
Console output: 
[node-error 11:19:07 AM] [eqFTP-ftpDomain]: [r.c] Can't get in directory: home. Trying to get in /. The error is: stdin: is not a tty

When remote path is empty I get to root and see that right there's the home directory, but regardless to what I enter into remote path I get this error.
I've tried ~/home, ~/home/, /home/, /home, home/, ../home, ../home/ etc etc just to be sure, even tried backslashes. Only time I get the list is when the remote path is empty.

**Comment by Equals182** [comment]
### Hello there!

I know this issue been there for a pretty long time, but I have some good news here!
We just released eqFTP v**1.0.0-beta.0** (v1-b for short I guess) and we're completely discontinuing support of all previous versions of this plugin.
New version works great on Brackets 1.8 and it should be good on lower versions too.

So yeah, we're closing and locking this issue forever and looking forward for you to try out our new version of eqFTP.
I'm sorry if I somehow disturbed you, or you lost your interest in eqFTP or Brackets in general, we're not going to make any noise here again.

If you have any questions, please contact me via email (you can find it in [my profile](https://github.com/Equals182)) or [Telegram app](http://t.me/equals182)

Thank you for understanding 😊
