### ISSUE TITLE
FTP-error ECONNRESET

### ISSUE THREAD

**Issue by sasagit** [Equals182/eqFTP#196]
After some time working without problems ftp just stop working, then I have to reload brackets and it works again.

I get this in console
[node-log 8:45:23 AM] [eqFTP-ftpDomain]: [c.c] Connection already exists for this ID: 19
NodeDebugUtils.js:117 [node-log 8:45:23 AM] DEBUG:  user_command
NodeDebugUtils.js:117 [node-log 8:45:23 AM] "NOOP"
NodeDebugUtils.js:117 [node-log 8:45:23 AM] DEBUG:  server_response
NodeDebugUtils.js:117 [node-log 8:45:23 AM] {
  "code": 200,
  "text": "200 NOOP command successful",
  "isMark": false,
  "isError": false
}
NodeDebugUtils.js:117 [node-log 8:45:33 AM] [eqFTP-ftpDomain]: [c.c] Connection already exists for this ID: 19
NodeDebugUtils.js:117 [node-log 8:45:33 AM] DEBUG:  user_command
NodeDebugUtils.js:117 [node-log 8:45:33 AM] "NOOP"
NodeDebugUtils.js:114 [node-error 8:45:33 AM] [eqFTP-ftpDomain]: [s.l][FTP-error] {"code":"ECONNRESET","errno":"ECONNRESET","syscall":"read"}NodeDebugUtils.js:114 handleLogEvent

**Comment by Equals182** [comment]
Yeah, eqFTP still have some problems with handling some errors :( Sorry about that.

**Comment by sasagit** [comment]
No problem :) and thank you for this great extension. Hope this problems will be fixed soon.

**Comment by Equals182** [comment]
### Hello there!

I know this issue been there for a pretty long time, but I have some good news here!
We just released eqFTP v**1.0.0-beta.0** (v1-b for short I guess) and we're completely discontinuing support of all previous versions of this plugin.
New version works great on Brackets 1.8 and it should be good on lower versions too.

So yeah, we're closing and locking this issue forever and looking forward for you to try out our new version of eqFTP.
I'm sorry if I somehow disturbed you, or you lost your interest in eqFTP or Brackets in general, we're not going to make any noise here again.

If you have any questions, please contact me via email (you can find it in [my profile](https://github.com/Equals182)) or [Telegram app](http://t.me/equals182)

Thank you for understanding 😊
