### ISSUE TITLE
FTP checkin/checkout - Version control (Improvement Request)

### ISSUE THREAD

**Issue by scramble45** [Equals182/eqFTP#197]
I would really like see adding a basic version control system similar to how dreamweaver works for checking in and checking out files.

Here is some basic information about it: 
https://helpx.adobe.com/dreamweaver/using/checking-checking-out-files.html

https://en.wikipedia.org/wiki/Version_control

**Comment by FurmanSK** [comment]
I agree, this would be nice. I just submitted one today about this before I realized this was already requested. I'll leave mine as another way to look at it for version control.

**Comment by Equals182** [comment]
### Hello there!

I know this issue been there for a pretty long time, but I have some good news here!
We just released eqFTP v**1.0.0-beta.0** (v1-b for short I guess) and we're completely discontinuing support of all previous versions of this plugin.
New version works great on Brackets 1.8 and it should be good on lower versions too.

So yeah, we're closing and locking this issue forever and looking forward for you to try out our new version of eqFTP.
I'm sorry if I somehow disturbed you, or you lost your interest in eqFTP or Brackets in general, we're not going to make any noise here again.

If you have any questions, please contact me via email (you can find it in [my profile](https://github.com/Equals182)) or [Telegram app](http://t.me/equals182)

Thank you for understanding 😊
