### ISSUE TITLE
Doesn't auto upload after CTRL-S

### ISSUE THREAD

**Issue by FurmanSK** [Equals182/eqFTP#198]
It used to work when I first installed it but after a couple of reloads and restarts it doesn't work anymore. I can't figure out why. It connects if I force it to or if I right click a file and upload but if I save the document it won't auto-upload it.  Yes I have it enabled in the options for each connection too. 

Also I've noticed I can't clear the queue. Don't know if that's an issue also but figured I'd mention it.

Brackets Version:
Release 1.6 build 1.6.0-16680 (release 3df0ac6fa)

eqFTP: v0.7.2

Console doesn't really show errors when I do a save. just keeps looping and saying Keep Alive. 
CONSOLE OUTPUT: 
```
 [node-log 9:31:11 AM] [eqFTP-ftpDomain]: Adding connections.
NodeDebugUtils.js:117 [node-log 9:31:11 AM] [eqFTP-ftpDomain]: 136: Checking connection ID: 0
NodeDebugUtils.js:117 [node-log 9:31:11 AM] [eqFTP-ftpDomain]: 147: Getting existent connection by ID, result: undefined
NodeDebugUtils.js:117 [node-log 9:31:11 AM] [eqFTP-ftpDomain]: 173: Adding new connection: "tnweb1"
NodeDebugUtils.js:117 [node-log 9:31:11 AM] [eqFTP-ftpDomain]: 136: Checking connection ID: 1
NodeDebugUtils.js:117 [node-log 9:31:11 AM] [eqFTP-ftpDomain]: 147: Getting existent connection by ID, result: undefined
NodeDebugUtils.js:117 [node-log 9:31:11 AM] [eqFTP-ftpDomain]: 173: Adding new connection: "tnsclp1"
NodeDebugUtils.js:117 [node-log 9:31:19 AM] [eqFTP-ftpDomain]: 1870: [q.a] Queuer is NOT ignored, continueing
NodeDebugUtils.js:117 [node-log 9:31:19 AM] [eqFTP-ftpDomain]: 1901: [q.a] Queue updated: {"a":[{"type":"folder","connectionID":1,"path":"","id":"f_1453991479073855","state":"opened","queue":"a"}],"p":[],"f":[],"s":[]}
NodeDebugUtils.js:117 [node-log 9:31:19 AM] [eqFTP-ftpDomain]: Connecting to this ID: 1
main.js:1629 Object {event: "queue_update", connectionID: 1, element: Object}
main.js:1629 Object {event: "working", work: true}
main.js:1629 Object {event: "queue_update", connectionID: 1, element: Object}
main.js:1629 Object {event: "server_connecting", connectionID: 1}
NodeDebugUtils.js:117 [node-log 9:31:19 AM] [eqFTP-ftpDomain]: Connecting...
main.js:1629 Object {event: "server_connect", connectionID: 1}
NodeDebugUtils.js:117 [node-log 9:31:19 AM] [eqFTP-ftpDomain]: Connected...
NodeDebugUtils.js:117 [node-log 9:31:19 AM] [eqFTP-ftpDomain]: [s.gRR] Getting remote root for this ID: 1
NodeDebugUtils.js:117 [node-log 9:31:19 AM] [eqFTP-ftpDomain]: [s.gRR] User set Remote Path to: /usr/alcoa/scalper/src
2NodeDebugUtils.js:117 [node-log 9:31:19 AM] [eqFTP-ftpDomain]: [c.c] Connection already exists for this ID: 1
NodeDebugUtils.js:117 [node-log 9:31:19 AM] [eqFTP-ftpDomain]: [s.gRR] Remote root for this ID: 1 is /usr/alcoa/scalper/src
NodeDebugUtils.js:117 [node-log 9:31:19 AM] [eqFTP-ftpDomain]: [c.c] Connection already exists for this ID: 1
NodeDebugUtils.js:117 [node-log 9:31:20 AM] [eqFTP-ftpDomain]: 1172: [s.gP] Got Directory: /usr/alcoa/scalper/src/
NodeDebugUtils.js:117 [node-log 9:31:20 AM] [eqFTP-ftpDomain]: [q.p] Got folder: /usr/alcoa/scalper/src/
NodeDebugUtils.js:117 [node-log 9:31:20 AM] [eqFTP-ftpDomain]: [q.p] Queue is empty
main.js:1629 Object {event: "directory_got", files: Array[1263], path: "", connectionID: 1, queuer: Object}
main.js:1629 Object {event: "working", work: false}
NodeDebugUtils.js:117 [node-log 9:31:29 AM] [eqFTP-ftpDomain]: [c.c] Connection already exists for this ID: 1
NodeDebugUtils.js:117 [node-log 9:31:29 AM] [eqFTP-ftpDomain]: Keep Alive (cd .) SFTP
NodeDebugUtils.js:117 [node-log 9:31:39 AM] [eqFTP-ftpDomain]: [c.c] Connection already exists for this ID: 1
NodeDebugUtils.js:117 [node-log 9:31:39 AM] [eqFTP-ftpDomain]: Keep Alive (cd .) SFTP
NodeDebugUtils.js:117 [node-log 9:31:49 AM] [eqFTP-ftpDomain]: [c.c] Connection already exists for this ID: 1
NodeDebugUtils.js:117 [node-log 9:31:49 AM] [eqFTP-ftpDomain]: Keep Alive (cd .) SFTP
NodeDebugUtils.js:117 [node-log 9:31:59 AM] [eqFTP-ftpDomain]: [c.c] Connection already exists for this ID: 1
NodeDebugUtils.js:117 [node-log 9:31:59 AM] [eqFTP-ftpDomain]: Keep Alive (cd .) SFTP
NodeDebugUtils.js:117 [node-log 9:32:09 AM] [eqFTP-ftpDomain]: [c.c] Connection already exists for this ID: 1
NodeDebugUtils.js:117 [node-log 9:32:09 AM] [eqFTP-ftpDomain]: Keep Alive (cd .) SFTP
NodeDebugUtils.js:117 [node-log 9:32:19 AM] [eqFTP-ftpDomain]: [c.c] Connection already exists for this ID: 1
NodeDebugUtils.js:117 [node-log 9:32:19 AM] [eqFTP-ftpDomain]: Keep Alive (cd .) SFTP
NodeDebugUtils.js:117 [node-log 9:32:29 AM] [eqFTP-ftpDomain]: [c.c] Connection already exists for this ID: 1
NodeDebugUtils.js:117 [node-log 9:32:29 AM] [eqFTP-ftpDomain]: Keep Alive (cd .) SFTP
```

**Comment by Equals182** [comment]
I'll send you special version for debugging tomorrow. Please stay tuned.

**Comment by Equals182** [comment]
Please install test version from `https://github.com/Equals182/Buggy-eqFTP`
Follow these steps to install from url: `http://equals182.github.io/eqFTP/#installing` (steps for beta version, except different url from this message)
Restart your Brackets manually after installation and try again. You'll see lots of `[eqftp-save-debug]` log lines in console. Please send me those in right order but don't forget to delete all personal info if you found some in there.

**Comment by FurmanSK** [comment]
Here's the first attempt at doing a ctrl-s to upload it. It just sits there
spinning on the folder icon on the right. And in the queue it has it shown
as started but isn't doing anything. I tried to manually connect but it's
not for whatever reason.

[node-log 11:18:33 AM] [eqFTP-ftpDomain]: Adding connections.
NodeDebugUtils.js:117 [node-log 11:18:33 AM] [eqFTP-ftpDomain]: 136:
Checking connection ID: 0
NodeDebugUtils.js:117 [node-log 11:18:33 AM] [eqFTP-ftpDomain]: 147:
Getting existent connection by ID, result: "tnweb1"
NodeDebugUtils.js:117 [node-log 11:18:33 AM] [eqFTP-ftpDomain]: 150:
Checking if creditials are not same
NodeDebugUtils.js:117 [node-log 11:18:33 AM] [eqFTP-ftpDomain]: 136:
Checking connection ID: 1
NodeDebugUtils.js:117 [node-log 11:18:33 AM] [eqFTP-ftpDomain]: 147:
Getting existent connection by ID, result: "tnsclp1"
NodeDebugUtils.js:117 [node-log 11:18:33 AM] [eqFTP-ftpDomain]: 150:
Checking if creditials are not same
NodeDebugUtils.js:117 [node-log 11:18:33 AM] [eqFTP-ftpDomain]: [s.d.i.cs]
Checking for ignoring.
NodeDebugUtils.js:117 [node-log 11:18:33 AM] [eqFTP-ftpDomain]: 1870: [q.a]
Queuer is NOT ignored, continueing
NodeDebugUtils.js:117 [node-log 11:18:33 AM] [eqFTP-ftpDomain]: 1901: [q.a]
Queue updated: {"a":[{"localPath":"C:/Users/formawc/Documents/eqFTP
Projects/tnweb1/scalper/scalperlaserrecord.html","remotePath":"/scalper/scalperlaserrecord.html","name":"scalperlaserrecord.html","direction":"upload","queue":"a","type":"file","connectionID":0,"after":"disconnect","id":"f_1454084313664355"}],"p":[],"f":[],"s":[]}
main.js:1629 Object {event: "queue_update", connectionID: 0, element:
Object}
main.js:1629 Object {event: "working", work: true}
main.js:1629 Object {event: "queue_update", connectionID: 0, element:
Object}
NodeDebugUtils.js:117 [node-log 11:18:33 AM] [eqFTP-ftpDomain]: Connecting
to this ID: 0
main.js:1629 Object {event: "server_connecting", connectionID: 0}
NodeDebugUtils.js:117 [node-log 11:18:33 AM] [eqFTP-ftpDomain]:
Connecting...
NodeDebugUtils.js:117 [node-log 11:18:33 AM] [eqFTP-ftpDomain]: Adding
connections.
NodeDebugUtils.js:117 [node-log 11:18:33 AM] [eqFTP-ftpDomain]: 136:
Checking connection ID: 0
NodeDebugUtils.js:117 [node-log 11:18:33 AM] [eqFTP-ftpDomain]: 147:
Getting existent connection by ID, result: "tnweb1"
NodeDebugUtils.js:117 [node-log 11:18:33 AM] [eqFTP-ftpDomain]: 150:
Checking if creditials are not same
NodeDebugUtils.js:117 [node-log 11:18:33 AM] [eqFTP-ftpDomain]: 136:
Checking connection ID: 1
NodeDebugUtils.js:117 [node-log 11:18:33 AM] [eqFTP-ftpDomain]: 147:
Getting existent connection by ID, result: "tnsclp1"
NodeDebugUtils.js:117 [node-log 11:18:33 AM] [eqFTP-ftpDomain]: 150:
Checking if creditials are not same
main.js:1629 Object {event: "server_connect", connectionID: 0}
NodeDebugUtils.js:117 [node-log 11:18:34 AM] [eqFTP-ftpDomain]: Connected...
NodeDebugUtils.js:117 [node-log 11:18:34 AM] [eqFTP-ftpDomain]: [s.gRR]
Getting remote root for this ID: 0
NodeDebugUtils.js:114 [node-error 11:18:34 AM] [eqFTP-ftpDomain]: [s.gRR]
There's no connection with this ID: 0
NodeDebugUtils.js:114 [node-error 11:18:34 AM] [eqFTP-ftpDomain]: [q.p]
Can't connect to server on connectionID: 0. Queue cleared now.
NodeDebugUtils.js:117 [node-log 11:18:34 AM] [eqFTP-ftpDomain]:
Disconnecting...
main.js:1629 Object {event: "server_disconnecting", connectionID: 0,
clearQueue: true}
NodeDebugUtils.js:117 [node-log 11:18:34 AM] [eqFTP-ftpDomain]:
Disonnected. Actually there was no client so nothing to disconnect.

**Comment by FurmanSK** [comment]
Alright I just closed brackets and reopened it and now it's working. Odd....

**Comment by FurmanSK** [comment]
Since it's working now, should I use the beta version? Or is this the same
version I had 0.7.2 just with more debug options?

Thanks.

**Comment by Equals182** [comment]
There's no differences between beta and release version (except extra console.log lines), so you can do whatever you want to. :)
I hope you won't have any issues with eqFTP any more :)
