### ISSUE TITLE
eqFTP stopped working in Brackets 1.6

### ISSUE THREAD

**Issue by pjb493** [Equals182/eqFTP#199]
Hi, it appears as if Brackets 1.6 has caused the eqFTP extension to stop working. It was working perfectly in 1.5 and stopped working as soon as I updated to 1.6
Is there a fix for this asap? Thanks

**Comment by Equals182** [comment]
Hi. What exactly isn't working? Is it familiar with #198 ?

**Comment by pjb493** [comment]
It looks like the same issues, yes. I don't know how to capture a log though.

**Comment by Equals182** [comment]
Here's how you capture it: http://equals182.github.io/eqFTP/#creating-issue
If issue I sent to is just like yours, let's close this one and continue
there.

**Comment by pjb493** [comment]
it appears to be the same so yeah

**Comment by Equals182** [comment]
Please check it again, looks like its solved
