### ISSUE TITLE
Add version control on uploading [Feature Request]

### ISSUE THREAD

**Issue by FurmanSK** [Equals182/eqFTP#200]
Hi,

Love the plugin but was wondering if it's possible to add a way when using SFTP could you have it create a "backup" or version of the current file up there by renaming it to filename.extension:version# and that way you can back out things you've changed if possible. Kind of like a version control for your files? Just a thought. I do it manually now but having it in the actual program would be nice when on save (CTRL-S) it connects, renames current file to "example.html:2" and uploades the new example.html file.

Thanks,

FurmanSK

**Comment by Equals182** [comment]
### Hello there!

I know this issue been there for a pretty long time, but I have some good news here!
We just released eqFTP v**1.0.0-beta.0** (v1-b for short I guess) and we're completely discontinuing support of all previous versions of this plugin.
New version works great on Brackets 1.8 and it should be good on lower versions too.

So yeah, we're closing and locking this issue forever and looking forward for you to try out our new version of eqFTP.
I'm sorry if I somehow disturbed you, or you lost your interest in eqFTP or Brackets in general, we're not going to make any noise here again.

If you have any questions, please contact me via email (you can find it in [my profile](https://github.com/Equals182)) or [Telegram app](http://t.me/equals182)

Thank you for understanding 😊
