### ISSUE TITLE
Cant download files from my remote server

### ISSUE THREAD

**Issue by 517Design** [Equals182/eqFTP#203]
when I try to download a file i get "Connected to server" then "Disconnected from server" in green boxes underneath eqFTP and nothing downloads or opens in the left sidebar. I can connect to my server just can't download files.

**Comment by Equals182** [comment]
Please, follow these steps to get some logs: `http://equals182.github.io/eqFTP/#creating-issue`

**Comment by Equals182** [comment]
### Hello there!

I know this issue been there for a pretty long time, but I have some good news here!
We just released eqFTP v**1.0.0-beta.0** (v1-b for short I guess) and we're completely discontinuing support of all previous versions of this plugin.
New version works great on Brackets 1.8 and it should be good on lower versions too.

So yeah, we're closing and locking this issue forever and looking forward for you to try out our new version of eqFTP.
I'm sorry if I somehow disturbed you, or you lost your interest in eqFTP or Brackets in general, we're not going to make any noise here again.

If you have any questions, please contact me via email (you can find it in [my profile](https://github.com/Equals182)) or [Telegram app](http://t.me/equals182)

Thank you for understanding 😊
