### ISSUE TITLE
Connection closed by xxx.xxx.xxx.xxx [preauth]

### ISSUE THREAD

**Issue by questions00** [Equals182/eqFTP#204]
the sftp Service wont work with any unix-Server in my environment.
The ssh-Server log this: Connection closed by xxx.xxx.xxx.xxx [preauth]
Here the debug-log:

[node-log 9:17:12 AM] [eqFTP-ftpDomain]: 1870: [q.a] Queuer is NOT ignored, continueing
NodeDebugUtils.js:117 [node-log 9:17:12 AM] [eqFTP-ftpDomain]: 1901: [q.a] Queue updated: {"a":[{"type":"folder","connectionID":0,"path":"","id":"f_1455697032897417","state":"opened","queue":"a"}],"p":[],"f":[],"s":[]}
main.js:1629 Object {event: "queue_update", connectionID: 0, element: Object}connectionID: 0element: ObjectconnectionID: 0id: "f_1455697032897417"path: ""queue: "a"state: "opened"status: "QUEUE_TASK_STATUS_WAITING"type: "folder"**proto**: Object__defineGetter__: function **defineGetter**() { [native code] }arguments: nullcaller: nulllength: 2name: "**defineGetter**"**proto**: function Empty() {}apply: function apply() { [native code] }arguments: nullcaller: nulllength: 2name: "apply"**proto**: function Empty() {}apply: function apply() { [native code] }arguments: nullcaller: nulllength: 2name: "apply"**proto**: function Empty() {}apply: function apply() { [native code] }arguments: nullcaller: nulllength: 2name: "apply"**proto**: function Empty() {}apply: function apply() { [native code] }arguments: nullcaller: nulllength: 2name: "apply"**proto**: function Empty() {}apply: function apply() { [native code] }arguments: nullcaller: nulllength: 2name: "apply"**proto**: function Empty() {}apply: function apply() { [native code] }arguments: nullcaller: nulllength: 2name: "apply"**proto**: function Empty() {}apply: function apply() { [native code] }arguments: nullcaller: nulllength: 2name: "apply"**proto**: function Empty() {}apply: function apply() { [native code] }arguments: nullcaller: nulllength: 2name: "apply"**proto**: function Empty() {}apply: function apply() { [native code] }arguments: nullcaller: nulllength: 2name: "apply"**proto**: function Empty() {}apply: function apply() { [native code] }arguments: nullcaller: nulllength: 2name: "apply"**proto**: function Empty() {}apply: function apply() { [native code] }arguments: nullcaller: nulllength: 2name: "apply"**proto**: function Empty() {}apply: function apply() { [native code] }arguments: nullcaller: nulllength: 2name: "apply"**proto**: function Empty() {}apply: function apply() { [native code] }arguments: nullbind: function bind() { [native code] }call: function call() { [native code] }caller: nullconstructor: function Function() { [native code] }length: 0name: "Empty"toString: function toString() { [native code] }**proto**: Object<function scope><function scope>arguments: nullbind: function bind() { [native code] }call: function call() { [native code] }caller: nullconstructor: function Function() { [native code] }length: 0name: "Empty"toString: function toString() { [native code] }**proto**: Object<function scope><function scope>arguments: nullbind: function bind() { [native code] }call: function call() { [native code] }caller: nullconstructor: function Function() { [native code] }length: 0name: "Empty"toString: function toString() { [native code] }**proto**: Object<function scope><function scope>arguments: nullbind: function bind() { [native code] }call: function call() { [native code] }caller: nullconstructor: function Function() { [native code] }length: 0name: "Empty"toString: function toString() { [native code] }**proto**: Object<function scope><function scope>Global: Windowarguments: nullbind: function bind() { [native code] }call: function call() { [native code] }caller: nullconstructor: function Function() { [native code] }length: 0name: "Empty"toString: function toString() { [native code] }**proto**: Object<function scope><function scope>arguments: nullbind: function bind() { [native code] }call: function call() { [native code] }caller: nullconstructor: function Function() { [native code] }length: 0name: "Empty"toString: function toString() { [native code] }**proto**: Object<function scope><function scope>arguments: nullbind: function bind() { [native code] }call: function call() { [native code] }caller: nullconstructor: function Function() { [native code] }length: 0name: "Empty"toString: function toString() { [native code] }**proto**: Object<function scope><function scope>arguments: nullbind: function bind() { [native code] }call: function call() { [native code] }caller: nullconstructor: function Function() { [native code] }length: 0name: "Empty"toString: function toString() { [native code] }**proto**: Object<function scope><function scope>arguments: nullbind: function bind() { [native code] }call: function call() { [native code] }caller: nullconstructor: function Function() { [native code] }length: 0name: "Empty"toString: function toString() { [native code] }**proto**: Object<function scope><function scope>arguments: nullbind: function bind() { [native code] }call: function call() { [native code] }caller: nullconstructor: function Function() { [native code] }length: 0name: "Empty"toString: function toString() { [native code] }**proto**: Object<function scope><function scope>arguments: nullbind: function bind() { [native code] }call: function call() { [native code] }caller: nullconstructor: function Function() { [native code] }length: 0name: "Empty"toString: function toString() { [native code] }**proto**: Object<function scope><function scope>arguments: nullbind: function bind() { [native code] }call: function call() { [native code] }caller: nullconstructor: function Function() { [native code] }length: 0name: "Empty"toString: function toString() { [native code] }**proto**: Object<function scope><function scope>arguments: nullbind: function bind() { [native code] }call: function call() { [native code] }caller: nullconstructor: function Function() { [native code] }length: 0name: "Empty"toString: function toString() { [native code] }**proto**: Object<function scope><function scope>**defineSetter**: function **defineSetter**() { [native code] }**lookupGetter**: function **lookupGetter**() { [native code] }**lookupSetter**: function **lookupSetter**() { [native code] }constructor: function Object() { [native code] }hasOwnProperty: function hasOwnProperty() { [native code] }isPrototypeOf: function isPrototypeOf() { [native code] }propertyIsEnumerable: function propertyIsEnumerable() { [native code] }toLocaleString: function toLocaleString() { [native code] }toString: function toString() { [native code] }valueOf: function valueOf() { [native code] }get **proto**: function **proto**() { [native code] }set **proto**: function **proto**() { [native code] }event: "queue_update"**proto**: Object
main.js:1629 Object {event: "working", work: true}
main.js:1629 Object {event: "queue_update", connectionID: 0, element: Object}connectionID: 0element: Objectevent: "queue_update"**proto**: Object__defineGetter__: function **defineGetter**() { [native code] }arguments: nullcaller: nulllength: 2name: "**defineGetter**"**proto**: function Empty() {}apply: function apply() { [native code] }arguments: nullcaller: nulllength: 2name: "apply"**proto**: function Empty() {}apply: function apply() { [native code] }arguments: nullcaller: nulllength: 2name: "apply"**proto**: function Empty() {}apply: function apply() { [native code] }arguments: nullbind: function bind() { [native code] }call: function call() { [native code] }caller: nullconstructor: function Function() { [native code] }length: 0name: "Empty"toString: function toString() { [native code] }**proto**: Object<function scope><function scope>arguments: nullbind: function bind() { [native code] }call: function call() { [native code] }caller: nullconstructor: function Function() { [native code] }length: 0name: "Empty"toString: function toString() { [native code] }**proto**: Object<function scope><function scope>arguments: nullbind: function bind() { [native code] }call: function call() { [native code] }caller: nullconstructor: function Function() { [native code] }length: 0name: "Empty"toString: function toString() { [native code] }**proto**: Object<function scope><function scope>**defineSetter**: function **defineSetter**() { [native code] }**lookupGetter**: function **lookupGetter**() { [native code] }**lookupSetter**: function **lookupSetter**() { [native code] }constructor: function Object() { [native code] }hasOwnProperty: function hasOwnProperty() { [native code] }isPrototypeOf: function isPrototypeOf() { [native code] }propertyIsEnumerable: function propertyIsEnumerable() { [native code] }toLocaleString: function toLocaleString() { [native code] }toString: function toString() { [native code] }valueOf: function valueOf() { [native code] }get **proto**: function **proto**() { [native code] }set **proto**: function **proto**() { [native code] }
NodeDebugUtils.js:117 [node-log 9:17:12 AM] [eqFTP-ftpDomain]: Connecting to this ID: 0
main.js:1629 Object {event: "server_connecting", connectionID: 0}
NodeDebugUtils.js:117 [node-log 9:17:12 AM] [eqFTP-ftpDomain]: Connecting...
NodeDebugUtils.js:117 [node-log 9:17:13 AM] [eqFTP-ftpDomain]: [s.l][SFTP-error] {"level":"authentication","partial":false}
NodeDebugUtils.js:117 [node-log 9:17:13 AM] [eqFTP-ftpDomain]: Disconnecting...
main.js:1629 Object {event: "server_disconnecting", connectionID: 0}
2NodeDebugUtils.js:117 [node-log 9:17:13 AM] [eqFTP-ftpDomain]: [c.c] ftpDomain currently disconnecting from: 0
NodeDebugUtils.js:117 [node-log 9:17:13 AM] [eqFTP-ftpDomain]: Disonnected.
NodeDebugUtils.js:117 [node-log 9:17:13 AM] [eqFTP-ftpDomain]: Connecting to this ID: 0
NodeDebugUtils.js:117 [node-log 9:17:13 AM] [eqFTP-ftpDomain]: Connecting...
main.js:1629 Object {event: "server_disconnect", connectionID: 0}
main.js:1629 Object {event: "server_connecting", connectionID: 0}
NodeDebugUtils.js:114 [node-error 9:17:13 AM] [eqFTP-ftpDomain]: 321: [c.cC] Can't create sftp Client for ID: 0. Error: {"level":"authentication","partial":false}NodeDebugUtils.js:114 handleLogEvent/utils/EventDispatcher.js:233 trigger/utils/EventDispatcher.js:271 triggerWithArray/utils/NodeConnection.js:479 NodeConnection._receive
NodeDebugUtils.js:114 [node-error 9:17:13 AM] [eqFTP-ftpDomain]: [q.p] Can't connect to server on connectionID: 0. Queue cleared now.NodeDebugUtils.js:114 handleLogEvent/utils/EventDispatcher.js:233 trigger/utils/EventDispatcher.js:271 triggerWithArray/utils/NodeConnection.js:479 NodeConnection._receive
NodeDebugUtils.js:117 [node-log 9:17:13 AM] [eqFTP-ftpDomain]: Disconnecting...
2NodeDebugUtils.js:117 [node-log 9:17:13 AM] [eqFTP-ftpDomain]: [c.c] ftpDomain currently disconnecting from: 0
NodeDebugUtils.js:117 [node-log 9:17:13 AM] [eqFTP-ftpDomain]: Disonnected.
main.js:1629 Object {event: "server_disconnecting", connectionID: 0, clearQueue: true}
main.js:1629 Object {event: "server_disconnect", connectionID: 0, clearQueue: true}

**Comment by questions00** [comment]
the eqFTP Version is 0.7.2

**Comment by Equals182** [comment]
### Hello there!

I know this issue been there for a pretty long time, but I have some good news here!
We just released eqFTP v**1.0.0-beta.0** (v1-b for short I guess) and we're completely discontinuing support of all previous versions of this plugin.
New version works great on Brackets 1.8 and it should be good on lower versions too.

So yeah, we're closing and locking this issue forever and looking forward for you to try out our new version of eqFTP.
I'm sorry if I somehow disturbed you, or you lost your interest in eqFTP or Brackets in general, we're not going to make any noise here again.

If you have any questions, please contact me via email (you can find it in [my profile](https://github.com/Equals182)) or [Telegram app](http://t.me/equals182)

Thank you for understanding 😊
