### ISSUE TITLE
Can't add file to queue

### ISSUE THREAD

**Issue by paolobasso99** [Equals182/eqFTP#207]
When I try to add a file on queue or upload it using RIGHT-CLICK then "upload" or "add to queue" nothing append.
FTP fields are correct and the connection with the server is established.
What can i do?

**Comment by Equals182** [comment]
Please, attach some logs. Follow [these](http://equals182.github.io/eqFTP/#creating-issue) steps to do so.

**Comment by paolobasso99** [comment]
[eqFTP] Uploding directory. There's no connectionID.
NodeDebugUtils.js:117 [node-log 7:21:10 PM] [eqFTP-ftpDomain]: [c.c] Connection already exists for this ID: 0
NodeDebugUtils.js:117 [node-log 7:21:10 PM] DEBUG:  user_command
NodeDebugUtils.js:117 [node-log 7:21:10 PM] "NOOP"
NodeDebugUtils.js:117 [node-log 7:21:10 PM] DEBUG:  server_response
NodeDebugUtils.js:117 [node-log 7:21:10 PM] {
  "code": 200,
  "text": "200 NOOP ok.",
  "isMark": false,
  "isError": false
}

**Comment by Equals182** [comment]
### Hello there!

I know this issue been there for a pretty long time, but I have some good news here!
We just released eqFTP v**1.0.0-beta.0** (v1-b for short I guess) and we're completely discontinuing support of all previous versions of this plugin.
New version works great on Brackets 1.8 and it should be good on lower versions too.

So yeah, we're closing and locking this issue forever and looking forward for you to try out our new version of eqFTP.
I'm sorry if I somehow disturbed you, or you lost your interest in eqFTP or Brackets in general, we're not going to make any noise here again.

If you have any questions, please contact me via email (you can find it in [my profile](https://github.com/Equals182)) or [Telegram app](http://t.me/equals182)

Thank you for understanding 😊
