### ISSUE TITLE
Upload not working, sometime

### ISSUE THREAD

**Issue by vinnygambiny** [Equals182/eqFTP#211]
Sometime, CTRL+S is upload my file fine. But after a few upload, it's stop. Reload Brackets needed.

After reload, I need to select the server of my project manually, then CTR+S, the file is uploaded. If I don't select manually, the file is not uploaded.

`[eqFTP] Loaded (v0.7.2)
NodeDebugUtils.js:117 [node-log 9:38:45 AM] [eqFTP-ftpDomain]: Adding connections.
NodeDebugUtils.js:117 [node-log 9:38:45 AM] [eqFTP-ftpDomain]: 136: Checking connection ID: 3
NodeDebugUtils.js:117 [node-log 9:38:45 AM] [eqFTP-ftpDomain]: 147: Getting existent connection by ID, result: undefined
NodeDebugUtils.js:117 [node-log 9:38:45 AM] [eqFTP-ftpDomain]: 173: Adding new connection: "....*****...."
NodeDebugUtils.js:117 [node-log 9:38:45 AM] [eqFTP-ftpDomain]: 136: Checking connection ID: 0
NodeDebugUtils.js:117 [node-log 9:38:45 AM] [eqFTP-ftpDomain]: 147: Getting existent connection by ID, result: undefined
NodeDebugUtils.js:117 [node-log 9:38:45 AM] [eqFTP-ftpDomain]: 173: Adding new connection: "......****...."
NodeDebugUtils.js:117 [node-log 9:38:45 AM] [eqFTP-ftpDomain]: 136: Checking connection ID: 4
NodeDebugUtils.js:117 [node-log 9:38:45 AM] [eqFTP-ftpDomain]: 147: Getting existent connection by ID, result: undefined
NodeDebugUtils.js:117 [node-log 9:38:45 AM] [eqFTP-ftpDomain]: 173: Adding new connection: ".....****....."
NodeDebugUtils.js:117 [node-log 9:38:45 AM] [eqFTP-ftpDomain]: 136: Checking connection ID: 1
NodeDebugUtils.js:117 [node-log 9:38:45 AM] [eqFTP-ftpDomain]: 147: Getting existent connection by ID, result: undefined
NodeDebugUtils.js:117 [node-log 9:38:45 AM] [eqFTP-ftpDomain]: 173: Adding new connection: ".......******....."
NodeDebugUtils.js:117 [node-log 9:38:45 AM] [eqFTP-ftpDomain]: 136: Checking connection ID: 2
NodeDebugUtils.js:117 [node-log 9:38:45 AM] [eqFTP-ftpDomain]: 147: Getting existent connection by ID, result: undefined
NodeDebugUtils.js:117 [node-log 9:38:45 AM] [eqFTP-ftpDomain]: 173: Adding new connection: "......*****....."
NodeDebugUtils.js:117 [node-log 9:38:45 AM] [eqFTP-ftpDomain]: [s.d.i.cs] Checking for ignoring.
NodeDebugUtils.js:117 [node-log 9:38:45 AM] [eqFTP-ftpDomain]: 1870: [q.a] Queuer is NOT ignored, continueing
NodeDebugUtils.js:117 [node-log 9:38:45 AM] [eqFTP-ftpDomain]: 1901: [q.a] Queue updated: {"a":[{"localPath":"C:/............./app.component.js","remotePath":"/app/app.component.js","name":"app.component.js","direction":"upload","queue":"a","type":"file","connectionID":4,"after":"disconnect","id":"f_1457447925654743"}],"p":[],"f":[],"s":[]}
main.js:1629 Object {event: "queue_update", connectionID: 4, element: Object}
main.js:1629 Object {event: "working", work: true}
main.js:1629 Object {event: "queue_update", connectionID: 4, element: Object}
NodeDebugUtils.js:117 [node-log 9:38:45 AM] [eqFTP-ftpDomain]: Connecting to this ID: 4
main.js:1629 Object {event: "server_connecting", connectionID: 4}
NodeDebugUtils.js:117 [node-log 9:38:45 AM] [eqFTP-ftpDomain]: Connecting...
NodeDebugUtils.js:117 [node-log 9:38:45 AM] [eqFTP-ftpDomain]: Adding connections.
NodeDebugUtils.js:117 [node-log 9:38:45 AM] [eqFTP-ftpDomain]: 136: Checking connection ID: 3
NodeDebugUtils.js:117 [node-log 9:38:45 AM] [eqFTP-ftpDomain]: 147: Getting existent connection by ID, result: ".......*****......"
NodeDebugUtils.js:117 [node-log 9:38:45 AM] [eqFTP-ftpDomain]: 150: Checking if creditials are not same
NodeDebugUtils.js:117 [node-log 9:38:45 AM] [eqFTP-ftpDomain]: 136: Checking connection ID: 0
NodeDebugUtils.js:117 [node-log 9:38:45 AM] [eqFTP-ftpDomain]: 147: Getting existent connection by ID, result: ".....******......"
NodeDebugUtils.js:117 [node-log 9:38:45 AM] [eqFTP-ftpDomain]: 150: Checking if creditials are not same
NodeDebugUtils.js:117 [node-log 9:38:45 AM] [eqFTP-ftpDomain]: 136: Checking connection ID: 4
NodeDebugUtils.js:117 [node-log 9:38:45 AM] [eqFTP-ftpDomain]: 147: Getting existent connection by ID, result: "......******......"
NodeDebugUtils.js:117 [node-log 9:38:45 AM] [eqFTP-ftpDomain]: 150: Checking if creditials are not same
NodeDebugUtils.js:117 [node-log 9:38:45 AM] [eqFTP-ftpDomain]: 136: Checking connection ID: 1
NodeDebugUtils.js:117 [node-log 9:38:45 AM] [eqFTP-ftpDomain]: 147: Getting existent connection by ID, result: ".........********......."
NodeDebugUtils.js:117 [node-log 9:38:45 AM] [eqFTP-ftpDomain]: 150: Checking if creditials are not same
NodeDebugUtils.js:117 [node-log 9:38:45 AM] [eqFTP-ftpDomain]: 136: Checking connection ID: 2
NodeDebugUtils.js:117 [node-log 9:38:45 AM] [eqFTP-ftpDomain]: 147: Getting existent connection by ID, result: ".......********......."
NodeDebugUtils.js:117 [node-log 9:38:45 AM] [eqFTP-ftpDomain]: 150: Checking if creditials are not same
main.js:1629 Object {event: "server_connect", connectionID: 4}
NodeDebugUtils.js:117 [node-log 9:38:45 AM] [eqFTP-ftpDomain]: Connected...
NodeDebugUtils.js:114 [node-error 9:38:45 AM] [Launcher] uncaught exception at top level, exiting. TypeError: Cannot call method 'auth' of undefined
    at Object._commands.service.auth (C:\........\AppData\Roaming\Brackets\extensions\user\equals182.eqftp\node\ftpDomain.js:793:84)
    at Object._commands.connection.createClient.callback (C:\........\AppData\Roaming\Brackets\extensions\user\equals182.eqftp\node\ftpDomain.js:386:59)
    at eqFTPconnections.(anonymous function).listeners.connect (C:\......\AppData\Roaming\Brackets\extensions\user\equals182.eqftp\node\ftpDomain.js:738:44)
    at EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (C:\......\AppData\Roaming\Brackets\extensions\user\equals182.eqftp\node\node_modules\jsftp\lib\jsftp.js:91:14)
    at Socket.EventEmitter.emit (events.js:117:20)
    at Object.afterConnect [as oncomplete] (net.js:883:10)NodeDebugUtils.js:114 handleLogEvent/utils/EventDispatcher.js:233 trigger/utils/EventDispatcher.js:271 triggerWithArray/utils/NodeConnection.js:479 NodeConnection._receive
NodeDebugUtils.js:114 [node-info 9:38:45 AM] [Server] stopping
/filesystem/FileSystem.js:959 File watchers went offline!
/utils/EventDispatcher.js:235 Exception in 'change' listener on FileSystem {_index: FileIndex, _watchedRoots: Object, _watchRequests: Array[1], _externalChanges: Array[0], _impl: Object…} TypeError: Cannot read property 'isDirectory' of null TypeError: Cannot read property 'isDirectory' of null
    at _fsChangeHandler (file:///......./AppData/Roaming/Brackets/extensions/user/growlscript.brackets.classcompletion/CacheManager.js:340:19)
    at FileSystem.trigger (/utils/EventDispatcher.js:233:40)
    at FileSystem._fireChangeEvent (/filesystem/FileSystem.js:703:14)
    at FileSystem._handleExternalChange (/filesystem/FileSystem.js:809:18)
    at FileSystem._unwatchAll (/filesystem/FileSystem.js:973:14)
    at eval (/filesystem/impls/appshell/AppshellFileSystem.js:75:13)
    at NodeConnection.trigger (/utils/EventDispatcher.js:233:40)
    at WebSocket.self._ws.onclose (/utils/NodeConnection.js:267:30)
/utils/EventDispatcher.js:236 Assertion failed:/utils/EventDispatcher.js:236 trigger/filesystem/FileSystem.js:703 FileSystem._fireChangeEvent/filesystem/FileSystem.js:809 FileSystem._handleExternalChange/filesystem/FileSystem.js:973 FileSystem._unwatchAll/filesystem/impls/appshell/AppshellFileSystem.js:75 (anonymous function)/utils/EventDispatcher.js:233 trigger/utils/NodeConnection.js:267 self._ws.onclose
/utils/NodeConnection.js:89 WebSocket connection to 'ws://localhost:57779/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
/filesystem/FileSystem.js:967 Watching disabled for C:/.............../
10/utils/NodeConnection.js:89 WebSocket connection to 'ws://localhost:57779/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
NodeDebugUtils.js:117 [node-log 9:38:58 AM] [eqFTP-ftpDomain] Loaded`

**Comment by Equals182** [comment]
### Hello there!

I know this issue been there for a pretty long time, but I have some good news here!
We just released eqFTP v**1.0.0-beta.0** (v1-b for short I guess) and we're completely discontinuing support of all previous versions of this plugin.
New version works great on Brackets 1.8 and it should be good on lower versions too.

So yeah, we're closing and locking this issue forever and looking forward for you to try out our new version of eqFTP.
I'm sorry if I somehow disturbed you, or you lost your interest in eqFTP or Brackets in general, we're not going to make any noise here again.

If you have any questions, please contact me via email (you can find it in [my profile](https://github.com/Equals182)) or [Telegram app](http://t.me/equals182)

Thank you for understanding 😊
