### ISSUE TITLE
Can't connect to remote host on port 222 (SFTP)

### ISSUE THREAD

**Issue by charlesmigrino** [Equals182/eqFTP#212]
I'm having a problem connecting on this particular remote server. The connection I am using is on SFTP. Other servers are working fine. Could a difference of port be causing the issue? This server uses the port 222 instead of the standard 22. I can confirm that there is an issue because other SFTP plugins can access it. Here is the debug log I got:

>  [node-log 10:24:23 PM] [eqFTP-ftpDomain]: Connecting to this ID: 1
> main.js:1629 Object {event: "server_connecting", connectionID: 1}
> NodeDebugUtils.js:117 [node-log 10:24:23 PM] [eqFTP-ftpDomain]: Connecting...
> ErrorNotification.js:125 [node-error 10:24:23 PM] [eqFTP-ftpDomain]: 321: [c.cC] Can't create sftp Client for ID: 1. Error: {"level":"connection-timeout"}
> ErrorNotification.js:125 [node-error 10:24:23 PM] [eqFTP-ftpDomain]: [q.p] Can't connect to server on connectionID: 1. Queue cleared now.
> NodeDebugUtils.js:117 [node-log 10:24:23 PM] [eqFTP-ftpDomain]: Disconnecting...
> main.js:1629 Object {event: "server_disconnecting", connectionID: 1, clearQueue: true}
> 2NodeDebugUtils.js:117 [node-log 10:24:23 PM] [eqFTP-ftpDomain]: [c.c] ftpDomain currently disconnecting from: 1
> NodeDebugUtils.js:117 [node-log 10:24:23 PM] [eqFTP-ftpDomain]: Disonnected.
> main.js:1629 Object {event: "server_disconnect", connectionID: 1, clearQueue: true}

**Comment by charlesmigrino** [comment]
To add further details, it just pops "Disconnected" when I try to start browsing the server. And yes, I have triple-checked the connection settings.
![disconnect](https://cloud.githubusercontent.com/assets/17745635/13638460/5dab3462-e647-11e5-9739-464f93ac8afe.jpg)

**Comment by carinlynchin** [comment]
where are the log files?

**Comment by Equals182** [comment]
You can see logs in Brackets Console
Follow steps 2-4 here: http://equals182.github.io/eqFTP/#creating-issue

**Comment by Equals182** [comment]
### Hello there!

I know this issue been there for a pretty long time, but I have some good news here!
We just released eqFTP v**1.0.0-beta.0** (v1-b for short I guess) and we're completely discontinuing support of all previous versions of this plugin.
New version works great on Brackets 1.8 and it should be good on lower versions too.

So yeah, we're closing and locking this issue forever and looking forward for you to try out our new version of eqFTP.
I'm sorry if I somehow disturbed you, or you lost your interest in eqFTP or Brackets in general, we're not going to make any noise here again.

If you have any questions, please contact me via email (you can find it in [my profile](https://github.com/Equals182)) or [Telegram app](http://t.me/equals182)

Thank you for understanding 😊
