### ISSUE TITLE
"Local Path" doesn't let me assign not mounted samba shared folders

### ISSUE THREAD

**Issue by RafaelLinux** [Equals182/eqFTP#214]
I'm in trouble with eqFTP. I have all local files of my projects in a samba shared folder. That folder is not mounted (I'm using Linux) but I can access without problems using "smb://webhost/root_site_folder". However, if I put that path in "Local path" and download some file from my FTP server, eqFTP create a new folder called "smb:" in my $HOME path, instead of downloading it to "smb://webhost/root_site_folder".

Please, is there any way to solve this issue?

Thank you

**Comment by Equals182** [comment]
Hi

eqFTP as well as Brackets uses **fs** (File System) api of Node.js. I'm not sure if it's able to work with "smb://..." links. Need to google for solution or workaround, I guess.

**Comment by RafaelLinux** [comment]
Thank you for your reply. Sadly, I'm an user, not a programmer, so I found some information about node.js and "samba" shared folders, but I have no idea about how to "join" this solution with Brackets  :(

http://stackoverflow.com/questions/9689791/copy-files-from-samba-share-in-node-js

**Comment by Equals182** [comment]
### Hello there!

I know this issue been there for a pretty long time, but I have some good news here!
We just released eqFTP v**1.0.0-beta.0** (v1-b for short I guess) and we're completely discontinuing support of all previous versions of this plugin.
New version works great on Brackets 1.8 and it should be good on lower versions too.

So yeah, we're closing and locking this issue forever and looking forward for you to try out our new version of eqFTP.
I'm sorry if I somehow disturbed you, or you lost your interest in eqFTP or Brackets in general, we're not going to make any noise here again.

If you have any questions, please contact me via email (you can find it in [my profile](https://github.com/Equals182)) or [Telegram app](http://t.me/equals182)

Thank you for understanding 😊
