### ISSUE TITLE
Error when I went to upload a file.. 

### ISSUE THREAD

**Issue by ajota** [Equals182/eqFTP#215]
![erroreqftp](https://cloud.githubusercontent.com/assets/4956046/14323290/92cfa1ec-fbe5-11e5-8225-630b74c96e1c.PNG)

**Comment by ajota** [comment]
I have added this "escape()" to the file location "from" on line 2037  and it worked for me...
I hope.. this can help you. :)

**Comment by Equals182** [comment]
Will do. Thanks for help, man. Glad you figured it out yourself.
