### ISSUE TITLE
settings or connections pop up freezing up bracket

### ISSUE THREAD

**Issue by carinlynchin** [Equals182/eqFTP#216]
I was trying to edit the connections list and the dark mask shows up but no pop up and then I can't do anything with brackets and have to do a force close. See pic
<img width="1440" alt="screen shot 2016-05-05 at 12 06 21 pm" src="https://cloud.githubusercontent.com/assets/1210918/15048958/cd85d85c-12b9-11e6-8514-c7d45cb188cf.png">

**Comment by Mootly** [comment]
Doing the same on Windows for me, so not an OS specific problem.

**Comment by carinlynchin** [comment]
thanks. Also do you know where the logs are? i can't connect to a specific server....but a different domain works fine...i looked over all the settings so i was hoping the log might tell me whats up

**Comment by carinlynchin** [comment]
omg that was totally it. I will let the brackets compare guy know about it. 
he had just release one that fixed some bugs so I'll share that...thats crazy that its the reason why. How did you find that out?

**Comment by Mootly** [comment]
How did I find it? Walked through the modules, found the one that went *boom*. Tested everything else I had installed one by one. It was the only one that made it go *boom*.

Didn't dig cuz I was just reviewing a few editors for something for easy remote editing to give to non-techies who sometimes needed to tweak a live document.

**Comment by carinlynchin** [comment]
cool

**Comment by Equals182** [comment]
### Hello there!

I know this issue been there for a pretty long time, but I have some good news here!
We just released eqFTP v**1.0.0-beta.0** (v1-b for short I guess) and we're completely discontinuing support of all previous versions of this plugin.
New version works great on Brackets 1.8 and it should be good on lower versions too.

So yeah, we're closing and locking this issue forever and looking forward for you to try out our new version of eqFTP.
I'm sorry if I somehow disturbed you, or you lost your interest in eqFTP or Brackets in general, we're not going to make any noise here again.

If you have any questions, please contact me via email (you can find it in [my profile](https://github.com/Equals182)) or [Telegram app](http://t.me/equals182)

Thank you for understanding 😊
