### ISSUE TITLE
When I open setting option

### ISSUE THREAD

**Issue by Randore** [Equals182/eqFTP#220]
This is what i see, then I have to forcefully close the brackets to get started freshly.

http://prntscr.com/b5stn2

**Comment by carinlynchin** [comment]
sucks but I am going to have to use another ftp options. I need to be able to add a new connection but can't because it freezes up so much I have to force-quit brackets

**Comment by kleninb** [comment]
@carinlynchin : Hey try the "SFtpUpload" it's works like a charm. I used it for my previous project.

**Comment by carinlynchin** [comment]
thanks @kleninb

**Comment by YasiOnFire** [comment]
If You are using Custom CSS Injector use this to fix this issue:
```
#eqFTP-project-settings {
    visibility: visible;
}
```

**Comment by Equals182** [comment]
If this is an actual fix,
You can just edit css file for eqftp. 
Open Brackets, click Help in menu, click Show Extensions Folder, go to user->equals182.eqftp->styles and change eqFTP-styles.css

**Comment by carinlynchin** [comment]
actually turns out I found another solution ...removing brackets compare plugin...its back now. I guess he has something in there that is conflicting with it somehow.

**Comment by Equals182** [comment]
### Hello there!

I know this issue been there for a pretty long time, but I have some good news here!
We just released eqFTP v**1.0.0-beta.0** (v1-b for short I guess) and we're completely discontinuing support of all previous versions of this plugin.
New version works great on Brackets 1.8 and it should be good on lower versions too.

So yeah, we're closing and locking this issue forever and looking forward for you to try out our new version of eqFTP.
I'm sorry if I somehow disturbed you, or you lost your interest in eqFTP or Brackets in general, we're not going to make any noise here again.

If you have any questions, please contact me via email (you can find it in [my profile](https://github.com/Equals182)) or [Telegram app](http://t.me/equals182)

Thank you for understanding 😊
