### ISSUE TITLE
Won't Load on Icon Click on Windows

### ISSUE THREAD

**Issue by stevematthewroberts** [Equals182/eqFTP#225]
Currently the Icon won't click, display only on Windows however works on OSX.
Not sure the issue but this is with no other plugins installed on a fresh install with no extensions.

This is the latest version, other versions for me won't connect.

**Comment by TekaProd** [comment]
I have the same issue.

**Comment by 33Jake** [comment]
I'm getting the same issue running Windows 10... no problem on OSX or Windows 7.

I removed the extension and did a fresh install, after which I was able to open via icon click. However after closing and reopening Brackets, I am unable to open via icon click.

Is there a way to open project settings and whatnot without the icon?

**Comment by Equals182** [comment]
### Hello there!

I know this issue been there for a pretty long time, but I have some good news here!
We just released eqFTP v**1.0.0-beta.0** (v1-b for short I guess) and we're completely discontinuing support of all previous versions of this plugin.
New version works great on Brackets 1.8 and it should be good on lower versions too.

So yeah, we're closing and locking this issue forever and looking forward for you to try out our new version of eqFTP.
I'm sorry if I somehow disturbed you, or you lost your interest in eqFTP or Brackets in general, we're not going to make any noise here again.

If you have any questions, please contact me via email (you can find it in [my profile](https://github.com/Equals182)) or [Telegram app](http://t.me/equals182)

Thank you for understanding 😊
