### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by AGDesignStudio** [Equals182/eqFTP#226]
![ftp](https://cloud.githubusercontent.com/assets/6169614/16522123/99e664a6-3f93-11e6-9815-3512deb05931.PNG)

When I click the icon the screen dims and nothing happens... I am unable to setup new FTP, I have downgraded Brackets to see if that was the issue but still having issues.

Aaron

**Comment by Equals182** [comment]
Is it similar to #220 ?

**Comment by AGDesignStudio** [comment]
That fixed the issue. Thanks dude :)
