### ISSUE TITLE
Not work if project deeper then opened folder in Brackets

### ISSUE THREAD

**Issue by VitaliyAT** [Equals182/eqFTP#228]
I have
![screenshot 17](https://cloud.githubusercontent.com/assets/1639608/16981680/1ad51b0c-4e85-11e6-990e-f99165f79628.jpg)
My project that I want to upload placed inside **_dist_** folder. **dist == /** on ftp site, but I work with source code of bootstrap (some files in **_dist_** folders compile by Grunt), that's why I need work from **_bootstrap-3.3.6_** folder.
Source and Grunt compile me **_dist_**. I add something in **_dist_** and need upload it like root folder to FTP.
My options say that way of project is so:
![screenshot 18](https://cloud.githubusercontent.com/assets/1639608/16981760/8589d30c-4e85-11e6-98d9-6f208db2405d.jpg)
I need upload _index.html_ (for example) - no reaction at all. No errors, no uploads, nothing.
If I change way so:
![screenshot 19](https://cloud.githubusercontent.com/assets/1639608/16981804/c7f4749a-4e85-11e6-9a11-e5543b1fd83a.jpg)
it uploaded, but of course with wrong structure: eqFTP create folder **_dist_** and put _index.html_ in it.

**Comment by VitaliyAT** [comment]
Не выгружаются файлы ниже открытой папки в Brakets.

У меня ледующая картина
Мой проект находится внутри папки dist. Содержимое папки это и есть выгружаемый скомпилированный сайт. Работаю с исходниками бутсрапа, Тоесть Грунт следит за изменениями, производимые мной изменения происходят в исходниках. А сам сайт формируется в папке dist - часть относящаяся к бутсрапу. Созданные мной и исправляемые файлы в папке dist тоже присутствуют. 

В соответствии с этой задумкой я настраиваю соединение:

Например мне надо выгрузить index.html, но никакой реакции нет, ни ошибок в консоли, ничего, молчок, но по факту ничего не выгрузилось. Без разницы руками я пушу выгрузку или автоматом срабатывает после сохранения. Но если я меняю настройки на уровень выше - такой же как у открытой папки (как у всего проекта включая некомпилированные исходники бустрапа):

всё выгружается, но, соответственно, не так как мне надо, создаётся dist и в нём уже index.html.

**Comment by Equals182** [comment]
### Hello there!

I know this issue been there for a pretty long time, but I have some good news here!
We just released eqFTP v**1.0.0-beta.0** (v1-b for short I guess) and we're completely discontinuing support of all previous versions of this plugin.
New version works great on Brackets 1.8 and it should be good on lower versions too.

So yeah, we're closing and locking this issue forever and looking forward for you to try out our new version of eqFTP.
I'm sorry if I somehow disturbed you, or you lost your interest in eqFTP or Brackets in general, we're not going to make any noise here again.

If you have any questions, please contact me via email (you can find it in [my profile](https://github.com/Equals182)) or [Telegram app](http://t.me/equals182)

Thank you for understanding 😊
