### ISSUE TITLE
Can't upload but connection is ok

### ISSUE THREAD

**Issue by VitaliyAT** [Equals182/eqFTP#229]
Нормально соединяется с ФТП. Всё видно - файлы, каталоги, даже папки и файлы создаются, но как только делаешь Upload to FTP - связь обрывается и "я не я... и логин и пароль тоже не мои" поёт. Связь падает. Ну всё на скринах. В консоли потом пишет малопонятное сообщение о невозможности авторизации.

Connection with FTP is normal. All folders and files that on server are shown. But when I try upload something - it's ERROR (Can't authorize on connectionID: 0) (by the way, popup message and message in console are different)
![screenshot 24](https://cloud.githubusercontent.com/assets/1639608/17055884/3b8b4646-5029-11e6-919f-8a988bcdffad.jpg)
![screenshot 25](https://cloud.githubusercontent.com/assets/1639608/17055888/3e8dacb2-5029-11e6-89aa-7f7e306b0b7b.jpg)

**Comment by ramal-ratne** [comment]
Looks like the upload path is set incorrectly..


`[node-log 2:08:59 AM] [eqFTP-ftpDomain]: [c.c] Connection already exists for this ID: 0
NodeDebugUtils.js:117 [node-log 2:08:59 AM] [eqFTP-ftpDomain]: Trying to upload file. Local path: C:/Users/rajitha/Documents/eqFTP Projects/nest-ns1/usr/local/forest/keeper/website/src/app/core/core.module.js Remote path: /C:/Users/rajitha/Documents/eqFTP Projects/nest-ns1/usr/local/forest/keeper/website/src/app/core/core.module.js
3NodeDebugUtils.js:117 [node-log 2:08:59 AM] [eqFTP-ftpDomain]: [c.c] Connection already exists for this ID: 0
2NodeDebugUtils.js:117 [node-log 2:09:00 AM] [eqFTP-ftpDomain]: [c.c] Connection already exists for this ID: 0
NodeDebugUtils.js:114 [node-error 2:09:05 AM] [eqFTP-ftpDomain]: 2220: /C:/Users/rajitha/Documents/eqFTP Projects/nest-ns1/usr/local/forest/keeper/website/src/app/core/core.module.js: There was an error uploading the file.handleLogEvent @ NodeDebugUtils.js:114
NodeDebugUtils.js:114 [node-error 2:09:05 AM] [eqFTP-ftpDomain]: 2221: [f.u][SFTP-error] {"lang":""}handleLogEvent @ NodeDebugUtils.js:114
main.js:1629 Objectelement: Objectevent: "upload_error"__proto__: Object
NodeDebugUtils.js:117 [node-log 2:09:05 AM] [eqFTP-ftpDomain]: [q.m] Moving in queue with params: {"connectionID":0,"from":"a","to":"f","files":[{"localPath":"C:/Users/rajitha/Documents/eqFTP Projects/nest-ns1/usr/local/forest/keeper/website/src/app/core/core.module.js","remotePath":"/C:/Users/rajitha/Documents/eqFTP Projects/nest-ns1/usr/local/forest/keeper/website/src/app/core/core.module.js","name":"core.module.js","direction":"upload","queue":"a","type":"file","connectionID":0,"id":"f_1469894939950549","ftpDomain":{"diff":{"check":false,"action":false}},"aRemotePath":"/C:/Users/rajitha/Documents/eqFTP Projects/nest-ns1/usr/local/forest/keeper/website/src/app/core/core.module.js","stats":{"dev":0,"mode":33206,"nlink":1,"uid":0,"gid":0,"rdev":0,"ino":0,"size":400,"atime":"2016-07-30T14:35:03.000Z","mtime":"2016-07-30T14:35:03.000Z","ctime":"2016-07-30T14:35:03.000Z"}}]}
main.js:1629 Object
main.js:1629 Object
NodeDebugUtils.js:117 [node-log 2:09:05 AM] [eqFTP-ftpDomain]: [q.p] Queue is empty
NodeDebugUtils.js:117 [node-log 2:09:05 AM] [eqFTP-ftpDomain]: Disconnecting...
main.js:1629 Object
2NodeDebugUtils.js:117 [node-log 2:09:05 AM] [eqFTP-ftpDomain]: [c.c] ftpDomain currently disconnecting from: 0
NodeDebugUtils.js:117 [node-log 2:09:05 AM] [eqFTP-ftpDomain]: Disonnected.
main.js:1629 Object`

**Comment by Equals182** [comment]
### Hello there!

I know this issue been there for a pretty long time, but I have some good news here!
We just released eqFTP v**1.0.0-beta.0** (v1-b for short I guess) and we're completely discontinuing support of all previous versions of this plugin.
New version works great on Brackets 1.8 and it should be good on lower versions too.

So yeah, we're closing and locking this issue forever and looking forward for you to try out our new version of eqFTP.
I'm sorry if I somehow disturbed you, or you lost your interest in eqFTP or Brackets in general, we're not going to make any noise here again.

If you have any questions, please contact me via email (you can find it in [my profile](https://github.com/Equals182)) or [Telegram app](http://t.me/equals182)

Thank you for understanding 😊
