### ISSUE TITLE
eqFTP folder doesn't open up

### ISSUE THREAD

**Issue by sancocho28** [Equals182/eqFTP#233]
I had eqFTP-0.6.2 installed and working.  I upgraded to the new version and nothing happens when i click on the eqFTP folder on the right to view the settings of my ftp server.  I can click on the eqFTPQueue link on the status bar with no problem.

I'm using Brackets 1.7 build 1.7.0-16898

**Comment by pawelsas** [comment]
Same here.

**Comment by dimmsan** [comment]
Same
Wait for fix

**Comment by Equals182** [comment]
### Hello there!

I know this issue been there for a pretty long time, but I have some good news here!
We just released eqFTP v**1.0.0-beta.0** (v1-b for short I guess) and we're completely discontinuing support of all previous versions of this plugin.
New version works great on Brackets 1.8 and it should be good on lower versions too.

So yeah, we're closing and locking this issue forever and looking forward for you to try out our new version of eqFTP.
I'm sorry if I somehow disturbed you, or you lost your interest in eqFTP or Brackets in general, we're not going to make any noise here again.

If you have any questions, please contact me via email (you can find it in [my profile](https://github.com/Equals182)) or [Telegram app](http://t.me/equals182)

Thank you for understanding 😊
