### ISSUE TITLE
FTP connections folders [Feature Request]

### ISSUE THREAD

**Issue by tonoslav** [Equals182/eqFTP#236]
Hello,

It would be nice that I can manage my ftp connections into folders or something like that cause I have a lot of ftp connections from different areas I work in
for example:
- Company I work for
- My company
- Personal
- Old

**Comment by Equals182** [comment]
Heyyy

How about some kind of "labels" functionality? Like in GitHub or Trello, you could put a label with it's own color on connection and it will be shown nearby it's name. And (in next version) you will be able to search by label, connection name, host or even login. Will it be convinient for you?
BTW, can't do it for current public version, but I'll try to do it in next version.

**Comment by tonoslav** [comment]
@Equals182 that sounds great, and also sorting in connections would be awesome too, like not only drag&drop but also A-Z or By label etc.

**Comment by Equals182** [comment]
### Hello there!

I know this issue been there for a pretty long time, but I have some good news here!
We just released eqFTP v**1.0.0-beta.0** (v1-b for short I guess) and we're completely discontinuing support of all previous versions of this plugin.
New version works great on Brackets 1.8 and it should be good on lower versions too.

So yeah, we're closing and locking this issue forever and looking forward for you to try out our new version of eqFTP.
I'm sorry if I somehow disturbed you, or you lost your interest in eqFTP or Brackets in general, we're not going to make any noise here again.

If you have any questions, please contact me via email (you can find it in [my profile](https://github.com/Equals182)) or [Telegram app](http://t.me/equals182)

Thank you for understanding 😊
