### ISSUE TITLE
Upload on save file when not connected makes eqFTP stuck in loop.  

### ISSUE THREAD

**Issue by FlemmingH** [Equals182/eqFTP#238]
I often forget to connect eqFTP when i open Brackets. Then when i save a file i see eqFTP trying to connect with no success, and it forces me to restart Brackets because i can't get eqFTP to response. I got v. 0.7.2 and this have been going on since i checked the "Upload File on Save" about 3 mo ago.

**Comment by Equals182** [comment]
I am sorry, but work on current version of eqFTP is frozen. I will not continue development of version 0.7.0 but I *will* release v0.8 someday, which will be a completely remastered version of plugin and I will try my best to avoid such bugs as this one.

**Comment by Equals182** [comment]
### Hello there!

I know this issue been there for a pretty long time, but I have some good news here!
We just released eqFTP v**1.0.0-beta.0** (v1-b for short I guess) and we're completely discontinuing support of all previous versions of this plugin.
New version works great on Brackets 1.8 and it should be good on lower versions too.

So yeah, we're closing and locking this issue forever and looking forward for you to try out our new version of eqFTP.
I'm sorry if I somehow disturbed you, or you lost your interest in eqFTP or Brackets in general, we're not going to make any noise here again.

If you have any questions, please contact me via email (you can find it in [my profile](https://github.com/Equals182)) or [Telegram app](http://t.me/equals182)

Thank you for understanding 😊
