### ISSUE TITLE
Does Not Work with Brackets 1.8

### ISSUE THREAD

**Issue by topwebs** [Equals182/eqFTP#242]
In Brackets 1.8, the folder/file screen is blank on connect.

**Comment by Equals182** [comment]
Fixed with ef04efffc00bfab4156347aea4b0d16b4a0c78cb
thanks for report!

**Comment by topwebs** [comment]
Thanks, it works now.

**Comment by hung0** [comment]
Fix works...thank you!!!

**Comment by FlemmingH** [comment]
How do i install it? Something with copying main.js to extensions folder ? But there's none with a recognizable name?

**Comment by Equals182** [comment]
**Installing directly from Github:**
1. Open Brackets’s Extension Manager
2. Click 'Install from URL’
3. Paste https://github.com/Equals182/eqFTP in new window
4. Click install and restart Brackets manually

**Downloading archive and installing locally:**
1. Download file: https://github.com/Equals182/eqFTP/raw/master/eqFTP-0.7.3.zip
2. Open Brackets’s Extension Manager
3. Drag and Drop zip file to lower part of Ext. Manager window

**Comment by FlemmingH** [comment]
Thank's! it works now :-)

**Comment by ceberS** [comment]
Thank's! ;)

**Comment by phrench** [comment]
Thanks for the fix and install directions

**Comment by Equals182** [comment]
### Hello there!

I know this issue been there for a pretty long time, but I have some good news here!
We just released eqFTP v**1.0.0-beta.0** (v1-b for short I guess) and we're completely discontinuing support of all previous versions of this plugin.
New version works great on Brackets 1.8 and it should be good on lower versions too.

So yeah, we're closing and locking this issue forever and looking forward for you to try out our new version of eqFTP.
I'm sorry if I somehow disturbed you, or you lost your interest in eqFTP or Brackets in general, we're not going to make any noise here again.

If you have any questions, please contact me via email (you can find it in [my profile](https://github.com/Equals182)) or [Telegram app](http://t.me/equals182)

Thank you for understanding 😊
