### ISSUE TITLE
Upload file issue

### ISSUE THREAD

**Issue by EcchiHiro** [Equals182/eqFTP#248]
Hi, 

I can't manage to save an upload a file with eqftp. The strange thing is that i'am already connected to the FTP and the sync mode seems to be working.

Here are the errors i'am getting : 

[eqftp-save-debug] Change event fired File
main.js:3339 [eqftp-save-debug] File is within project. Getting connection by path
main.js:3342 [eqftp-save-debug] Connection id:  false
main.js:3336 [eqftp-save-debug] Change event fired File
main.js:3339 [eqftp-save-debug] File is within project. Getting connection by path
main.js:3342 [eqftp-save-debug] Connection id:  false

Thanks for the help.

**Comment by Equals182** [comment]
### Hello there!

I know this issue been there for a pretty long time, but I have some good news here!
We just released eqFTP v**1.0.0-beta.0** (v1-b for short I guess) and we're completely discontinuing support of all previous versions of this plugin.
New version works great on Brackets 1.8 and it should be good on lower versions too.

So yeah, we're closing and locking this issue forever and looking forward for you to try out our new version of eqFTP.
I'm sorry if I somehow disturbed you, or you lost your interest in eqFTP or Brackets in general, we're not going to make any noise here again.

If you have any questions, please contact me via email (you can find it in [my profile](https://github.com/Equals182)) or [Telegram app](http://t.me/equals182)

Thank you for understanding 😊
