### ISSUE TITLE
Cannot connect to any server

### ISSUE THREAD

**Issue by aaronrobb** [Equals182/eqFTP#252]
New to eqftp.
Just set it up and tested two different servers - one ftp and one sftp.
Neither will connect.

Getting this error in the console:
Failed to clear temp storage: It was determined that certain files are unsafe for access within a Web application, or that too many calls are being made on file resources. SecurityError

SFTP connections just say "connected to server" in the green box, then nothing shows up.
FTP pops up with: {"code":"ETIMEDOUT","errno":"ETIMEDOUT","syscall":"connect"}

I'm not sure how to show the console with the full errors. After trying an ftp, there are no errors that come up in the console.

Thanks!

**Comment by Equals182** [comment]
I am sorry to say, but I can't help you with this issue now because this current version is kinda obsolete.
We're cooking next version right now and it should be available before new year. Please, stay in touch, I will post a comment here on release date.

**Comment by Equals182** [comment]
### Hello there!

I know this issue been there for a pretty long time, but I have some good news here!
We just released eqFTP v**1.0.0-beta.0** (v1-b for short I guess) and we're completely discontinuing support of all previous versions of this plugin.
New version works great on Brackets 1.8 and it should be good on lower versions too.

So yeah, we're closing and locking this issue forever and looking forward for you to try out our new version of eqFTP.
I'm sorry if I somehow disturbed you, or you lost your interest in eqFTP or Brackets in general, we're not going to make any noise here again.

If you have any questions, please contact me via email (you can find it in [my profile](https://github.com/Equals182)) or [Telegram app](http://t.me/equals182)

Thank you for understanding 😊
