### ISSUE TITLE
Panel doesn't show remote files

### ISSUE THREAD

**Issue by djwood** [Equals182/eqFTP#255]
- Brackets Release 1.8 build 1.8.0-17108
- eqFTP 0.7.2

Configuration:
- sftp
- Classic Automatization (Upload..., Even if...)
- blank remote and local paths

The devtools shows:
- successful "server_connect" event
- successful "directory_got" event with the expected "files" array objects
- eqFTP panel doesn't show any folders/files (completely blank)...
(Reluctant to attach console logs due to passwords, etc)

Looks like the SFTP is successful and retrieves the folder/files objects but the eqFTP panel is blank. The extension looks like the perfect tool for me to edit remote files directly and it's so close to working... any suggestions would be appreciated!

D

**Comment by Equals182** [comment]
Hi

Thank you for detailed and nicely organized report. I'm sorry to say, but
version 0.7 is discontinued.
We're currently working on version 1.0 that should be done by New Year. So
please stay tuned for it!

-- 
Regards,
Alex

**Comment by MonsterDeveloper** [comment]
I have got the same problem. But version is 0.7.2

**Comment by MonsterDeveloper** [comment]
Solved! Just remove Brackets v8 and download Brackets v7 here: https://github.com/adobe/brackets/releases

**Comment by Equals182** [comment]
### Hello there!

I know this issue been there for a pretty long time, but I have some good news here!
We just released eqFTP v**1.0.0-beta.0** (v1-b for short I guess) and we're completely discontinuing support of all previous versions of this plugin.
New version works great on Brackets 1.8 and it should be good on lower versions too.

So yeah, we're closing and locking this issue forever and looking forward for you to try out our new version of eqFTP.
I'm sorry if I somehow disturbed you, or you lost your interest in eqFTP or Brackets in general, we're not going to make any noise here again.

If you have any questions, please contact me via email (you can find it in [my profile](https://github.com/Equals182)) or [Telegram app](http://t.me/equals182)

Thank you for understanding 😊
