### ISSUE TITLE
Date Format Not Working

### ISSUE THREAD

**Issue by topwebs** [Equals182/eqFTP#259]
## Expected Behavior

Change date format to m.d.Y and expect to see that.
## Current Behavior

However, after changing to m.d.Y, observed format is d.m.Y

**Comment by Equals182** [comment]
Hey, really nice to see you here!
Will work on it asap
Thanks for report!

**Comment by Equals182** [comment]
It needs a restart right now or reloading settings file (choosing same again), but I'll make it right tomorrow :)

**Comment by Equals182** [comment]
Just fixed this thing. Tested it couple of times, looks good for me. Please update from GitHub and check if it works for you
