### ISSUE TITLE
Connections file not loaded

### ISSUE THREAD

**Issue by topwebs** [Equals182/eqFTP#261]
## Expected vs Current Behavior
When open eqFTP should read settings.eqftp and show previously saved connections.
## Steps to Reproduce (for bugs)
1. Open eqFTP and no connections are shown. Following is content of settings.eqftp and the file path is properly shown in settings.

{
    "misc": {
        "version": "1.0.0",
        "encrypted": false,
        "userId": "1b65cq52m"
    },
    "main": {
        "projects_folder": "C:/Users/Dan/UniServerZ/www",
        "date_format": "m.d.Y",
        "debug": true,
        "open_project_connection": false
    },
    "connections": {
        "settings": {},
        "credentials": {},
        "1b65d3rtp": {
            "name": "stlouischurches.org",
            "protocol": "sftp",
            "server": "host.topwebsnetwork.com",
            "port": "22",
            "login": "stlouischurch",
            "password": "yyyyyyyyyyy",
            "rsa": "",
            "localpath": "C:/Users/Dan/UniServerZ/www/stlouischurches.org",
            "remotepath": "public_html",
            "check_difference": true,
            "autoupload": false,
            "ignore_list": "",
            "id": "1b65d3rtp"
        }
    }
}

## Debug Information

* eqFTP version:
* Brackets version:
* Operating System and version:

**Comment by Equals182** [comment]
Oh snap I just realized that this is actually an issue I just fixed. I'm sorry, I'm dumb and I've created a new issue for this #266 
Once again, I think I fixed it, so please check #266 or just update from github + restart node and brackets manually. More info on how to do it: https://github.com/Equals182/eqFTP/issues/266#issuecomment-271857384
