### ISSUE TITLE
eqFTP won't start

### ISSUE THREAD

**Issue by sasagit** [Equals182/eqFTP#262]
## Steps to Reproduce (for bugs)
1. install new version eqFTP v1.0.0-beta.0

## Debug Information

```
Uncaught TypeError: _node.domains.eqFTP.commands is not a function(anonymous function) @ main.js:154
emit @ index.js:150
(anonymous function) @ main.js:737
j @ thirdparty.min.js:19
k.fireWith @ thirdparty.min.js:19
e.(anonymous function) @ thirdparty.min.js:19
(anonymous function) @ /utils/NodeConnection.js:523
(anonymous function) @ /utils/NodeConnection.js:523
(anonymous function) @ thirdparty.min.js:19
j @ thirdparty.min.js:19
k.fireWith @ thirdparty.min.js:19
e.(anonymous function) @ thirdparty.min.js:19
refreshInterfaceCallback @ /utils/NodeConnection.js:561
j @ thirdparty.min.js:19
k.fireWith @ thirdparty.min.js:19
x @ thirdparty.min.js:21
(anonymous function) @ thirdparty.min.js:21
```

* eqFTP version:1.0.0-beta.0
* Brackets version:
* Operating System and version:windows7

**Comment by Equals182** [comment]
It looks like your Brackets didn't restart 'node-side' of plugin, so it's still cached somewhere with old functions and without new ones. Brackets have some issues restarting Node.js process automatically.

Try restarting Brackets manually couple of times, it should help. If it doesn't, try this:

- Click Debug -> Restart Node in Brackets' Menu bar
- Press F5 in couple of seconds after that

If it's still not working:

- Uninstall eqFTP
- Restart Brackets manually
- Install eqFTP
- Restart Brackets manually again (after it restarts itself)

**Comment by sasagit** [comment]
Thank you, now eqFTP started after Debug -> Restart Node and F5.
But I got message We couldn't find your settings file ... and Create button doesn't save new one.

**Comment by Equals182** [comment]
Can you please press F12 to open DevTools in Brackets and check for errors on console there?

**Comment by Equals182** [comment]
Actually, lets move to a separate issue just so people could find it if they need to
Please follow here: #263
