### ISSUE TITLE
'Create' button doesn't save a file

### ISSUE THREAD

**Issue by Equals182** [Equals182/eqFTP#263]
## Expected vs Current Behavior
You click CREATE button on Welcome screen and it doesn't save a settings file

## Steps to Reproduce (for bugs)
1. Fresh install Brackets
2. Open panel and click Create button
3. Get confused

* eqFTP version: 1.0.0-beta.0
* Brackets version:
* Operating System and version:

**Comment by Equals182** [comment]
@sasagit please open DevTools (F12 in Brackets) and check for errors in console there?

**Comment by sasagit** [comment]
There are no errors after clicking Create button. What I have done is created new empty settings.eqftp file and opened that one. Now it works.
All connections from previous version are lost but I presume this is default behavior.

**Comment by Equals182** [comment]
Yeah, settings file has a different structure now so you need to create connections again. I'm planning to make an automatic conversion from old versions of settings to new, but it will work from this current version of eqFTP only, without support of anything < 1.0 version.

As for error, well.. you found one way to solve it, that's good. But I guess I'll need to make a better solution still.

What happens when you click 'create' button? Does it opens 'Save File' dialog? What kind of OS are you using?

**Comment by sasagit** [comment]
Yes it opens Save File dialog and when you click Save dialog closes but nothing is saved.

**Comment by Equals182** [comment]
You have Windows, macOS or Linux/Unix? I need this just to know on which one I should try to reproduce this thing.

**Comment by sasagit** [comment]
Sorry I forgot, OS is Windows 7

**Comment by Equals182** [comment]
Okay, thanks! I'll try to solve this thing or maybe find a workaround. 
Would you like to help me with this? I could put there some logs to see where it fails. You'll just need to reproduce this issue and check console for those logs.

**Comment by sasagit** [comment]
Ofcourse, just tell me what to do

**Comment by Equals182** [comment]
I've managed to reproduce it myself, so I didn't bother you with that. I just want you to test it again just in case :)

**Comment by Equals182** [comment]
Oh, sorry, forgot to mention how to update and stuff.
So, you need to update eqFTP directly from Github:

- Open **Extension Manager** and click **Install from URL**
- Put `https://github.com/Equals182/eqFTP` in there
- Restart Node + F5
- Try to reproduce the issue

**Comment by sasagit** [comment]
Yes it works now, Create button creates new settings file. The only problem is if I copy connections from previously saved setting file or even use that file itself, there are no connections in Connections list

**Comment by Equals182** [comment]
Yeah, as I said before, the structure is completely different now, event for connections part. Now we split credentials and other settings like localpath, remotepath, etc, just to encrypt only creds so we could work with everything else before you type in master password. You need to make those connections from UI again.

**Comment by sasagit** [comment]
Yes but I used settings file from new v1.0.0-beta.0 version.

I copied this data to new settings file

 

        "1b66cl3q2": {

            "name": "…",

            "protocol": "",

            "server": "…",

            "port": "",

            "login": "…",

            "password": "…",

            "rsa": "",

            "localpath": " ",

            "remotepath": "",

            "check_difference": true,

            "autoupload": true,

            "ignore_list": "",

            "id": "1b66cl3q2"

        }

But this connection is not shown in connections list. It is possible to add new connections but only new one are visible in connection list.

**Comment by sasagit** [comment]
And now even after creating new settings file and creating new connection, after restart connection disappears. If I open settings.eqftp the connection is there but not shown in Connections list.

**Comment by Equals182** [comment]
@BarryEgan I've deleted your comment from another issue due to irrelevance. Please search before you post comments or create issues. 
This issue you we're talking about is currently fixed as you can see here: https://github.com/Equals182/eqFTP/issues/263#issuecomment-271836455

**Comment by Equals182** [comment]
@sasagit can you please attach content of settings.eqftp file?
NOTE: Delete all sensitive data before you post it. Replace it with * or whatever.

**Comment by sasagit** [comment]
Here is content of settings.eqftp file

{
    "misc": {
        "version": "1.0.0",
        "encrypted": false,
        "userId": "1b66jl8bc"
    },
    "main": {
        "projects_folder": "***",
        "date_format": "d.m.Y",
        "debug": false,
        "open_project_connection": false
    },
    "connections": {
        "settings": {},
        "credentials": {},
        "1b66jr7iv": {
            "name": "***",
            "protocol": "",
            "server": "***",
            "port": "",
            "login": "***",
            "password": "***",
            "rsa": "",
            "localpath": "***",
            "remotepath": "***",
            "check_difference": true,
            "autoupload": true,
            "ignore_list": "",
            "id": "1b66jr7iv"
        }
    }
}

**Comment by Equals182** [comment]
okaay, that looks pretty bad...
I managed to reproduce it, and gonna fix it now. Please stay tuned
