### ISSUE TITLE
Use current for local path

### ISSUE THREAD

**Issue by sasagit** [Equals182/eqFTP#264]
It would be really nice if you could implement this feature when selecting Local path

**Comment by Equals182** [comment]
Just like in previous versions? That good ol magic wand?

**Comment by sasagit** [comment]
Yes that would be great!

**Comment by Equals182** [comment]
Okay, we'll add this to our tasks list!
Thank you!

**Comment by Equals182** [comment]
Hey what's up!
We've just added this feature! Check it out! You'll wind a link icon right next to local path input in connection's editor.

How to update, just in case:
- Open **Extension Manager** and click **Install from URL**
- Put `https://github.com/Equals182/eqFTP` in there
- After Brackets restarted click Debug -> Restart Node in Brackets' Menu bar
- Press F5 in couple of seconds after that

**Comment by sasagit** [comment]
Great, thank you!
