### ISSUE TITLE
What do Check difference between files and Automatically upload changes do?

### ISSUE THREAD

**Issue by sasagit** [Equals182/eqFTP#265]
In previous versions there were several options for syncing files, now there is checkbox Automatically upload changes. Are files uploaded on save, change (like when css files are changed after compiling less files), or when new file or directory is created?

Also what does Check for difference do?

**Comment by Equals182** [comment]
1. Files are uploaded on change. No matter what program changed this file, it will be uploaded unless you set ignore option to skip this file
2. Currently 'Check for difference' does nothing. It's a shame that I didn't hide this checkbox in this beta release. What it will to is that eqFTP will automatically check for differences between remote and local copy of current file on upload, download and switching between files, and if there *are* differences, it will prompt you.

**Comment by sasagit** [comment]
Than you. Also a great feature would be to have option to check for newer files on remote (compare all local and remote files and have option to download newer files from remote and/or files missing on local).
And congratulations on new version it looks really great.

**Comment by Equals182** [comment]
Oh that feature would cause a lot of troubles a presume. Like, getting all the folders, maybe thousands of them.. Need to think really hard on how to make it right, how to optimize it. I do think that this feature would be handy, but remote server may have an entire system's file structure there and good God it will be painful to get all those folders checked.

And thank you! We are trying our best to make eqFTP great again 😄

**Comment by sasagit** [comment]
Yes I believe that this could cause a lot of problems. As you said it would be handy especially when several people are working on same remote files.
