### ISSUE TITLE
Feature Request for Beta 1.0.???

### ISSUE THREAD

**Issue by zibass** [Equals182/eqFTP#267]
![featuring](https://cloud.githubusercontent.com/assets/1046248/21848657/ab6fbb56-d7e0-11e6-8e0c-b4289c73bb7d.jpg)

Hello my friend!!
I downloaded your beta directly from https://github.com/Equals182/eqFTP and is working perfectly on clean install of brackets 1.8.

Your new UI work fine, only 3 things I missed...

1.- "delete file" (or folder), from context menu.
2.- Some scrollbar for connection setting (my resolution is 1366x768 and it need scroll)
3.- Open the local proyect folder when i connect any saved proyect on eqFTP.

When I find some error or feature I'll let you know
Thanks for everything.
Good Work!
--->

* eqFTP version:1.0 Beta
* Brackets version: 1.8
* Operating System and version: Win10pro

**Comment by Equals182** [comment]
Hi!
Thank you for report!
1. Removing is already on it's way: [check here](https://github.com/Equals182/eqFTP/projects/1#card-1298111)
2. That's actually a really good request! Didn't thought about it, gonna fix it soon
3. Opening local project on connect is also in plans: [check here](https://github.com/Equals182/eqFTP/projects/1#card-1326148) and #260

I really appreciate all issues and feature requests, but c'mon, guys, please, check issues and project's board before posting anything.
Thank you again for your requests, we **will** work on them!

**Comment by Equals182** [comment]
Hey man, we've added some scrolls. Tested it on small resolutions, should work!
Please check it out yourself, follow these steps to update:

- Open **Extension Manager** and click **Install from URL**
- Put `https://github.com/Equals182/eqFTP` in there
- After Brackets restart click Debug -> Restart Node in Brackets' Menu bar
- Press F5 in couple of seconds after that
- Try to reproduce the issue

Feel free to comment/reopen if you having issues with scrollbar
As for feature requests - they a logged and we won't lose them, so don't worry about it 😉

**Comment by zibass** [comment]
tested and working... perfect!

**Comment by Equals182** [comment]
I thought I've added this but apparently I didn't
Now Settings Tab should have scroll as well
