### ISSUE TITLE
No directory/file listing

### ISSUE THREAD

**Issue by PatrickPahlke** [Equals182/eqFTP#285]
eqFTP don't list the directories and files. After connection the eqFTP box After the connection remains empty.

## Steps to Reproduce (for bugs)
- Start a SFTP connection.

## Debug Information

* eqFTP version: 0.7.2
* Brackets version: Release 1.8 Experimenteller Build 1.8.0-17108
* Operating System and version: Ubuntu 16.10

![bildschirmfoto vom 2017-03-15 19-29-47](https://cloud.githubusercontent.com/assets/22255083/23964731/c5e7dd18-09b5-11e7-8f3a-33f81a2d6c65.png)

**Comment by Equals182** [comment]
Sorry, versions below v1.0 are not supported anymore. In fact, this project is not quite supported at all lol. But at least v1.0 (which you can [download](https://github.com/Equals182/eqFTP/issues/270#issuecomment-275843216)) is working and have ALMOST same features as previous versions.
