### ISSUE TITLE
Help finding logs.

### ISSUE THREAD

**Issue by carinlynchin** [Equals182/eqFTP#295]
I just need to know where to find eqftp logs. I am trying to show all the uploads I during a specific time period.

**Comment by Equals182** [comment]
In latest version you can find logs at bottom of eqFTP panel. Click log line to expand it and see all log lines. You can also turn on debug and press F12 to open DevTools where you can switch to console to see log of all actions taken.

**Comment by carinlynchin** [comment]
I mean logs from the past... like 5 days ago. Is there a log file they get put into?On Friday, May 5, 2017, 8:42:30 AM EDT, Aleksandr <notifications@github.com> wrote:
In latest version you can find logs at bottom of eqFTP panel. Click log line to expand it and see all log lines. You can also turn on debug and press F12 to open DevTools where you can switch to console to see log of all actions taken.

**Comment by Equals182** [comment]
Nope, there's no such logs, sorry.

**Comment by carinlynchin** [comment]
its ok. I just checked linux and got the access logs from there.. Thanks anyway
On Friday, May 5, 2017, 8:52:07 AM EDT, Aleksandr <notifications@github.com> wrote:
Nope, there's no such logs, sorry.
