### ISSUE TITLE
Unable to upload new directories or files in new directories

### ISSUE THREAD

**Issue by globexdesigns** [Equals182/eqFTP#48]
1. Create a new directory in your project
2. Create a new file in that directory
3. Right-click on the new file and select Upload
4. Note that the eqFTP queue says error 553.

Looks like uploading new directories, or files in new directories doesn't work yet.

If I connect to the FTP servers with the same username/password on another FTP client and create the directory - then eqFTP can upload without any issues.

Also, the reported error "error 553" is a permissions error. Seems very strange, as I don't think this is actually a permissions issue.

**Comment by Big-Erny** [comment]
Try adding a backslash only in the remote path area. Sometimes it fixes the issue.
![slash](https://cloud.githubusercontent.com/assets/10825742/7653116/c6a58a00-fb13-11e4-8069-2b04a17b7e77.PNG)
