### ISSUE TITLE
Extension error

### ISSUE THREAD

**Issue by JackStoneDev** [Equals182/eqFTP#55]
Hello,

When I download and run eqFTP it works great, but when I close Brackets and open it again, every time I get "Extension Error." I am running OS X Yosemite beta, so could this be the issue?

**Comment by Equals182** [comment]
Consider it was a one of a kind bug. Closing.

**Comment by cleargen** [comment]
@JackStoneDev ... I had the same problem and this solution worked for me:

1) Disable all extensions: help->show extension folder->move all extensions in 'user' folder to 'disabled' folder (keep window open for manual download)
2) Reload brackets: debug->reload with extensions
3) Retry download: extension manager or manually

manually: create folder, 'brackets-emmet' in extensions folder (place inside either disabled or user)-> download emmet zip and extract-> move all extracted files to 'brackets-emmet' folder->successfully downloaded
