### ISSUE TITLE
Create empty lines after upload

### ISSUE THREAD

**Issue by AphoomZhah** [Equals182/eqFTP#60]
Hello! first I would like to say I've been using this extension for about 3 month (after trying all others), and eqFTP is just amazing!.

Now, I've just noticed this:
When I edit / save a document and it uploads through eqFTP, it creates 2 empty lines between each line of code (To test this, I downloaded the file through FilleZille, or another FTP Server).

How could I possible fix that?

Thanks!

**Comment by Equals182** [comment]
Please let me know if it's still a thing.
I'm closing it for now since there's nothing new about this problem.
Thank you for participating!
