### ISSUE TITLE
Can't open empty files

### ISSUE THREAD

**Issue by thomhines** [Equals182/eqFTP#64]
First of all, I love this plugin. One of the best implementations I've seen.

One of the main issues I'm running into right now, though, is that I can't open empty files. I'm definitely looking forward to the ability to create new files in eqFTP (please?), but for now, I can't even edit the files I make in an external FTP app if I'm working directly on the server.

The problem seems to come from this line in node/ftpDomain.js:

`if (progressTotalsize > 0) {`

I was able to quickly fix the problem on my own machine by changing the line to 

`if (progressTotalsize > -1) {`

but obviously this becomes a pretty silly if statement. However, this seemed to fix it for me! It would be great to see this ability in future versions.

Thanks!

**Comment by Equals182** [comment]
Should work in v0.7.0.
Thank you for participating!
