### ISSUE TITLE
[RU] Зависание при загрузке

### ISSUE THREAD

**Issue by xomorg** [Equals182/eqFTP#82]
Иногда возникает проблема: на иконке eqFTP появляются песочные часы и плагин перестаёт открываться. Перезагрузка или рефреш brackets не помогает, помогает лишь переустановка плагина. Что это такое и из-за чего появляется мне совершенно не понятно.

**Comment by xomorg** [comment]
16.12.2014 22:06, Alexander пишет:
>
> Вы не могли бы в следующий раз, когда он перестанет открываться нажать 
> F12, котрыть вкладку Console и показать мне красные строчки оттуда?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Equals182/eqFTP/issues/82#issuecomment-67172551>.
>
Здравствуйте. Вот скриншот

**Comment by xomorg** [comment]
16.12.2014 22:06, Alexander пишет:
>
> Вы не могли бы в следующий раз, когда он перестанет открываться нажать 
> F12, котрыть вкладку Console и показать мне красные строчки оттуда?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Equals182/eqFTP/issues/82#issuecomment-67172551>.
>
Заметил, что плагин зависает при отключенном denwer. Стоит его включить 
и обновить brackets, и плагин запускается превосходно. Остановить denwer 
- плагин перестаёт работает...

**Comment by Equals182** [comment]
Скриншот не прикрепился. От девера плагин никак не зависит и скорее всего при выключенном денвере как-то меняются настройки доступа node к сети. Проверьте, работает ли обычный менеджер дополнений при выключенном денвере?

**Comment by xomorg** [comment]
13.01.2015 11:55, Alexander пишет:
>
> Скриншот не прикрепился. От девера плагин никак не зависит и скорее 
> всего при выключенном денвере как-то меняются настройки доступа node к 
> сети. Проверьте, работает ли обычный менеджер дополнений при 
> выключенном денвере?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Equals182/eqFTP/issues/82#issuecomment-69695485>.
>
менеджер открывается, но установить ничего не получается: "неизвестная 
ошибка"

**Comment by Equals182** [comment]
Скорее всего у всего Brackets обрубается доступ к интернету, соответственно ни менеджер расширений, ни плагин работать не могут. Попробуйте проверить настройки в компьютере (что конкретно проверить, посоветовать не могу, к сожалению), либо оставляйте денвер включенным)

**Comment by goshka-kartoshka** [comment]
постоянно зависает плагин. стоит 10минут его не использовать и все, перестает отликаться, помогает только перезагрузка брекетса. Помогите, пожалуйста

**Comment by Equals182** [comment]
### Hello there!

I know this issue been there for a pretty long time, but I have some good news here!
We just released eqFTP v**1.0.0-beta.0** (v1-b for short I guess) and we're completely discontinuing support of all previous versions of this plugin.
New version works great on Brackets 1.8 and it should be good on lower versions too.

So yeah, we're closing and locking this issue forever and looking forward for you to try out our new version of eqFTP.
I'm sorry if I somehow disturbed you, or you lost your interest in eqFTP or Brackets in general, we're not going to make any noise here again.

If you have any questions, please contact me via email (you can find it in [my profile](https://github.com/Equals182)) or [Telegram app](http://t.me/equals182)

Thank you for understanding 😊
