### ISSUE TITLE
New release not working

### ISSUE THREAD

**Issue by topwebs** [Equals182/eqFTP#85]
The latest release is not working. You can't download or open files and opening folders often takes a long time. The error is:
```
Exception in 'eqFTP:getDirectory' listener on NodeConnection {domains: Object, _registeredModules: Array[1], _pendingInterfaceRefreshDeferreds: Array[0], _pendingCommandDeferreds: Array[110], _autoReconnect: true…}_autoReconnect: true_commandCount: 117_eventHandlers: Object_pendingCommandDeferreds: Array[117]_pendingInterfaceRefreshDeferreds: Array[0]_port: 52953_registeredModules: Array[1]_ws: WebSocketdomainEvents: Objectdomains: Object__proto__: NodeConnection TypeError: Cannot read property 'length' of undefined TypeError: Cannot read property 'length' of undefined
    at Function.n.extend.each (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:2725)
    at file:///C:/Users/Dan/AppData/Roaming/Brackets/extensions/user/equals182.eqftp/main.js:2391:19
    at NodeConnection.trigger (/utils/EventDispatcher.js:222:40)
    at Object.triggerWithArray (/utils/EventDispatcher.js:260:28)
    at NodeConnection._receive (/utils/NodeConnection.js:479:29)
```

**Comment by Equals182** [comment]
Looks like we gotta roll back with this. I'll check out an error you've got and try to do something. 

New version works very buggy for you. Too bad I have no servers like yours to test this stuff, 'cause it works really well with mine. Anyway, it's an alpha (I didn't thought about working on connection stuff more, though. Just planned working on SFTP and that's it). 

So yeah, I'll check v0.6.2 for your bug and try to fix it.

**Comment by Equals182** [comment]
So yeah. Can you please delete eqFTP and install it from here: https://github.com/Equals182/Buggy-eqFTP/tree/0.6.2-debug ?
I've added some logs so I need you to turn debug mode on and try to do same things and see what will happen.

**Comment by topwebs** [comment]
I installed above version. First time of use with debug on, sites wouldn't open at all. Then, I turned debug off and back on and now sites load and downloading works without errors, as well as uploading. Not sure what's going on, but it seems to be working now.

**Comment by Equals182** [comment]
I'm not sure why that happened. I've added just two lines of `console.log` and nothing more. Updating this extension is always a problem. I've seen things even more weird than this. Like function executing just one line of it's code and nothing more, even if second line is console.log.
Anyway, yeah, that happens and it's kinda sad. If there are some issues after update - try reloading node and restart Brackets manually, it helps in most of cases.

Thank you for using this extension.
