### ISSUE TITLE
Sort in listing?

### ISSUE THREAD

**Issue by Licciardi** [Equals182/eqFTP#86]
Hello,

is it possible to set up a sort in the listing for each FTP connections by alphabet?

**Comment by Wikunia** [comment]
@Equals182 works on that feature and it will be part of v0.7.0: http://pastebin.com/raw.php?i=URb9Az1n

**Comment by Equals182** [comment]
Hey! Looks like I've got my personal manager right here! Thanks @Wikunia for answer, you're totally right.
