### ISSUE TITLE
Is sftp supported?

### ISSUE THREAD

**Issue by bagusflyer** [Equals182/eqFTP#9]
I found this wonderful extension for Bracket. But I'm wondering if sftp is supported or is going to be supported? Thanks

**Comment by Equals182** [comment]
Sup guys! Still waiting? Have an update: https://twitter.com/Equals182/status/552580775884103682

**Comment by amaradrys** [comment]
Cool !!
When ???? ^^

**Comment by Equals182** [comment]
So.. Anyone wanna test sftp and lots of other stuff? 
Install from here: https://github.com/Equals182/Buggy-eqFTP
