### ISSUE TITLE
eqFTP Lost Password ?

### ISSUE THREAD

**Issue by SheepDomination** [Equals182/eqFTP#90]
I made a password for eqFTP, I can't use it because it asks for a password, how can I find out the password I had entered, or how can I change the password ?

**Comment by Equals182** [comment]
Hi! There's no way to restore your password for eqFTP: https://github.com/Equals182/eqFTP/wiki/1.1.-Setting-Up#store-passwords-safely (see at very bottom of page)
You can click cancel when it ask password, go to settings uncheck "store passwords safely" option and click save. This should **overwrite** your settings file and you'll need to set up connections again.

About changing password when you *remember* it: go to settings, uncheck "store passwords safely" option, click save, check it again and enter new password.

**Comment by SheepDomination** [comment]
Thanks ;-)
