### ISSUE TITLE
Stylus.styl problem

### ISSUE THREAD

**Issue by luisameglio** [Equals182/eqFTP#91]
Hello,
Everytime I try to upload the style.styl file, I get an error and it wont upload it to the server do you know why is that?

Thank u in advanced.

best Regards!

Awesome plugin!!

**Comment by Equals182** [comment]
Hi
Well.. It could be permissions problem or something else, not sure.
Can you please turn on debug mode in eqFTP settings, then press F12, go to console tab and then try to upload your file and post logs from console here? Don't forget to hide personal data in logs!

**Comment by luisameglio** [comment]
ok, I fixed the problem by creating the stylus folder manually using the file manager in my cpanel, so the question is if eqFTP is not capable of creating new folders in the server when uploading it from my computer?

**Comment by Equals182** [comment]
it is capable. well.. not in every case. v0.7.0 of eqFTP should fix some problems with that but still - if server just says 'access denied', then I can't do anything about it. But yeah, there were some problems with folder creation in some cases, sorry about that.
Thank you for using eqFTP :D

**Comment by luisameglio** [comment]
Oh ok, well I'll be waiting for the new version.. thank you again!

**Comment by Equals182** [comment]
It should be released pretty soon, it's almost done :)

**Comment by luisameglio** [comment]
Hello Again,
I have a question about the option "store password safely", when is checked, it keeps asking me for a password is this how it suppose to work?

**Comment by Equals182** [comment]
Hey :) 
That's why I wrote it in Wiki: https://github.com/Equals182/eqFTP/wiki/1.6-Frequently-Asked-Questions#what-is-password-for-eqftp
