### ISSUE TITLE
Upload CSS file when LESS file is saved

### ISSUE THREAD

**Issue by matty1491** [Equals182/eqFTP#93]
Hi there,

I currently have my extension set up so that files "upload on save". However, when I save my LESS file, the LESS file uploads, but not the CSS file. Any way I could get the CSS file uploaded as well without having to manually do it every time?

Thanks,
Matt

**Comment by Equals182** [comment]
In v0.7.0 you will have this option. Also it's already been asked here #59 
This version will give you possibility to upload everything that been changed (in any way) in project's folder. Also you'll be able to set up ignore list that will work just like .gitignore stuff.
