### ISSUE TITLE
SFTP not working

### ISSUE THREAD

**Issue by MrStickmanPro1** [Equals182/eqFTP#94]
When I try to select the Protocol-type for creating a new server, I cannot select any other than FTP.
The Entries can't be clicked on. If you need any more details, please ask me.

**Comment by Equals182** [comment]
That's because SFTP is still in plans. I mean it's done, but your version is most likely not 0.7.0
As you may see #9 is still opened and here #73 you may see some progress on v0.7.0
Anyway it will be done preeeetttyyyy soon, stay tuned.
