### ISSUE TITLE
Issues 0.7.0

### ISSUE THREAD

**Issue by Wikunia** [Equals182/eqFTP#97]
Hey Alex,

I found some unexpected behavior in your new version.
It looks like you have a toggle mode for your sorting: First `unsorted` then `asc` then `desc` but I would like to click on the down arrow:
![eqftp-sorting](https://cloud.githubusercontent.com/assets/4931746/6191497/1eb1c274-b3aa-11e4-832d-b46a97190490.png)
to start the `desc` mode
![eqftp-sorting-correct](https://cloud.githubusercontent.com/assets/4931746/6191496/1eb05a24-b3aa-11e4-9fb0-3fae7be338a4.png)
At the moment:
![eqftp-sorting-wrong](https://cloud.githubusercontent.com/assets/4931746/6191495/1eaf953a-b3aa-11e4-926b-5e216d288d81.png)

When I open the preferences and change some settings and close the panel I would like to see a panel which asks me whether I want to save the changes. 

Looks like there is no animation on your icon in the sidebar when the extension uploads things. :/
That was a nice feature, cause the user can verify that the extension is in action.

Thanks for your awesome extension!

**Comment by Equals182** [comment]
Soooo
1. Unsorted, Desc, Asc, right?
2. This is nice feature request. Also saving now works for every connection separately, not like it was before and you may switch between connections without afraid that you may loose some data. Of course when you close settings everything that wasn't saved is lost.
3. Oh.. Yeah, animation was for completed action actually :) Anyway I thought about some notification stuff. Maybe using my new fancy notifications on right bottom? Or they are too big for this.. Don't know, suggest please :D Icon or notification?

**Comment by Wikunia** [comment]
Hey
1.) It depends: When the user clicks on the down arrow it should switch to `desc` and click again to `unsorted`. When the user clicks on the upper arrow => `asc` then `unsorted` when the user clicks on the name you can make the current 3 toggle option.
3.) You have a notification option in your settings so maybe you would like to add an animation option as well but I would make that one checked by default cause it was the default in earlier versions.

**Comment by Equals182** [comment]
Alright, got it!

**Comment by Equals182** [comment]
Oh, I just noticed.. Icon for sorting.. It's solid.. So making it separate and adding those events you demanding is not that easy and quick as I thought. I'll leave it as feature request for later. Hope you aren't mad :)

**Comment by Equals182** [comment]
### Hello there!

I know this issue been there for a pretty long time, but I have some good news here!
We just released eqFTP v**1.0.0-beta.0** (v1-b for short I guess) and we're completely discontinuing support of all previous versions of this plugin.
New version works great on Brackets 1.8 and it should be good on lower versions too.

So yeah, we're closing and locking this issue forever and looking forward for you to try out our new version of eqFTP.
I'm sorry if I somehow disturbed you, or you lost your interest in eqFTP or Brackets in general, we're not going to make any noise here again.

If you have any questions, please contact me via email (you can find it in [my profile](https://github.com/Equals182)) or [Telegram app](http://t.me/equals182)

Thank you for understanding 😊
